# GENERATED BY GLM
"""几何题推理AI的渲染引擎。

该模块提供几何渲染和数值验证功能。
"""

import math
from typing import List, Tuple, Optional, Dict, Any
from dataclasses import dataclass
import random


ATOM = 1e-9


@dataclass
class Point:
    x: float
    y: float

    def __add__(self, other: "Point") -> "Point":
        return Point(self.x + other.x, self.y + other.y)

    def __sub__(self, other: "Point") -> "Point":
        return Point(self.x - other.x, self.y - other.y)

    def __mul__(self, scalar: float) -> "Point":
        return Point(self.x * scalar, self.y * scalar)

    def __rmul__(self, scalar: float) -> "Point":
        return self.__mul__(scalar)

    def distance(self, other: "Point") -> float:
        dx = self.x - other.x
        dy = self.y - other.y
        return math.sqrt(dx * dx + dy * dy)

    def close(self, other: "Point", tol: float = ATOM) -> bool:
        return abs(self.x - other.x) < tol and abs(self.y - other.y) < tol


@dataclass
class Line:
    a: float
    b: float
    c: float

    @classmethod
    def from_points(cls, p1: Point, p2: Point) -> "Line":
        if p1.close(p2):
            a, b, c = 0.0, 0.0, 0.0
        else:
            a = p1.y - p2.y
            b = p2.x - p1.x
            c = p1.x * p2.y - p2.x * p1.y
            if a < 0 or (a == 0 and b > 0):
                a, b, c = -a, -b, -c
        return cls(a, b, c)

    def distance(self, p: Point) -> float:
        denom = math.sqrt(self.a**2 + self.b**2)
        if denom < ATOM:
            return 0.0
        return abs(self.a * p.x + self.b * p.y + self.c) / denom

    def is_parallel(self, other: "Line") -> bool:
        return abs(self.a * other.b - self.b * other.a) < ATOM

    def is_perpendicular(self, other: "Line") -> bool:
        return abs(self.a * other.a + self.b * other.b) < ATOM

    def intersect(self, other: "Line") -> Optional[Point]:
        d = self.a * other.b - other.a * self.b
        if abs(d) < ATOM:
            return None
        x = (other.c * self.b - self.c * other.b) / d
        y = (self.c * other.a - other.c * self.a) / d
        return Point(x, y)


@dataclass
class Circle:
    center: Point
    radius: float

    @classmethod
    def from_three_points(cls, p1: Point, p2: Point, p3: Point) -> Optional["Circle"]:
        l12 = Line.from_points(p1, p2)
        l23 = Line.from_points(p2, p3)

        mid12 = Point((p1.x + p2.x) / 2, (p1.y + p2.y) / 2)
        mid23 = Point((p2.x + p3.x) / 2, (p2.y + p3.y) / 2)

        perp12 = Line(-l12.b, l12.a, l12.b * mid12.x - l12.a * mid12.y)
        perp23 = Line(-l23.b, l23.a, l23.b * mid23.x - l23.a * mid23.y)

        center = perp12.intersect(perp23)
        if center is None:
            return None

        radius = center.distance(p1)
        return cls(center, radius)

    def contains(self, p: Point, tol: float = ATOM) -> bool:
        return abs(self.center.distance(p) - self.radius) < tol


class RenderEngine:
    def __init__(self, seed: int = 42):
        random.seed(seed)
        self.points: Dict[str, Point] = {}
        self.lines: Dict[str, Line] = {}
        self.circles: Dict[str, Circle] = {}

    def parse_proposition(self, prop_str: str) -> Dict[str, Any]:
        tokens = prop_str.strip().split()
        result: Dict[str, Any] = {"type": None, "points": [], "relations": []}

        if not tokens:
            return result

        result["type"] = tokens[0]
        result["points"] = [t for t in tokens[1:] if t.isalpha() and len(t) == 1]

        return result

    def create_random_point(
        self, _name: str, existing: Optional[List[Point]] = None
    ) -> Point:
        if existing:
            cx = sum(p.x for p in existing) / len(existing)
            cy = sum(p.y for p in existing) / len(existing)
            scale = (
                max(p.distance(Point(cx, cy)) for p in existing) if existing else 1.0
            )
        else:
            cx, cy = 0.0, 0.0
            scale = 1.0

        for _ in range(100):
            angle = random.uniform(0, 2 * math.pi)
            dist = random.uniform(0.5, 2.0) * scale
            p = Point(cx + dist * math.cos(angle), cy + dist * math.sin(angle))

            valid = True
            if existing:
                for ep in existing:
                    if p.close(ep, tol=0.1 * scale):
                        valid = False
                        break

            if valid:
                return p

        return Point(random.uniform(-1, 1), random.uniform(-1, 1))

    def verify_collinear(self, points: List[Point]) -> bool:
        if len(points) < 3:
            return True

        line = Line.from_points(points[0], points[1])
        for p in points[2:]:
            if line.distance(p) > ATOM:
                return False
        return True

    def verify_parallel(self, p1: Point, p2: Point, p3: Point, p4: Point) -> bool:
        l1 = Line.from_points(p1, p2)
        l2 = Line.from_points(p3, p4)
        return l1.is_parallel(l2)

    def verify_perpendicular(self, p1: Point, p2: Point, p3: Point, p4: Point) -> bool:
        l1 = Line.from_points(p1, p2)
        l2 = Line.from_points(p3, p4)
        return l1.is_perpendicular(l2)

    def verify_congruent(self, p1: Point, p2: Point, p3: Point, p4: Point) -> bool:
        d1 = p1.distance(p2)
        d2 = p3.distance(p4)
        return abs(d1 - d2) < ATOM

    def verify_midpoint(self, m: Point, a: Point, b: Point) -> bool:
        return self.verify_collinear([m, a, b]) and self.verify_congruent(m, a, m, b)

    def verify_cyclic(self, points: List[Point]) -> bool:
        if len(points) < 4:
            return True

        circle = Circle.from_three_points(points[0], points[1], points[2])
        if circle is None:
            return False

        for p in points[3:]:
            if not circle.contains(p):
                return False
        return True

    def verify_proposition(self, prop_type: str, points: List[Point]) -> bool:
        if len(points) < 2:
            return True

        if prop_type == "coll":
            return self.verify_collinear(points)
        if prop_type == "para":
            if len(points) < 4:
                return True
            return self.verify_parallel(points[0], points[1], points[2], points[3])
        if prop_type == "perp":
            if len(points) < 4:
                return True
            return self.verify_perpendicular(points[0], points[1], points[2], points[3])
        if prop_type == "cong":
            if len(points) < 4:
                return True
            return self.verify_congruent(points[0], points[1], points[2], points[3])
        if prop_type == "midp":
            if len(points) < 3:
                return True
            return self.verify_midpoint(points[0], points[1], points[2])
        if prop_type == "cyclic":
            return self.verify_cyclic(points)
        return True

    def render_and_verify(
        self, proposition: str, point_coords: Optional[Dict[str, Any]] = None
    ) -> Tuple[bool, str]:
        parsed = self.parse_proposition(proposition)

        if not parsed["type"] or not parsed["points"]:
            return False, "Invalid proposition format"

        prop_type = parsed["type"]
        point_names: List[str] = parsed["points"]

        if point_coords is None:
            existing = list(self.points.values())
            for name in point_names:
                if name not in self.points:
                    self.points[name] = self.create_random_point(name, existing)
                    existing.append(self.points[name])

        points: List[Point] = []
        for name in point_names:
            pt = self.points.get(name)
            if pt is not None:
                points.append(pt)

        if len(points) != len(point_names):
            return False, f"Missing point coordinates for proposition: {proposition}"

        result = self.verify_proposition(prop_type, points)

        return (
            result,
            f"Proposition '{proposition}' is {'valid' if result else 'invalid'}",
        )

    def reset(self):
        self.points = {}
        self.lines = {}
        self.circles = {}


if __name__ == "__main__":
    engine = RenderEngine()

    engine.points = {
        "A": Point(0, 0),
        "B": Point(1, 0),
        "C": Point(0.5, math.sqrt(3) / 2),
    }

    result, msg = engine.render_and_verify("coll A B C")
    print(f"共线测试: {msg}")

    engine.points["D"] = Point(0.5, 0)
    result, msg = engine.render_and_verify("midp D A B")
    print(f"中点测试: {msg}")

    engine.points["E"] = Point(0, 1)
    result, msg = engine.render_and_verify("perp A B A E")
    print(f"垂直测试: {msg}")
