# GENERATED BY GLM
"""几何题推理AI的符号引擎。

该模块提供类似于AlphaGeometry的DD的符号演绎功能。
"""

from typing import List, Set, Dict, Tuple, Optional
from dataclasses import dataclass, field


@dataclass
class Statement:
    predicate: str
    args: Tuple[str, ...]

    def __str__(self):
        return f"{self.predicate} {' '.join(self.args)}"

    def __hash__(self):
        return hash((self.predicate, self.args))

    def __eq__(self, other):
        if not isinstance(other, Statement):
            return False
        return self.predicate == other.predicate and self.args == other.args


@dataclass
class ProofState:
    statements: Set[Statement] = field(default_factory=set)
    derived: Set[Statement] = field(default_factory=set)

    def add(self, stmt: Statement, is_derived: bool = False):
        self.statements.add(stmt)
        if is_derived:
            self.derived.add(stmt)

    def contains(self, stmt: Statement) -> bool:
        return stmt in self.statements

    def get_by_predicate(self, predicate: str) -> List[Statement]:
        return [s for s in self.statements if s.predicate == predicate]


class DeductionRule:
    def __init__(self, name: str, premises: List[str], conclusions: List[str]):
        self.name = name
        self.premises = premises
        self.conclusions = conclusions

    def apply(self, state: ProofState) -> List[Statement]:
        new_statements = []

        premise_stmts = [self._parse_statement(p) for p in self.premises]
        conclusion_stmts = [self._parse_statement(c) for c in self.conclusions]

        bindings_list = self._find_bindings(state, premise_stmts)

        for bindings in bindings_list:
            for conc in conclusion_stmts:
                bound_args = tuple(bindings.get(arg, arg) for arg in conc.args)
                new_stmt = Statement(conc.predicate, bound_args)
                if not state.contains(new_stmt):
                    new_statements.append(new_stmt)

        return new_statements

    def _parse_statement(self, stmt_str: str) -> Statement:
        parts = stmt_str.split()
        if not parts:
            return Statement("", ())
        return Statement(parts[0], tuple(parts[1:]))

    def _find_bindings(
        self, state: ProofState, patterns: List[Statement]
    ) -> List[Dict[str, str]]:
        if not patterns:
            return [{}]

        first_pattern = patterns[0]
        rest_patterns = patterns[1:]

        candidates = state.get_by_predicate(first_pattern.predicate)
        bindings_list = []

        for candidate in candidates:
            bindings = self._match_pattern(first_pattern.args, candidate.args)
            if bindings is not None:
                rest_bindings = self._find_bindings(state, rest_patterns)
                for rest_binding in rest_bindings:
                    combined = {**bindings, **rest_binding}
                    if self._is_consistent(combined):
                        bindings_list.append(combined)

        return bindings_list

    def _match_pattern(
        self, pattern_args: Tuple[str, ...], actual_args: Tuple[str, ...]
    ) -> Optional[Dict[str, str]]:
        if len(pattern_args) != len(actual_args):
            return None

        bindings: Dict[str, str] = {}
        for p, a in zip(pattern_args, actual_args):
            if p.isupper():
                if p in bindings and bindings[p] != a:
                    return None
                bindings[p] = a
            elif p != a:
                return None

        return bindings

    def _is_consistent(self, _bindings: Dict[str, str]) -> bool:
        return True


BUILTIN_RULES = [
    DeductionRule("perp_to_para", ["perp A B C D", "perp E F C D"], ["para A B E F"]),
    DeductionRule("para_to_para", ["para A B C D", "para C D E F"], ["para A B E F"]),
    DeductionRule("midp_to_cong", ["midp M A B"], ["cong A M M B"]),
    DeductionRule("cong_trans", ["cong A B C D", "cong C D E F"], ["cong A B E F"]),
    DeductionRule("cong_refl", [], ["cong A A B B"]),
    DeductionRule("circle_def", ["circle O A", "circle O B"], ["cong O A O B"]),
    DeductionRule("cyclic_perp", ["cyclic A B C D", "perp A B B C"], ["perp C D D A"]),
    DeductionRule("isos_triangle", ["cong A B A C"], ["eqangle B A C A C A B"]),
]


class SymbolicEngine:
    def __init__(self, rules: Optional[List[DeductionRule]] = None):
        self.rules = rules if rules is not None else BUILTIN_RULES.copy()
        self.state = ProofState()
        self.max_iterations = 100

    def add_statement(self, stmt_str: str, is_derived: bool = False) -> Statement:
        stmt = self._parse_statement(stmt_str)
        self.state.add(stmt, is_derived)
        return stmt

    def _parse_statement(self, stmt_str: str) -> Statement:
        stmt_str = stmt_str.strip()
        parts = stmt_str.split()
        if not parts:
            return Statement("", ())
        return Statement(parts[0], tuple(parts[1:]))

    def apply_rules(self) -> List[Statement]:
        new_statements = []
        for rule in self.rules:
            derived = rule.apply(self.state)
            for stmt in derived:
                self.state.add(stmt, is_derived=True)
                new_statements.append(stmt)
        return new_statements

    def deduce(self, max_steps: Optional[int] = None) -> int:
        actual_max_steps = max_steps if max_steps is not None else self.max_iterations
        total_new = 0

        for _ in range(actual_max_steps):
            new = self.apply_rules()
            total_new += len(new)
            if not new:
                break

        return total_new

    def verify(self, stmt_str: str) -> bool:
        stmt = self._parse_statement(stmt_str)
        return self.state.contains(stmt)

    def can_derive(
        self, stmt_str: str, max_steps: Optional[int] = None
    ) -> Tuple[bool, List[Statement]]:
        if self.verify(stmt_str):
            return True, []

        original_state = ProofState(
            statements=self.state.statements.copy(), derived=self.state.derived.copy()
        )

        target = self._parse_statement(stmt_str)
        derivation_path = []

        actual_max_steps = max_steps if max_steps is not None else self.max_iterations

        for _ in range(actual_max_steps):
            new = self.apply_rules()
            derivation_path.extend(new)

            if self.state.contains(target):
                return True, derivation_path

        self.state = original_state
        return False, []

    def reset(self):
        self.state = ProofState()

    def get_all_statements(self) -> List[str]:
        return [str(s) for s in self.state.statements]

    def get_derived_statements(self) -> List[str]:
        return [str(s) for s in self.state.derived]


if __name__ == "__main__":
    engine = SymbolicEngine()

    engine.add_statement("perp A B C D")
    engine.add_statement("perp E F C D")

    new = engine.deduce()
    print(f"推导出 {new} 条新语句")

    result, path = engine.can_derive("para A B E F")
    print(f"能否推导 'para A B E F': {result}")
    if path:
        print("推导路径:")
        for stmt in path:
            print(f"  {stmt}")

    print("\n所有语句:")
    for stmt_str in engine.get_all_statements():
        print(f"  {stmt_str}")
