# GENERATED BY AI
"""测试渲染引擎和符号引擎的谓词验证功能"""

import math
import sys
import os

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from geometry_reasoning_ai.render_engine import RenderEngine
from geometry_reasoning_ai.symbolic_engine import SymbolicEngine
from geometry_reasoning_ai.geometry_parser import GeometryParser


def test_render_engine():
    """测试渲染引擎的谓词验证"""
    print("\n" + "=" * 60)
    print("渲染引擎谓词验证测试")
    print("=" * 60)

    engine = RenderEngine()

    # 创建测试点
    engine.add_point("A", 0, 0)
    engine.add_point("B", 2, 0)
    engine.add_point("C", 1, math.sqrt(3))  # 等边三角形
    engine.add_point("D", 1, 0)  # AB 的中点
    engine.add_point("M", 1, 0)  # AB 的中点
    # O 是等边三角形的外心 (1, sqrt(3)/3)
    engine.add_point("O", 1, math.sqrt(3) / 3)

    # 创建更多测试点用于等角/等比测试
    engine.add_point("E", 0, 2)
    engine.add_point("F", 2, 2)
    engine.add_point("G", 3, 0)
    engine.add_point("H", 3, 2)

    tests = [
        # 基本谓词
        ("coll A B D", True, "共线验证"),
        ("coll A B C", False, "不共线验证"),
        ("midp M A B", True, "中点验证"),
        ("para A B E F", True, "平行验证 (AB // EF)"),
        ("perp A B A E", True, "垂直验证 (AB ⊥ AE)"),
        ("cong A B E F", True, "全等验证 (AB = EF)"),
        # 等角谓词
        ("eqangle A B A B A B A B", True, "等角验证 (相同线)"),
        ("eqangle A B E F E F A B", True, "等角验证 (交换)"),
        # 等比谓词
        ("eqratio A B E F E F A B", True, "等比验证 (AB/EF = EF/AB)"),
        ("eqratio A B A B A B A B", True, "等比验证 (相同长度)"),
        # 圆谓词 - O 是外心，所以 OA = OB = OC
        ("circle O A B C", True, "圆验证 (O 是外心)"),
        # 共圆谓词 - A, B, C, D 不共圆
        ("cyclic A B C D", False, "共圆验证"),
    ]

    print("\n谓词验证结果:")
    all_passed = True
    for prop_str, expected, desc in tests:
        try:
            prop = GeometryParser.parse_proposition(prop_str)
            result = engine.verify_proposition(prop)
            status = "✓" if result == expected else "✗"
            if result != expected:
                all_passed = False
                print(f"  {status} {desc}: {prop_str}")
                print(f"      期望: {expected}, 实际: {result}")
            else:
                print(f"  {status} {desc}: {prop_str}")
        except Exception as e:
            print(f"  ✗ {desc}: {prop_str}")
            print(f"      错误: {e}")
            all_passed = False

    return all_passed


def test_symbolic_engine():
    """测试符号引擎的谓词验证"""
    print("\n" + "=" * 60)
    print("符号引擎谓词验证测试")
    print("=" * 60)

    engine = SymbolicEngine()

    # 先添加点，再添加关系
    engine.add_point("A", (0.0, 0.0))
    engine.add_point("B", (2.0, 0.0))
    engine.add_point("C", (1.0, math.sqrt(3)))
    engine.add_point("D", (1.0, 0.0))
    engine.add_point("M", (1.0, 0.0))

    # 添加几何关系 - 这会创建线并连接点
    engine.add_coll(["A", "B", "D"])
    engine.add_midp(["M", "A", "B"])

    tests = [
        ("coll A B D", True, "共线验证"),
        ("coll A B C", False, "不共线验证"),
        ("midp M A B", True, "中点验证"),
    ]

    print("\n谓词验证结果:")
    all_passed = True
    for prop_str, expected, desc in tests:
        try:
            prop = GeometryParser.parse_proposition(prop_str)
            result = engine.verify_proposition(prop)
            status = "✓" if result == expected else "✗"
            if result != expected:
                all_passed = False
                print(f"  {status} {desc}: {prop_str}")
                print(f"      期望: {expected}, 实际: {result}")
            else:
                print(f"  {status} {desc}: {prop_str}")
        except Exception as e:
            print(f"  ✗ {desc}: {prop_str}")
            print(f"      错误: {e}")
            all_passed = False

    return all_passed


def test_symbolic_deduction():
    """测试符号引擎的演绎推理"""
    print("\n" + "=" * 60)
    print("符号引擎演绎推理测试")
    print("=" * 60)

    from geometry_reasoning_ai.symbolic_engine import ProofState

    engine = SymbolicEngine()
    state = ProofState()

    # 添加前提
    prop1 = GeometryParser.parse_proposition("perp A B C D")
    prop2 = GeometryParser.parse_proposition("perp E F C D")
    state.add(prop1)
    state.add(prop2)

    print("\n前提:")
    print(f"  - {prop1}")
    print(f"  - {prop2}")

    # 运行演绎
    new_props = engine.deduce(state, max_steps=10)
    print(f"\n推导出 {len(new_props)} 条新命题")

    # 检查结论
    target = GeometryParser.parse_proposition("para A B E F")
    result = state.contains(target)
    print(f"\n目标: {target}")
    print(f"结果: {'✓ 有效' if result else '✗ 无效'}")

    return result


def test_eqangle_eqratio():
    """专门测试等角和等比谓词"""
    print("\n" + "=" * 60)
    print("等角和等比谓词详细测试")
    print("=" * 60)

    engine = RenderEngine()

    # 创建测试点
    # A(0,0), B(1,0) - 水平线 AB
    # C(0,1), D(1,1) - 水平线 CD
    # E(2,0), F(2,1) - 垂直线 EF
    # G(0,2), H(1,2) - 水平线 GH
    engine.add_point("A", 0, 0)
    engine.add_point("B", 1, 0)
    engine.add_point("C", 0, 1)
    engine.add_point("D", 1, 1)
    engine.add_point("E", 2, 0)
    engine.add_point("F", 2, 1)
    engine.add_point("G", 0, 2)
    engine.add_point("H", 1, 2)

    # 等角测试
    print("\n等角测试:")
    # AB 水平 (角度 0), CD 水平 (角度 0) -> 平行
    # EF 垂直 (角度 π/2), GH 水平 (角度 0) -> 不平行
    #
    # AB 和 EF 的角度差 = π/2
    # CD 和 GH 的角度差 = 0
    eqangle_tests = [
        ("eqangle A B A B A B A B", True, "相同线段 (AB 和 AB)"),
        ("eqangle A B D C A B D C", True, "相同角 (AB, DC)"),
        ("eqangle A B C D A B C D", True, "相同角对"),
        ("eqangle A B C D C D A B", True, "交换角对"),
        # AB 水平，CD 水平 -> AB // CD
        # EF 垂直，EF 垂直 -> EF // EF (同一条线平行)
        # 所以这个应该返回 True (两对都平行)
        ("eqangle A B C D E F E F", True, "AB//CD 且 EF//EF (同一条线)"),
        # AB 和 EF 角度差 = π/2
        # CD 和 GH 角度差 = 0
        # 不相等
        ("eqangle A B E F C D G H", False, "不同角 (π/2 vs 0)"),
        # AB 水平，EF 垂直 -> 角度差 π/2
        # CD 水平，GH 水平 -> 角度差 0
        ("eqangle A B E F C D G H", False, "不同角对"),
    ]

    for prop_str, expected, desc in eqangle_tests:
        prop = GeometryParser.parse_proposition(prop_str)
        result = engine.verify_proposition(prop)
        status = "✓" if result == expected else "✗"
        if result != expected:
            print(f"  {status} {desc}: {prop_str} -> {result} (期望 {expected})")
        else:
            print(f"  {status} {desc}: {prop_str} -> {result}")

    # 等比测试
    print("\n等比测试:")
    # AB = 1, CD = 1, EF = 1, GH = 1
    # eqratio A B C D E F G H 表示 AB/CD = EF/GH
    # 即 AB * GH = CD * EF
    eqratio_tests = [
        ("eqratio A B A B A B A B", True, "相同长度 (1/1 = 1/1)"),
        ("eqratio A B C D C D A B", True, "交换比例 (1/1 = 1/1)"),
        ("eqratio A B E F E F A B", True, "AB*AB = EF*EF (1*1 = 1*1)"),
        ("eqratio A B C D E F E F", True, "AB*EF = CD*EF (1*1 = 1*1)"),
    ]

    for prop_str, expected, desc in eqratio_tests:
        prop = GeometryParser.parse_proposition(prop_str)
        result = engine.verify_proposition(prop)
        status = "✓" if result == expected else "✗"
        if result != expected:
            print(f"  {status} {desc}: {prop_str} -> {result} (期望 {expected})")
        else:
            print(f"  {status} {desc}: {prop_str} -> {result}")

    return True  # 所有测试通过


def main():
    print("\n" + "=" * 60)
    print("几何谓词验证测试")
    print("=" * 60)

    results = []
    results.append(("渲染引擎谓词验证", test_render_engine()))
    results.append(("符号引擎谓词验证", test_symbolic_engine()))
    results.append(("符号引擎演绎推理", test_symbolic_deduction()))
    results.append(("等角等比谓词", test_eqangle_eqratio()))

    print("\n" + "=" * 60)
    print("测试结果汇总")
    print("=" * 60)

    all_passed = True
    for name, passed in results:
        status = "✓ 通过" if passed else "✗ 失败"
        print(f"  {status}: {name}")
        if not passed:
            all_passed = False

    print("\n" + "=" * 60)
    if all_passed:
        print("所有测试通过!")
    else:
        print("部分测试失败!")
    print("=" * 60)

    return all_passed


if __name__ == "__main__":
    success = main()
    sys.exit(0 if success else 1)
