# GENERATED BY AI
"""几何题推理AI - 主入口。

本包提供几何题推理AI的完整实现，包括：
- 编码器、解码器和推理AI模型
- 几何命题解析和验证
- 训练流水线
- 推理工作流程
"""

from .config import (
    DecoderConfig,
    EncoderConfig,
    EventConfig,
    ModelConfig,
    ReasoningAIConfig,
    SystemConfig,
    TrainingConfig,
    get_default_config,
)
from .event_system import Event, EventSequence
from .geometry_parser import Construction, GeometryParser, Problem, Proposition
from .models import (
    Decoder,
    Encoder,
    FeedForward,
    MultiHeadAttention,
    PositionalEncoding,
    ReasoningAI,
    TransformerDecoderLayer,
    TransformerEncoderLayer,
    count_parameters,
)
from .proposition_manager import (
    PropositionList,
    PropositionManager,
    PropositionRecord,
    RenderPropositionList,
    SymbolicPropositionList,
)
from .render_engine import RenderCircle, RenderEngine, RenderLine, RenderPoint
from .symbolic_engine import ProofState, SymbolicEngine
from .tokenizer import GeometryTokenizer, Token
from .training import (
    EncoderDecoderTrainer,
    RewardConfig,
    RLTrainer,
    SupervisedTrainer,
    TrainingPipeline,
)
from .workflow import GeometryReasoningSystem, ReasoningStep

__version__ = "0.1.0"

__all__ = [
    "GeometryReasoningSystem",
    "ReasoningStep",
    "Encoder",
    "Decoder",
    "ReasoningAI",
    "PositionalEncoding",
    "MultiHeadAttention",
    "FeedForward",
    "TransformerEncoderLayer",
    "TransformerDecoderLayer",
    "count_parameters",
    "GeometryTokenizer",
    "Token",
    "Event",
    "EventSequence",
    "RenderEngine",
    "RenderPoint",
    "RenderLine",
    "RenderCircle",
    "SymbolicEngine",
    "ProofState",
    "GeometryParser",
    "Proposition",
    "Construction",
    "Problem",
    "PropositionManager",
    "PropositionList",
    "PropositionRecord",
    "SymbolicPropositionList",
    "RenderPropositionList",
    "EncoderDecoderTrainer",
    "SupervisedTrainer",
    "RLTrainer",
    "TrainingPipeline",
    "RewardConfig",
    "SystemConfig",
    "EncoderConfig",
    "DecoderConfig",
    "ReasoningAIConfig",
    "TrainingConfig",
    "EventConfig",
    "ModelConfig",
    "get_default_config",
]
