# GENERATED BY AI
"""检查 AlphaGeometry 语法支持"""


from geometry_parser import GeometryParser  # type: ignore

AG_PREDICATES = {
    "coll",
    "para",
    "perp",
    "cong",
    "midp",
    "cyclic",
    "circle",
    "eqangle",
    "eqangle6",
    "eqangle3",
    "eqangle2",
    "eqratio",
    "eqratio6",
    "eqratio3",
    "ncoll",
    "npara",
    "nperp",
    "diff",
    "sameside",
    "rconst",
    "contri",
    "contri2",
    "simtri",
    "simtri2",
    "contri*",
    "simtri*",
}

AG_CONSTRUCTIONS = {
    "angle_bisector",
    "angle_mirror",
    "circle",
    "circumcenter",
    "eq_quadrangle",
    "eq_trapezoid",
    "eq_triangle",
    "eqangle2",
    "eqdia_quadrangle",
    "eqdistance",
    "foot",
    "free",
    "incenter",
    "incenter2",
    "excenter",
    "excenter2",
    "centroid",
    "ninepoints",
    "intersection_cc",
    "intersection_lc",
    "intersection_ll",
    "intersection_lp",
    "intersection_lt",
    "intersection_pp",
    "intersection_tt",
    "iso_triangle",
    "lc_tangent",
    "midpoint",
    "mirror",
    "nsquare",
    "on_aline",
    "on_aline2",
    "on_bline",
    "on_circle",
    "on_line",
    "on_pline",
    "on_tline",
    "orthocenter",
    "parallelogram",
    "pentagon",
    "psquare",
    "quadrangle",
    "r_trapezoid",
    "r_triangle",
    "rectangle",
    "reflect",
    "risos",
    "s_angle",
    "segment",
    "shift",
    "square",
    "isquare",
    "trapezoid",
    "triangle",
    "triangle12",
    "ieq_triangle",
    "bisect",
    "amirror",
    "2l1c",
    "e5128",
    "3peq",
    "tangent",
    "cc_tangent",
    "cc_tangent0",
    "on_dia",
    "on_opline",
    "on_circum",
}

print("=== AlphaGeometry 语法支持检查 ===")

missing_pred = AG_PREDICATES - GeometryParser.SUPPORTED_PREDICATES
extra_pred = GeometryParser.SUPPORTED_PREDICATES - AG_PREDICATES
print("\n--- 谓词支持 ---")
print(f'缺少的谓词: {missing_pred if missing_pred else "无"}')
print(f'额外的谓词: {extra_pred if extra_pred else "无"}')
print(f"支持率: {len(AG_PREDICATES - missing_pred)}/{len(AG_PREDICATES)}")

missing_const = AG_CONSTRUCTIONS - GeometryParser.SUPPORTED_CONSTRUCTIONS
extra_const = GeometryParser.SUPPORTED_CONSTRUCTIONS - AG_CONSTRUCTIONS
print("\n--- 构造支持 ---")
print(f'缺少的构造: {missing_const if missing_const else "无"}')
print(f'额外的构造: {extra_const if extra_const else "无"}')
print(f"支持率: {len(AG_CONSTRUCTIONS - missing_const)}/{len(AG_CONSTRUCTIONS)}")

print("\n--- 总结 ---")
total = len(AG_PREDICATES) + len(AG_CONSTRUCTIONS)
supported = len(AG_PREDICATES - missing_pred) + len(AG_CONSTRUCTIONS - missing_const)
print(f"总体支持率: {supported}/{total} = {supported/total*100:.1f}%")
