# GENERATED BY AI
"""检查平行四边形对边相等的证明"""

from data_generator import TrainingDataGenerator, DeductionRules

gen = TrainingDataGenerator()

print("检查规则中涉及 cong 的规则:")
for rule in DeductionRules.RULES:
    conc = rule["conclusion"]
    if "cong" in conc:
        print(f"  {rule['name']}: {rule['premises']} => {conc}")

print()
print("parallelogram 定义:")
print(gen.definitions["parallelogram"])

print()
print("AlphaGeometry 中 parallelogram 的定义:")
print("  a b c = ncoll a b c")
print("  x : para a b c x, para a x b c; cong a b c x, cong a x b c")
print()
print("问题：我们的 parallelogram 定义缺少 cong 条件！")
print("AlphaGeometry 定义中包含：cong a b c x, cong a x b c")
