# GENERATED BY AI
"""几何题推理AI的配置。

模型大小经过调整，以保持总参数量在0.01M以下。
"""

from dataclasses import dataclass, field


@dataclass
class ModelConfig:
    embed_dim: int = 10
    num_heads: int = 1
    ffn_dim: int = 20
    vocab_size: int = 150
    max_seq_len: int = 32
    dropout: float = 0.1


@dataclass
class EncoderConfig(ModelConfig):
    num_layers: int = 1


@dataclass
class DecoderConfig(ModelConfig):
    num_layers: int = 1


@dataclass
class ReasoningAIConfig(ModelConfig):
    num_layers: int = 1
    control_dim: int = 2


@dataclass
class TrainingConfig:
    batch_size: int = 16
    learning_rate: float = 1e-4
    num_epochs: int = 100
    warmup_steps: int = 100
    max_grad_norm: float = 1.0


@dataclass
class EventConfig:
    event_dim: int = 10
    max_events: int = 32


@dataclass
class SystemConfig:
    encoder: EncoderConfig = field(default_factory=EncoderConfig)
    decoder: DecoderConfig = field(default_factory=DecoderConfig)
    reasoning_ai: ReasoningAIConfig = field(default_factory=ReasoningAIConfig)
    training: TrainingConfig = field(default_factory=TrainingConfig)
    event: EventConfig = field(default_factory=EventConfig)


def get_default_config() -> SystemConfig:
    return SystemConfig()
