# GENERATED BY AI
"""
训练数据生成器 - 基于AlphaGeometry风格的几何证明数据生成

生成完整的证明逻辑链条，用于训练几何推理AI。
不包含辅助线功能，专注于从条件到结论的推理步骤。
"""

import json
import os
import random
from dataclasses import dataclass, field
from typing import List, Tuple, Dict, Optional

try:
    from .geometry_definitions import (
        GeometryConstructions,
        GeometryPredicates,
        GeometryRules,
    )
except ImportError:
    from geometry_definitions import (
        GeometryConstructions,
        GeometryPredicates,
        GeometryRules,
    )


@dataclass
class ProofStep:
    """证明步骤"""

    premises: List[str]
    conclusion: str
    rule_name: str
    level: int

    def to_dict(self) -> Dict:
        return {
            "premises": self.premises,
            "conclusion": self.conclusion,
            "rule_name": self.rule_name,
            "level": self.level,
        }


@dataclass
class ProofData:
    """完整的证明数据"""

    problem_name: str
    problem_statement: str
    constructions: List[str]
    goal: str
    proof_steps: List[ProofStep]
    is_solved: bool
    setup_predicates: List[str] = field(default_factory=list)

    def to_training_format(self) -> Dict:
        """转换为训练格式"""
        return {
            "problem_name": self.problem_name,
            "problem_statement": self.problem_statement,
            "constructions": self.constructions,
            "goal": self.goal,
            "setup_predicates": self.setup_predicates,
            "proof_steps": [step.to_dict() for step in self.proof_steps],
            "is_solved": self.is_solved,
            "step_sequence": self._get_step_sequence(),
        }

    def _get_step_sequence(self) -> List[str]:
        """获取推理步骤序列"""
        sequence = []
        for step in self.proof_steps:
            for prem in step.premises:
                sequence.append(prem)
            sequence.append(f"=> {step.conclusion}")
        return sequence


def _get_definitions_dict() -> Dict:
    """获取构造定义字典（兼容旧代码格式）"""
    result = {}
    for name, defn in GeometryConstructions.CONSTRUCTIONS.items():
        result[name] = {
            "args": defn.args,
            "predicates": defn.predicates,
            "description": defn.description,
        }
    return result


def _get_predicate_templates() -> Dict:
    """获取谓词模板（兼容旧代码格式）"""
    templates = {}
    for name, pred in GeometryPredicates.PREDICATES.items():
        if pred.arity > 0:
            args_str = " ".join([f"{{{i}}}" for i in range(pred.arity)])
            templates[name] = {
                "args": pred.arity,
                "template": f"{name} {args_str}",
            }
    return templates


def _get_rules_list() -> List[Dict]:
    """获取规则列表"""
    return GeometryRules.get_rules_dict_list()


class SimpleProofState:
    """简化的证明状态 - 存储已知的命题"""

    def __init__(self):
        self.predicates: set = set()
        self.predicate_list: List[str] = []
        self.predicate_sources: Dict[tuple, Tuple[str, int]] = {}

    def add(self, predicate: str, source: str = "given", level: int = 0) -> bool:
        normalized = self._normalize(predicate)
        if normalized not in self.predicates:
            self.predicates.add(normalized)
            self.predicate_list.append(predicate)
            self.predicate_sources[normalized] = (source, level)
            return True
        return False

    def contains(self, predicate: str) -> bool:
        return self._normalize(predicate) in self.predicates

    def _normalize(self, predicate: str) -> tuple:
        parts = predicate.strip().split()
        if not parts:
            return ()
        name = parts[0]
        args = sorted(parts[1:]) if name in ["coll", "cyclic", "ncoll"] else parts[1:]
        return (name, tuple(args))

    def get_all(self) -> List[str]:
        return list(self.predicate_list)

    def clear(self):
        self.predicates.clear()
        self.predicate_list.clear()
        self.predicate_sources.clear()


class SimpleDeductiveEngine:
    """简化的演绎推理引擎"""

    def __init__(self):
        self.state = SimpleProofState()
        self.rules = _get_rules_list()
        self.max_iterations = 100

    def reset(self):
        self.state.clear()

    def add_premise(self, predicate: str) -> None:
        self.state.add(predicate, "given", 0)

    def deduce(
        self, max_steps: int = 50, goal: Optional[str] = None
    ) -> List[ProofStep]:
        """执行演绎推理，返回所有推导出的步骤

        Args:
            max_steps: 最大迭代次数
            goal: 目标命题，如果找到则提前停止
        """
        steps: List[ProofStep] = []
        iteration = 0
        prev_count = 0

        # 如果目标已经在初始条件中，直接返回
        if goal and self.state.contains(goal):
            return steps

        while iteration < max_steps:
            new_predicates = []

            for rule in self.rules:
                matches = self._match_rule(rule)
                for match in matches:
                    conclusion = self._apply_rule(rule, match)
                    if conclusion and not self.state.contains(conclusion):
                        new_predicates.append((conclusion, rule["name"], iteration + 1))

                        premises = self._get_matched_premises(rule, match)
                        step = ProofStep(
                            premises=premises,
                            conclusion=conclusion,
                            rule_name=rule["name"],
                            level=iteration + 1,
                        )
                        steps.append(step)

                        # 如果找到了目标，提前停止
                        if goal and self._normalize(conclusion) == self._normalize(
                            goal
                        ):
                            for pred, rule_name, level in new_predicates:
                                self.state.add(pred, rule_name, level)
                            return steps

            for pred, rule_name, level in new_predicates:
                self.state.add(pred, rule_name, level)

            if len(self.state.predicates) == prev_count:
                break
            prev_count = len(self.state.predicates)
            iteration += 1

        return steps

    def _normalize(self, predicate: str) -> tuple:
        """规范化谓词"""
        parts = predicate.strip().split()
        if not parts:
            return ()
        name = parts[0]
        args = sorted(parts[1:]) if name in ["coll", "cyclic", "ncoll"] else parts[1:]
        return (name, tuple(args))

    def _match_rule(self, rule: Dict) -> List[Dict[str, str]]:
        """匹配规则的前提条件"""
        matches: List[Dict[str, str]] = []
        self._recursive_match(rule["premises"], {}, matches)
        return matches[:100]

    def _recursive_match(
        self, premises: List[str], current_mapping: Dict, matches: List
    ):
        """递归匹配前提条件"""
        if not premises:
            if current_mapping:
                matches.append(current_mapping.copy())
            return

        premise = premises[0]
        remaining = premises[1:]

        for predicate in self.state.get_all():
            mapping = self._try_match_predicate(premise, predicate, current_mapping)
            if mapping is not None:
                self._recursive_match(remaining, mapping, matches)

    def _try_match_predicate(
        self, template: str, actual: str, current_mapping: Dict
    ) -> Optional[Dict]:
        """尝试匹配单个谓词"""
        template_parts = template.split()
        actual_parts = actual.split()

        if len(template_parts) != len(actual_parts):
            return None

        if template_parts[0] != actual_parts[0]:
            return None

        new_mapping = current_mapping.copy()
        for t_arg, a_arg in zip(template_parts[1:], actual_parts[1:]):
            if t_arg in new_mapping:
                if new_mapping[t_arg] != a_arg:
                    return None
            else:
                new_mapping[t_arg] = a_arg

        return new_mapping

    def _apply_rule(self, rule: Dict, mapping: Dict[str, str]) -> Optional[str]:
        """应用规则生成结论"""
        conclusion = rule["conclusion"]
        parts = conclusion.split()

        result_parts = [parts[0]]
        for arg in parts[1:]:
            if arg in mapping:
                result_parts.append(mapping[arg])
            else:
                return None

        return " ".join(result_parts)

    def _get_matched_premises(self, rule: Dict, mapping: Dict[str, str]) -> List[str]:
        """获取匹配的前提条件"""
        premises = []
        for premise in rule["premises"]:
            parts = premise.split()
            result = [parts[0]]
            for arg in parts[1:]:
                result.append(mapping.get(arg, arg))
            premises.append(" ".join(result))
        return premises


class ProblemGenerator:
    """几何问题生成器"""

    def __init__(self):
        self.definitions = _get_definitions_dict()
        self.point_names = list("abcdefghijklmnopqrstuvwxyz")

    def generate_random_problem(
        self, _complexity: int = 2
    ) -> Tuple[str, str, List[str]]:
        """生成随机几何问题

        Args:
            _complexity: 问题复杂度 (1-3) (未使用)

        Returns:
            (问题陈述, 目标, 构造列表)
        """
        problem_type = random.choice(
            [
                "triangle_basic",
                "midpoint",
                "perpendicular",
                "parallel",
                "circle",
                "orthocenter",
                "centroid",
            ]
        )

        if problem_type == "triangle_basic":
            return self._gen_triangle_basic()
        if problem_type == "midpoint":
            return self._gen_midpoint_problem()
        if problem_type == "perpendicular":
            return self._gen_perp_problem()
        if problem_type == "parallel":
            return self._gen_para_problem()
        if problem_type == "circle":
            return self._gen_circle_problem()
        if problem_type == "orthocenter":
            return self._gen_orthocenter_problem()
        if problem_type == "centroid":
            return self._gen_centroid_problem()
        return self._gen_triangle_basic()

    def _gen_triangle_basic(self) -> Tuple[str, str, List[str]]:
        """生成基本三角形问题"""
        a, b, c = random.sample(self.point_names, 3)
        problem = f"{a} {b} {c} = triangle"
        goal_type = random.choice(["coll", "ncoll"])
        goal = f"{goal_type} {a} {b} {c}"
        return problem, goal, [f"{a} {b} {c} = triangle"]

    def _gen_midpoint_problem(self) -> Tuple[str, str, List[str]]:
        """生成中点相关问题"""
        a, b, c, d = random.sample(self.point_names, 4)
        problem = f"{a} {b} {c} = triangle; {d} = midpoint {d} {a} {b}"
        goal = f"coll {d} {a} {b}"
        return problem, goal, [f"{a} {b} {c} = triangle", f"{d} = midpoint {d} {a} {b}"]

    def _gen_perp_problem(self) -> Tuple[str, str, List[str]]:
        """生成垂直相关问题"""
        a, b, c, d, _e = random.sample(self.point_names, 5)
        problem = f"{a} {b} {c} = triangle; {d} = foot {d} {a} {b} {c}"
        goal = f"perp {d} {a} {b} {c}"
        return problem, goal, [f"{a} {b} {c} = triangle", f"{d} = foot {d} {a} {b} {c}"]

    def _gen_para_problem(self) -> Tuple[str, str, List[str]]:
        """生成平行相关问题"""
        a, b, c, d, e, _f = random.sample(self.point_names, 6)
        problem = f"{a} {b} {c} = triangle; {d} = on_pline {d} {a} {b} {c}; {e} = on_pline {e} {b} {a} {c}"
        goal = f"para {a} {d} {b} {e}"
        return (
            problem,
            goal,
            [
                f"{a} {b} {c} = triangle",
                f"{d} = on_pline {d} {a} {b} {c}",
                f"{e} = on_pline {e} {b} {a} {c}",
            ],
        )

    def _gen_circle_problem(self) -> Tuple[str, str, List[str]]:
        """生成圆相关问题"""
        a, b, c, d, o = random.sample(self.point_names, 5)
        problem = f"{a} {b} {c} = triangle; {o} = circumcenter {o} {a} {b} {c}; {d} = on_circle {d} {o} {a}"
        goal = f"cong {o} {d} {o} {a}"
        return (
            problem,
            goal,
            [
                f"{a} {b} {c} = triangle",
                f"{o} = circumcenter {o} {a} {b} {c}",
                f"{d} = on_circle {d} {o} {a}",
            ],
        )

    def _gen_orthocenter_problem(self) -> Tuple[str, str, List[str]]:
        """生成垂心相关问题"""
        a, b, c, h = random.sample(self.point_names, 4)
        problem = f"{a} {b} {c} = triangle; {h} = orthocenter {h} {a} {b} {c}"
        goal = f"perp {h} {a} {b} {c}"
        return (
            problem,
            goal,
            [f"{a} {b} {c} = triangle", f"{h} = orthocenter {h} {a} {b} {c}"],
        )

    def _gen_centroid_problem(self) -> Tuple[str, str, List[str]]:
        """生成重心相关问题"""
        a, b, c, g, m = random.sample(self.point_names, 5)
        problem = f"{a} {b} {c} = triangle; {m} = midpoint {m} {a} {b}; {g} = on_line {g} {c} {m}"
        goal = f"coll {g} {c} {m}"
        return (
            problem,
            goal,
            [
                f"{a} {b} {c} = triangle",
                f"{m} = midpoint {m} {a} {b}",
                f"{g} = on_line {g} {c} {m}",
            ],
        )


class TrainingDataGenerator:
    """训练数据生成器主类"""

    def __init__(self, cache_file: Optional[str] = None):
        self.engine = SimpleDeductiveEngine()
        self.problem_gen = ProblemGenerator()
        self.definitions = _get_definitions_dict()
        self._cache: Dict[str, ProofData] = {}
        self._cache_file = cache_file
        if cache_file:
            self._load_cache()

    def _load_cache(self):
        """加载缓存文件"""
        if self._cache_file and os.path.exists(self._cache_file):
            try:
                with open(self._cache_file, "r", encoding="utf-8") as f:
                    data = json.load(f)
                for key, value in data.items():
                    steps = [ProofStep(**s) for s in value.get("proof_steps", [])]
                    self._cache[key] = ProofData(
                        problem_name=value["problem_name"],
                        problem_statement=value["problem_statement"],
                        constructions=value["constructions"],
                        goal=value["goal"],
                        proof_steps=steps,
                        is_solved=value["is_solved"],
                        setup_predicates=value.get("setup_predicates", []),
                    )
                print(f"已加载 {len(self._cache)} 条缓存")
            except Exception as e:
                print(f"加载缓存失败: {e}")

    def _save_cache(self):
        """保存缓存文件"""
        if self._cache_file:
            try:
                data = {}
                for key, proof in self._cache.items():
                    data[key] = {
                        "problem_name": proof.problem_name,
                        "problem_statement": proof.problem_statement,
                        "constructions": proof.constructions,
                        "goal": proof.goal,
                        "proof_steps": [s.to_dict() for s in proof.proof_steps],
                        "is_solved": proof.is_solved,
                        "setup_predicates": proof.setup_predicates,
                    }
                with open(self._cache_file, "w", encoding="utf-8") as f:
                    json.dump(data, f, ensure_ascii=False, indent=2)
            except Exception as e:
                print(f"保存缓存失败: {e}")

    def _get_cache_key(self, problem_str: str) -> str:
        """生成缓存键"""
        return problem_str.strip()

    def clear_cache(self):
        """清空缓存"""
        self._cache.clear()
        if self._cache_file:
            if os.path.exists(self._cache_file):
                os.remove(self._cache_file)

    def parse_problem(self, problem_str: str) -> Tuple[List[str], str, List[str]]:
        """解析问题字符串

        Args:
            problem_str: 问题字符串，格式如 "a b c = triangle; d = midpoint d a b ? coll d a b"

        Returns:
            (构造列表, 目标, 初始谓词列表)
        """
        if " ? " in problem_str:
            setup, goal = problem_str.split(" ? ")
        else:
            setup = problem_str
            goal = ""

        constructions = [c.strip() for c in setup.split(";") if c.strip()]
        initial_predicates = []

        for const in constructions:
            predicates = self._expand_construction(const)
            initial_predicates.extend(predicates)

        return constructions, goal.strip(), initial_predicates

    def _expand_construction(self, construction: str) -> List[str]:
        """展开构造为谓词列表"""
        if " = " not in construction:
            return []

        _points_part, const_part = construction.split(" = ", 1)
        const_parts = const_part.strip().split()
        const_name = const_parts[0] if const_parts else ""
        const_args = const_parts[1:] if len(const_parts) > 1 else []

        if const_name not in self.definitions:
            return []

        definition = self.definitions[const_name]
        predicates = []

        arg_names = definition.get("args", [])

        var_mapping = {}
        for i, arg_name in enumerate(arg_names):
            if i < len(const_args):
                var_mapping[arg_name] = const_args[i]

        for pred_template in definition.get("predicates", []):
            pred = self._instantiate_predicate(pred_template, var_mapping)
            if pred:
                predicates.append(pred)

        return predicates

    def _instantiate_predicate(
        self, template: str, var_mapping: Dict[str, str]
    ) -> Optional[str]:
        """实例化谓词模板"""
        parts = template.split()

        result = [parts[0]]
        for arg in parts[1:]:
            if arg.startswith("(") and arg.endswith(")"):
                inner = arg[1:-1]
                if " " in inner:
                    sub_parts = inner.split()
                    if sub_parts[0] == "midpoint" and len(sub_parts) == 3:
                        p1 = var_mapping.get(sub_parts[1], sub_parts[1])
                        p2 = var_mapping.get(sub_parts[2], sub_parts[2])
                        m = self._find_or_create_midpoint(
                            p1, p2, list(var_mapping.values())
                        )
                        result.append(m)
                continue
            if arg in var_mapping:
                result.append(var_mapping[arg])
            elif len(arg) == 1 and arg.isalpha():
                result.append(arg)
            else:
                return None

        return " ".join(result)

    def _find_or_create_midpoint(self, p1: str, p2: str, available: List[str]) -> str:
        """查找或创建中点"""
        for p in available:
            if p not in [p1, p2]:
                return p
        return "m"

    def generate_proof_data(
        self, problem_str: str, problem_name: str = ""
    ) -> ProofData:
        """生成单个问题的证明数据

        Args:
            problem_str: 问题字符串
            problem_name: 问题名称

        Returns:
            ProofData对象
        """
        cache_key = self._get_cache_key(problem_str)
        if cache_key in self._cache:
            return self._cache[cache_key]

        self.engine.reset()

        constructions, goal, initial_predicates = self.parse_problem(problem_str)

        for pred in initial_predicates:
            self.engine.add_premise(pred)

        proof_steps = self.engine.deduce(max_steps=50, goal=goal)

        is_solved = False
        if goal:
            is_solved = self.engine.state.contains(goal)

        result = ProofData(
            problem_name=problem_name or "unnamed",
            problem_statement=problem_str,
            constructions=constructions,
            goal=goal,
            proof_steps=proof_steps,
            is_solved=is_solved,
            setup_predicates=initial_predicates,
        )

        self._cache[cache_key] = result
        if self._cache_file:
            self._save_cache()

        return result

    def generate_batch(
        self, num_problems: int = 100, include_random: bool = True
    ) -> List[ProofData]:
        """批量生成训练数据

        Args:
            num_problems: 生成的问题数量
            include_random: 是否包含随机生成的问题

        Returns:
            ProofData列表
        """
        results: List[ProofData] = []

        example_problems = self._get_example_problems()

        for _i, (problem, name) in enumerate(example_problems):
            if len(results) >= num_problems:
                break
            try:
                proof_data = self.generate_proof_data(problem, name)
                results.append(proof_data)
            except Exception as e:
                print(f"处理问题 {name} 时出错: {e}")

        if include_random:
            while len(results) < num_problems:
                try:
                    problem, goal, constructions = (
                        self.problem_gen.generate_random_problem()
                    )
                    problem_str = "; ".join(constructions) + f" ? {goal}"
                    proof_data = self.generate_proof_data(
                        problem_str, f"random_{len(results)}"
                    )
                    results.append(proof_data)
                except Exception as e:
                    print(f"生成随机问题时出错: {e}")

        return results

    def _get_example_problems(self) -> List[Tuple[str, str]]:
        """获取示例问题列表 - 所有问题都有可推导的目标"""
        return [
            ("a b c = triangle; m = midpoint m a b ? coll m a b", "midpoint_coll"),
            ("a b c = triangle; m = midpoint m a b ? cong m a m b", "midpoint_cong"),
            (
                "a b c = triangle; h = orthocenter h a b c ? perp h a b c",
                "orthocenter_perp1",
            ),
            (
                "a b c = triangle; h = orthocenter h a b c ? perp h b c a",
                "orthocenter_perp2",
            ),
            (
                "a b c = triangle; o = circumcenter o a b c ? cong o a o b",
                "circumcenter_cong1",
            ),
            (
                "a b c = triangle; o = circumcenter o a b c ? cong o b o c",
                "circumcenter_cong2",
            ),
            ("a b c = triangle; d = foot d a b c ? perp d a b c", "foot_perp"),
            ("a b c = triangle; d = foot d a b c ? coll d b c", "foot_coll"),
            (
                "a b c = triangle; m = midpoint m a b; n = midpoint n a c ? para m n b c",
                "midpoint_para",
            ),
            ("a b c d = parallelogram a b c d ? para a b c d", "para_para1"),
            ("a b c d = parallelogram a b c d ? para a d b c", "para_para2"),
            ("a b c d = rectangle a b c d ? perp a b b c", "rect_perp"),
            ("a b = segment a b; c = on_line c a b ? coll c a b", "online_coll"),
            ("a b c = triangle; d = on_tline d a b c ? perp d a b c", "ontline_perp"),
            ("a b c = triangle; d = on_pline d a b c ? para d a b c", "online_para"),
            (
                "a b c = triangle; m = midpoint m a b; n = midpoint n b c ? cong m a m b",
                "midpoint_chain",
            ),
            (
                "a b c = triangle; o = circumcenter o a b c; d = on_circle d o a ? cong o d o a",
                "circle_cong",
            ),
            (
                "a b c = triangle; m = midpoint m a b; n = midpoint n a c; p = midpoint p b c ? coll m n p",
                "midpoint_coll3",
            ),
            (
                "a b c = triangle; h = orthocenter h a b c; o = circumcenter o a b c ? cong o a o b",
                "ortho_circum",
            ),
            (
                "a b c = triangle; i = incenter i a b c ? eqangle a b a i a i a c",
                "incenter_angle",
            ),
        ]

    def export_to_file(
        self, data: List[ProofData], filepath: str, output_format: str = "json"
    ):
        """导出训练数据到文件

        Args:
            data: ProofData列表
            filepath: 输出文件路径
            output_format: 输出格式 (json, txt)
        """
        if output_format == "json":
            with open(filepath, "w", encoding="utf-8") as f:
                json.dump(
                    [d.to_training_format() for d in data],
                    f,
                    ensure_ascii=False,
                    indent=2,
                )
        elif output_format == "txt":
            with open(filepath, "w", encoding="utf-8") as f:
                for d in data:
                    f.write(f"=== {d.problem_name} ===\n")
                    f.write(f"问题: {d.problem_statement}\n")
                    f.write(f"目标: {d.goal}\n")
                    f.write(f"初始条件: {d.setup_predicates}\n")
                    f.write("证明步骤:\n")
                    for i, step in enumerate(d.proof_steps):
                        f.write(
                            f"  {i+1}. {step.premises} => {step.conclusion} ({step.rule_name})\n"
                        )
                    f.write(f"是否解决: {d.is_solved}\n\n")

    def get_training_sequences(
        self, data: List[ProofData]
    ) -> List[Tuple[str, List[str], str]]:
        """获取训练序列

        Args:
            data: ProofData列表

        Returns:
            (初始命题, 推理步骤序列, 目标) 的列表
        """
        sequences = []
        for d in data:
            if d.proof_steps:
                step_sequence = []
                for step in d.proof_steps:
                    step_sequence.extend(step.premises)
                    step_sequence.append(step.conclusion)

                sequences.append((" ".join(d.setup_predicates), step_sequence, d.goal))
        return sequences
