# GENERATED BY AI
"""测试简单的符号推理"""

from symbolic_engine import SymbolicEngine, ProofState
from geometry_parser import GeometryParser

engine = SymbolicEngine()

# 测试规则 6: midp E A B, midp F A C => para E F B C
state = ProofState()
prop1 = GeometryParser.parse_proposition('midp E A B')
prop2 = GeometryParser.parse_proposition('midp F A C')
state.add(prop1)
state.add(prop2)

print('测试规则 6: midp E A B, midp F A C => para E F B C')
print('状态中的命题:')
for p in state.get_all():
    print(f'  {p}')

print('\n尝试演绎...')
new_props = engine.deduce(state, max_steps=10)

print(f'\n推导出的命题数: {len(new_props)}')
for p in new_props:
    print(f'  {p}')

# 检查目标
target = GeometryParser.parse_proposition('para E F B C')
print(f'\n目标 {target} 在状态中: {state.contains(target)}')
