# GENERATED BY AI
"""测试符号推理并输出详细调试信息"""

from symbolic_engine import SymbolicEngine, ProofState
from geometry_parser import GeometryParser

engine = SymbolicEngine()

# 测试规则 6: midp E A B, midp F A C => para E F B C
state = ProofState()
prop1 = GeometryParser.parse_proposition('midp E A B')
prop2 = GeometryParser.parse_proposition('midp F A C')
state.add(prop1)
state.add(prop2)

print('测试规则 6: midp E A B, midp F A C => para E F B C')
print('状态中的命题:')
for p in state.get_all():
    print(f'  {p}')

# 手动测试规则匹配
print('\n\n手动测试规则匹配:')
rule = engine.rules[6]  # 规则 6: midp E A B, midp F A C => para E F B C
print(f'规则: {rule}')
print(f'前提: {rule.premises}')
print(f'结论: {rule.conclusions}')

# 测试第一个前提的匹配
first_premise = rule.premises[0]
print(f'\n第一个前提: {first_premise}')
print('尝试与状态中的命题匹配:')
for prop in state.get_all():
    bindings = engine.match_proposition(first_premise, prop, {})
    print(f'  {prop} -> {bindings}')

# 测试第二个前提的匹配
second_premise = rule.premises[1]
print(f'\n第二个前提: {second_premise}')
print('尝试与状态中的命题匹配:')
for prop in state.get_all():
    bindings = engine.match_proposition(second_premise, prop, {})
    print(f'  {prop} -> {bindings}')

# 尝试应用规则
derived = engine.apply_rule(rule, state)
print(f'\n应用规则后推导出 {len(derived)} 个命题:')
for p in derived:
    print(f'  {p}')
