# GENERATED BY AI
"""测试 _find_bindings 方法"""

from symbolic_engine import SymbolicEngine, ProofState
from geometry_parser import GeometryParser

engine = SymbolicEngine()

# 测试规则 6: midp E A B, midp F A C => para E F B C
state = ProofState()
prop1 = GeometryParser.parse_proposition("midp E A B")
prop2 = GeometryParser.parse_proposition("midp F A C")
state.add(prop1)
state.add(prop2)

rule = engine.rules[6]  # 规则 6: midp E A B, midp F A C => para E F B C
print(f"规则: {rule}")
print(f"前提: {rule.premises}")
print(f"结论: {rule.conclusions}")

print("\n状态中的命题:")
for p in state.get_all():
    print(f"  {p}")

print("\n调用 _find_all_matches:")
bindings_list = engine._find_all_matches(rule.premises, list(state.get_all()))
print(f"找到 {len(bindings_list)} 个绑定:")
for i, bindings in enumerate(bindings_list):
    print(f"  {i+1}. {bindings}")
