# GENERATED BY AI
"""调试符号引擎"""

from symbolic_engine import SymbolicEngine, ProofState
from geometry_parser import GeometryParser

engine = SymbolicEngine()
state = ProofState()

prop1 = GeometryParser.parse_proposition('perp A B C D')
prop2 = GeometryParser.parse_proposition('perp E F C D')

state.add(prop1)
state.add(prop2)

print('状态中的命题:')
for p in state.get_all():
    print(f'  {p}')

print('\n尝试演绎...')
new_props = engine.deduce(state, max_steps=10)

print(f'\n推导出的命题数: {len(new_props)}')
for p in new_props:
    print(f'  {p}')
