# GENERATED BY GLM
"""几何题推理AI的事件系统。"""

import torch
from torch import nn
from typing import Optional, List
from dataclasses import dataclass


@dataclass
class Event:
    event_vector: torch.Tensor
    is_success: Optional[bool] = None

    def __post_init__(self):
        if self.event_vector.dim() == 1:
            self.event_vector = self.event_vector.unsqueeze(0)


class PositionalEncoding(nn.Module):
    pe: torch.Tensor

    def __init__(self, embed_dim: int, max_len: int = 128, dropout: float = 0.1):
        super().__init__()
        self.dropout = nn.Dropout(p=dropout)

        pe = torch.zeros(max_len, embed_dim)
        position = torch.arange(0, max_len, dtype=torch.float).unsqueeze(1)
        div_term = torch.exp(
            torch.arange(0, embed_dim, 2).float()
            * (-torch.log(torch.tensor(10000.0)) / embed_dim)
        )
        pe[:, 0::2] = torch.sin(position * div_term)
        pe[:, 1::2] = torch.cos(position * div_term)
        pe = pe.unsqueeze(0)
        self.register_buffer("pe", pe)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        x = x + self.pe[:, : x.size(1)]
        return self.dropout(x)


class EventSequence:
    def __init__(self, event_dim: int, max_events: int = 128):
        self.event_dim = event_dim
        self.max_events = max_events
        self.events: List[Event] = []
        self.positional_encoding = PositionalEncoding(event_dim, max_events)

    def add_event(self, event: Event) -> bool:
        if len(self.events) >= self.max_events:
            return False
        self.events.append(event)
        return True

    def get_sequence_tensor(self) -> torch.Tensor:
        if not self.events:
            return torch.zeros(1, 1, self.event_dim)
        vectors = [e.event_vector for e in self.events]
        sequence = torch.cat(vectors, dim=0)
        if sequence.dim() == 2:
            sequence = sequence.unsqueeze(0)
        return sequence

    def get_position_encoded(self) -> torch.Tensor:
        sequence = self.get_sequence_tensor()
        return self.positional_encoding(sequence)

    def get_success_flags(self) -> List[Optional[bool]]:
        return [e.is_success for e in self.events]

    def clear(self):
        self.events = []

    def __len__(self) -> int:
        return len(self.events)

    def __getitem__(self, idx: int) -> Event:
        return self.events[idx]

    def last_event(self) -> Optional[Event]:
        return self.events[-1] if self.events else None
