# GENERATED BY AI
"""几何题推理AI的事件系统。

定义事件和事件序列的数据结构，用于推理过程中的状态管理。
"""

from dataclasses import dataclass
from typing import List, Optional

import torch


@dataclass
class Event:
    """事件数据结构，包含事件向量和验证状态"""

    event_vector: torch.Tensor
    is_success: Optional[bool] = None

    def __post_init__(self):
        if self.event_vector.dim() == 1:
            self.event_vector = self.event_vector.unsqueeze(0)


class EventSequence:
    """事件序列管理器，管理推理过程中的事件链"""

    def __init__(self, event_dim: int, max_events: int = 128):
        self.event_dim = event_dim
        self.max_events = max_events
        self.events: List[Event] = []

    def add_event(self, event: Event) -> bool:
        if len(self.events) >= self.max_events:
            return False
        self.events.append(event)
        return True

    def get_sequence_tensor(self) -> torch.Tensor:
        if not self.events:
            return torch.zeros(1, 1, self.event_dim)
        vectors = [e.event_vector for e in self.events]
        sequence = torch.cat(vectors, dim=0)
        if sequence.dim() == 2:
            sequence = sequence.unsqueeze(0)
        return sequence

    def get_success_flags(self) -> List[Optional[bool]]:
        return [e.is_success for e in self.events]

    def clear(self):
        self.events = []

    def __len__(self) -> int:
        return len(self.events)

    def __getitem__(self, idx: int) -> Event:
        return self.events[idx]

    def last_event(self) -> Optional[Event]:
        return self.events[-1] if self.events else None
