# GENERATED BY GLM
"""几何题推理AI使用示例。"""

import sys
import os

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from geometry_reasoning_ai.workflow import GeometryReasoningSystem
from geometry_reasoning_ai.training import TrainingPipeline
from geometry_reasoning_ai.render_engine import RenderEngine
from geometry_reasoning_ai.symbolic_engine import SymbolicEngine
from geometry_reasoning_ai.symbolic_engine import ProofState as SEProofState
from geometry_reasoning_ai.geometry_parser import GeometryParser


def example_basic_usage():
    print("\n" + "=" * 50)
    print("示例1: 基础系统使用")
    print("=" * 50)

    system = GeometryReasoningSystem()

    params = system.count_parameters()
    print("\n模型参数:")
    print(f"  编码器: {params['encoder']:,}")
    print(f"  解码器: {params['decoder']:,}")
    print(f"  推理AI: {params['reasoning_ai']:,}")
    print(f"  总计: {params['total']:,}")
    print(f"  小于0.05M: {params['total'] < 50000}")

    proposition = "perp A B C D"
    print(f"\n编码命题: '{proposition}'")

    event_vector = system.encode_proposition(proposition)
    print(f"事件向量形状: {event_vector.shape}")

    decoded = system.decode_event(event_vector)
    print(f"解码语句: '{decoded}'")


def example_render_engine():
    print("\n" + "=" * 50)
    print("示例2: 渲染引擎验证")
    print("=" * 50)

    engine = RenderEngine()

    engine.add_point("A", 0, 0)
    engine.add_point("B", 2, 0)
    engine.add_point("C", 1, 1.732)
    engine.add_point("D", 1, 0)
    engine.add_point("M", 1, 0)

    propositions = [
        ("coll A B D", "点A、B、D共线"),
        ("midp M A B", "M是AB的中点"),
        ("coll A B C", "点A、B、C共线"),
    ]

    print("\n验证命题:")
    for prop_str, desc in propositions:
        prop = GeometryParser.parse_proposition(prop_str)
        result = engine.verify_proposition(prop)
        status = "✓" if result else "✗"
        print(f"  {status} {desc}: {prop_str}")


def example_symbolic_engine():
    print("\n" + "=" * 50)
    print("示例3: 符号引擎演绎")
    print("=" * 50)

    engine = SymbolicEngine()

    print("\n添加前提:")
    state = SEProofState()
    prop1 = GeometryParser.parse_proposition("perp A B C D")
    prop2 = GeometryParser.parse_proposition("perp E F C D")
    state.add(prop1)
    state.add(prop2)
    print(f"  - {prop1}")
    print(f"  - {prop2}")

    print("\n运行演绎...")
    new_props = engine.deduce(state, max_steps=10)
    print(f"  推导出 {len(new_props)} 条新命题")

    print("\n检查结论:")
    target = GeometryParser.parse_proposition("para A B E F")
    result = state.contains(target)
    print(f"  {target}: {'✓ 有效' if result else '✗ 无效'}")

    print("\n所有推导语句:")
    for prop in state.get_all():
        print(f"  - {prop}")


def example_training():
    print("\n" + "=" * 50)
    print("示例4: 训练流程")
    print("=" * 50)

    system = GeometryReasoningSystem()
    pipeline = TrainingPipeline(system)

    print("\n预训练编码器-解码器 (5轮)...")
    losses = pipeline.pretrain_encoder_decoder(num_epochs=5)
    print(f"  最终损失: {losses[-1]:.4f}")

    supervised_problems = [
        (
            GeometryParser.parse_proposition("perp A B C D"),
            [GeometryParser.parse_proposition("perp A B C D")],
        ),
        (
            str(GeometryParser.parse_proposition("midp M A B")),
            [
                str(GeometryParser.parse_proposition("midp M A B")),
                str(GeometryParser.parse_proposition("cong A M M B")),
            ],
        ),
    ]

    print("\n监督训练 (3轮)...")
    pipeline.supervised_training(supervised_problems, num_epochs=3)

    rl_problems = [
        (
            str(GeometryParser.parse_proposition("perp A B C D")),
            str(GeometryParser.parse_proposition("para A B E F")),
        ),
        (
            str(GeometryParser.parse_proposition("midp M A B")),
            str(GeometryParser.parse_proposition("cong A M M B")),
        ),
    ]

    print("\n强化学习训练 (3轮)...")
    rewards = pipeline.rl_training(rl_problems, num_epochs=3)
    print(f"  最终平均奖励: {rewards[-1]:.4f}")


def example_reasoning():
    print("\n" + "=" * 50)
    print("示例5: 推理流程")
    print("=" * 50)

    system = GeometryReasoningSystem()

    initial_prop = "perp A B C D"
    target = "para"
    print(f"\n初始命题: '{initial_prop}'")
    print(f"目标包含: '{target}'")
    print("\n运行推理...")

    success, steps = system.run_reasoning(initial_prop, target=target, max_steps=10)
    print(f"\n推理完成: {'成功' if success else '达到最大步数'}")
    print(f"总步数: {len(steps)}")

    print("\n步骤详情:")
    for i, step in enumerate(steps[:5]):
        print(f"  步骤 {i+1}:")
        print(f"    控制信号: {step.control_signal[0].tolist()}")
        if step.decoded_statement:
            print(f"    解码: '{step.decoded_statement}'")
            if step.symbolic_valid is not None:
                print(f"    符号有效: {step.symbolic_valid}")


def main():
    print("\n" + "=" * 60)
    print("几何题推理AI - 使用示例")
    print("=" * 60)

    example_basic_usage()
    example_render_engine()
    example_symbolic_engine()
    example_training()
    example_reasoning()

    print("\n" + "=" * 60)
    print("所有示例完成!")
    print("=" * 60)


if __name__ == "__main__":
    main()
