# GENERATED BY GLM
"""几何题推理AI使用示例。"""

import sys
import os

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

if __name__ == "__main__":
    from integrated_workflow import IntegratedGeometrySystem
    from training import TrainingPipeline
    from extended_render_engine import ExtendedRenderEngine, Point
    from extended_symbolic_engine import ExtendedSymbolicEngine
else:
    from .integrated_workflow import IntegratedGeometrySystem
    from .training import TrainingPipeline
    from .extended_render_engine import ExtendedRenderEngine, Point
    from .extended_symbolic_engine import ExtendedSymbolicEngine


def example_basic_usage():
    print("\n" + "=" * 50)
    print("示例1: 基础系统使用")
    print("=" * 50)

    system = GeometryReasoningSystem()

    params = system.count_parameters()
    print("\n模型参数:")
    print(f"  编码器: {params['encoder']:,}")
    print(f"  解码器: {params['decoder']:,}")
    print(f"  推理AI: {params['reasoning_ai']:,}")
    print(f"  总计: {params['total']:,}")
    print(f"  小于0.05M: {params['total'] < 50000}")

    proposition = "perp A B C D"
    print(f"\n编码命题: '{proposition}'")

    event_vector = system.encode_proposition(proposition)
    print(f"事件向量形状: {event_vector.shape}")

    decoded = system.decode_event(event_vector)
    print(f"解码语句: '{decoded}'")


def example_render_engine():
    print("\n" + "=" * 50)
    print("示例2: 渲染引擎验证")
    print("=" * 50)

    engine = RenderEngine()

    engine.points = {
        "A": Point(0, 0),
        "B": Point(2, 0),
        "C": Point(1, 1.732),
        "D": Point(1, 0),
        "M": Point(1, 0),
    }

    propositions = [
        ("coll A B D", "点A、B、D共线"),
        ("midp M A B", "M是AB的中点"),
        ("coll A B C", "点A、B、C共线"),
    ]

    print("\n验证命题:")
    for prop, desc in propositions:
        result, msg = engine.render_and_verify(prop)
        status = "✓" if result else "✗"
        print(f"  {status} {desc}: {msg}")


def example_symbolic_engine():
    print("\n" + "=" * 50)
    print("示例3: 符号引擎演绎")
    print("=" * 50)

    engine = SymbolicEngine()

    print("\n添加前提:")
    engine.add_statement("perp A B C D")
    print("  - perp A B C D")
    engine.add_statement("perp E F C D")
    print("  - perp E F C D")

    print("\n运行演绎...")
    new_statements = engine.deduce()
    print(f"  推导出 {new_statements} 条新语句")

    print("\n检查结论:")
    result = engine.verify("para A B E F")
    print(f"  para A B E F: {'✓ 有效' if result else '✗ 无效'}")

    print("\n所有推导语句:")
    for stmt in engine.get_derived_statements():
        print(f"  - {stmt}")


def example_training():
    print("\n" + "=" * 50)
    print("示例4: 训练流程")
    print("=" * 50)

    system = GeometryReasoningSystem()
    pipeline = TrainingPipeline(system)

    print("\n预训练编码器-解码器 (5轮)...")
    losses = pipeline.pretrain_encoder_decoder(num_epochs=5)
    print(f"  最终损失: {losses[-1]:.4f}")

    supervised_problems = [
        ("perp A B C D", ["perp A B C D"]),
        ("midp M A B", ["midp M A B", "cong A M M B"]),
    ]

    print("\n监督训练 (3轮)...")
    pipeline.supervised_training(supervised_problems, num_epochs=3)

    rl_problems = [
        ("perp A B C D", "para A B E F"),
        ("midp M A B", "cong A M M B"),
    ]

    print("\n强化学习训练 (3轮)...")
    rewards = pipeline.rl_training(rl_problems, num_epochs=3)
    print(f"  最终平均奖励: {rewards[-1]:.4f}")


def example_reasoning():
    print("\n" + "=" * 50)
    print("示例5: 推理流程")
    print("=" * 50)

    system = GeometryReasoningSystem()

    initial_prop = "perp A B C D"
    target = "para"

    print(f"\n初始命题: '{initial_prop}'")
    print(f"目标包含: '{target}'")
    print("\n运行推理...")

    success, steps = system.run_reasoning(initial_prop, target=target, max_steps=10)

    print(f"\n推理完成: {'成功' if success else '达到最大步数'}")
    print(f"总步数: {len(steps)}")

    print("\n步骤详情:")
    for i, step in enumerate(steps[:5]):
        print(f"  步骤 {i+1}:")
        print(f"    控制信号: {step.control_signal[0].tolist()}")
        if step.decoded_statement:
            print(f"    解码: '{step.decoded_statement}'")
            if step.symbolic_valid is not None:
                print(f"    符号有效: {step.symbolic_valid}")


def main():
    print("\n" + "=" * 60)
    print("几何题推理AI - 使用示例")
    print("=" * 60)

    example_basic_usage()
    example_render_engine()
    example_symbolic_engine()
    example_training()
    example_reasoning()

    print("\n" + "=" * 60)
    print("所有示例完成!")
    print("=" * 60)


if __name__ == "__main__":
    main()
