# GENERATED BY AI
"""扩展的符号引擎，支持所有 AlphaGeometry 演绎规则。"""

from typing import List, Set, Dict, Tuple, Optional
from dataclasses import dataclass, field


@dataclass
class Statement:
    """几何命题。"""
    predicate: str
    args: Tuple[str, ...]

    def __str__(self):
        return f"{self.predicate} {' '.join(self.args)}"

    def __hash__(self):
        return hash((self.predicate, self.args))

    def __eq__(self, other):
        if not isinstance(other, Statement):
            return False
        return self.predicate == other.predicate and self.args == other.args


@dataclass
class ProofState:
    """证明状态。"""
    statements: Set[Statement] = field(default_factory=set)
    derived: Set[Statement] = field(default_factory=set)

    def add(self, stmt: Statement, is_derived: bool = False):
        """添加命题。"""
        self.statements.add(stmt)
        if is_derived:
            self.derived.add(stmt)

    def contains(self, stmt: Statement) -> bool:
        """检查是否包含命题。"""
        return stmt in self.statements

    def get_by_predicate(self, predicate: str) -> List[Statement]:
        """按谓词获取命题。"""
        return [s for s in self.statements if s.predicate == predicate]

    def get_by_pattern(self, pattern: Statement) -> List[Tuple[Statement, Dict[str, str]]]:
        """获取匹配模式的命题。"""
        results = []
        for stmt in self.statements:
            if stmt.predicate == pattern.predicate:
                bindings = self._match_args(pattern.args, stmt.args)
                if bindings is not None:
                    results.append((stmt, bindings))
        return results

    def _match_args(
        self, pattern_args: Tuple[str, ...], actual_args: Tuple[str, ...]
    ) -> Optional[Dict[str, str]]:
        """匹配参数。"""
        if len(pattern_args) != len(actual_args):
            return None

        bindings: Dict[str, str] = {}
        for p, a in zip(pattern_args, actual_args):
            if p.isupper():
                if p in bindings and bindings[p] != a:
                    return None
                bindings[p] = a
            elif p != a:
                return None

        return bindings


class DeductionRule:
    """演绎规则。"""

    def __init__(self, name: str, premises: List[str], conclusions: List[str]):
        self.name = name
        self.premises = premises
        self.conclusions = conclusions

    def apply(self, state: ProofState) -> List[Statement]:
        """应用规则。"""
        new_statements = []

        premise_stmts = [self._parse_statement(p) for p in self.premises]
        conclusion_stmts = [self._parse_statement(c) for c in self.conclusions]

        bindings_list = self._find_bindings(state, premise_stmts)

        for bindings in bindings_list:
            for conc in conclusion_stmts:
                bound_args = tuple(bindings.get(arg, arg) for arg in conc.args)
                new_stmt = Statement(conc.predicate, bound_args)
                if not state.contains(new_stmt):
                    new_statements.append(new_stmt)

        return new_statements

    def _parse_statement(self, stmt_str: str) -> Statement:
        """解析语句。"""
        parts = stmt_str.split()
        if not parts:
            return Statement("", ())
        return Statement(parts[0], tuple(parts[1:]))

    def _find_bindings(
        self, state: ProofState, patterns: List[Statement]
    ) -> List[Dict[str, str]]:
        """查找参数绑定。"""
        if not patterns:
            return [{}]

        first_pattern = patterns[0]
        rest_patterns = patterns[1:]

        candidates = state.get_by_pattern(first_pattern)
        bindings_list = []

        for candidate, bindings in candidates:
            rest_bindings = self._find_bindings(state, rest_patterns)
            for rest_binding in rest_bindings:
                combined = {**bindings, **rest_binding}
                if self._is_consistent(combined):
                    bindings_list.append(combined)

        return bindings_list

    def _is_consistent(self, bindings: Dict[str, str]) -> bool:
        """检查绑定是否一致。"""
        values = list(bindings.values())
        return len(values) == len(set(values))


class ExtendedSymbolicEngine:
    """扩展的符号引擎，支持所有 AlphaGeometry 演绎规则。"""

    def __init__(self, rules: Optional[List[DeductionRule]] = None):
        self.rules = rules if rules is not None else self._get_builtin_rules()
        self.state = ProofState()
        self.max_iterations = 100

    def _get_builtin_rules(self) -> List[DeductionRule]:
        """获取内置规则。"""
        rules = []

        # 垂直和平行规则
        rules.append(DeductionRule(
            "perp_to_para",
            ["perp A B C D", "perp E F C D"],
            ["para A B E F"]
        ))
        rules.append(DeductionRule(
            "para_trans",
            ["para A B C D", "para C D E F"],
            ["para A B E F"]
        ))
        rules.append(DeductionRule(
            "perp_to_para2",
            ["perp A B C D", "perp E F G H", "npara A B E F"],
            ["eqangle A B E F C D G H"]
        ))

        # 共圆规则
        rules.append(DeductionRule(
            "cong_to_cyclic",
            ["cong O A O B", "cong O B O C", "cong O C O D"],
            ["cyclic A B C D"]
        ))
        rules.append(DeductionRule(
            "cyclic_eqangle",
            ["cyclic A B P Q"],
            ["eqangle P A P B Q A Q B"]
        ))
        rules.append(DeductionRule(
            "eqangle6_to_cyclic",
            ["eqangle6 P A P B Q A Q B", "ncoll P Q A B"],
            ["cyclic A B P Q"]
        ))
        rules.append(DeductionRule(
            "cyclic_eqangle6_to_cong",
            ["cyclic A B C P Q R", "eqangle C A C B R P R Q"],
            ["cong A B P Q"]
        ))

        # 中点规则
        rules.append(DeductionRule(
            "midp_to_cong",
            ["midp M A B"],
            ["cong A M M B"]
        ))
        rules.append(DeductionRule(
            "midp_to_para",
            ["midp E A B", "midp F A C"],
            ["para E F B C"]
        ))
        rules.append(DeductionRule(
            "midp_to_para2",
            ["midp M A B", "para A C B D", "para A D B C"],
            ["midp M C D"]
        ))
        rules.append(DeductionRule(
            "midp_to_para3",
            ["midp M A B", "para A C B D"],
            ["para A C B D"]
        ))
        rules.append(DeductionRule(
            "midp_eqratio",
            ["midp M A B", "midp N C D"],
            ["eqratio M A A B N C C D"]
        ))

        # 全等传递规则
        rules.append(DeductionRule(
            "cong_trans",
            ["cong A B C D", "cong C D E F"],
            ["cong A B E F"]
        ))
        rules.append(DeductionRule(
            "cong_refl",
            [],
            ["cong A A B B"]
        ))

        # 圆定义规则
        rules.append(DeductionRule(
            "circle_def",
            ["circle O A", "circle O B"],
            ["cong O A O B"]
        ))
        rules.append(DeductionRule(
            "circle_perp",
            ["circle O A B C", "coll O A C"],
            ["perp A B B C"]
        ))

        # 共圆垂直规则
        rules.append(DeductionRule(
            "cyclic_perp",
            ["cyclic A B C D", "perp A B B C"],
            ["perp C D D A"]
        ))

        # 等角规则
        rules.append(DeductionRule(
            "eqangle_to_para",
            ["eqangle A B P Q C D P Q"],
            ["para A B C D"]
        ))
        rules.append(DeductionRule(
            "eqangle_to_perp",
            ["eqangle A B P Q C D U V", "perp P Q U V"],
            ["perp A B C D"]
        ))
        rules.append(DeductionRule(
            "eqangle_trans",
            ["eqangle a b c d m n p q", "eqangle c d e f p q r u"],
            ["eqangle a b e f m n r u"]
        ))

        # 等比规则
        rules.append(DeductionRule(
            "eqratio_to_cong",
            ["eqratio A B P Q C D U V", "cong P Q U V"],
            ["cong A B C D"]
        ))
        rules.append(DeductionRule(
            "eqratio_trans",
            ["eqratio a b c d m n p q", "eqratio c d e f p q r u"],
            ["eqratio a b e f m n r u"]
        ))

        # 等角等比转换规则
        rules.append(DeductionRule(
            "eqratio6_to_eqangle6",
            ["eqratio6 d b d c a b a c", "coll d b c", "ncoll a b c"],
            ["eqangle6 a b a d a d a c"]
        ))
        rules.append(DeductionRule(
            "eqangle6_to_eqratio6",
            ["eqangle6 a b a d a d a c", "coll d b c", "ncoll a b c"],
            ["eqratio6 d b d c a b a c"]
        ))

        # 全等和等角转换
        rules.append(DeductionRule(
            "cong_to_eqangle",
            ["cong O A O B", "ncoll O A B"],
            ["eqangle O A A B A B O B"]
        ))
        rules.append(DeductionRule(
            "eqangle6_to_cong",
            ["eqangle6 A O A B B A B O", "ncoll O A B"],
            ["cong O A O B"]
        ))

        # 圆中点规则
        rules.append(DeductionRule(
            "circle_midp_eqangle",
            ["circle O A B C", "midp M B C"],
            ["eqangle A B A C O B O M"]
        ))
        rules.append(DeductionRule(
            "circle_coll_eqangle_to_midp",
            ["circle O A B C", "coll M B C", "eqangle A B A C O B O M"],
            ["midp M B C"]
        ))

        # 中点垂直规则
        rules.append(DeductionRule(
            "midp_perp_to_cong",
            ["perp A B B C", "midp M A C"],
            ["cong A M B M"]
        ))

        # 全等三角形规则
        rules.append(DeductionRule(
            "cong_to_contri",
            ["cong A P B P", "cong A Q B Q", "cong C A R P", "ncoll A B C"],
            ["contri* A B C P Q R"]
        ))
        rules.append(DeductionRule(
            "cong_eqangle_to_contri",
            ["cong A P B P", "cong A Q B Q", "eqangle6 B A B C Q P Q R", "ncoll A B C"],
            ["contri* A B C P Q R"]
        ))

        # 相似三角形规则
        rules.append(DeductionRule(
            "eqangle_to_simtri",
            ["eqangle6 B A B C Q P Q R", "eqangle6 C A C B R P R Q", "ncoll A B C"],
            ["simtri A B C P Q R"]
        ))
        rules.append(DeductionRule(
            "eqangle2_to_simtri",
            ["eqangle6 B A B C Q R Q P", "eqangle6 C A C B R Q R P", "ncoll A B C"],
            ["simtri2 A B C P Q R"]
        ))
        rules.append(DeductionRule(
            "eqangle_cong_to_contri",
            ["eqangle6 B A B C Q P Q R", "eqangle6 C A C B R P R Q", "ncoll A B C", "cong A B P Q"],
            ["contri A B C P Q R"]
        ))
        rules.append(DeductionRule(
            "eqangle2_cong_to_contri2",
            ["eqangle6 B A B C Q R Q P", "eqangle6 C A C B R Q R P", "ncoll A B C", "cong A B P Q"],
            ["contri2 A B C P Q R"]
        ))

        # 等比相似规则
        rules.append(DeductionRule(
            "eqratio6_to_simtri",
            ["eqratio6 B A B C Q P Q R", "eqratio6 C A C B R P R Q", "ncoll A B C"],
            ["simtri* A B C P Q R"]
        ))
        rules.append(DeductionRule(
            "eqratio6_eqangle6_to_simtri",
            ["eqratio6 B A B C Q P Q R", "eqangle6 B A B C Q P Q R", "ncoll A B C"],
            ["simtri* A B C P Q R"]
        ))
        rules.append(DeductionRule(
            "eqratio6_cong_to_contri",
            ["eqratio6 B A B C Q P Q R", "eqratio6 C A C B R P R Q", "ncoll A B C", "cong A B P Q"],
            ["contri* A B C P Q R"]
        ))

        # 平行传递规则
        rules.append(DeductionRule(
            "para_eqratio",
            ["para a b c d", "coll m a d", "coll n b c", "eqratio6 m a m d n b n c", "sameside m a d n b c"],
            ["para m n a b"]
        ))
        rules.append(DeductionRule(
            "para_to_eqratio",
            ["para a b c d", "coll m a d", "coll n b c", "para m n a b"],
            ["eqratio6 m a m d n b n c"]
        ))

        # 平行共线规则
        rules.append(DeductionRule(
            "para_to_coll",
            ["para A B A C"],
            ["coll A B C"]
        ))

        # 等比平行规则
        rules.append(DeductionRule(
            "eqratio_to_para",
            ["eqratio O A A C O B B D", "coll O A C", "coll O B D", "ncoll A B C", "sameside A O C B O D"],
            ["para A B C D"]
        ))

        # 等腰三角形规则
        rules.append(DeductionRule(
            "isos_triangle",
            ["cong A B A C"],
            ["eqangle B A C A C A B"]
        ))

        return rules

    def add_statement(self, stmt_str: str, is_derived: bool = False) -> Statement:
        """添加命题。"""
        stmt = self._parse_statement(stmt_str)
        self.state.add(stmt, is_derived)
        return stmt

    def _parse_statement(self, stmt_str: str) -> Statement:
        """解析语句。"""
        stmt_str = stmt_str.strip()
        parts = stmt_str.split()
        if not parts:
            return Statement("", ())
        return Statement(parts[0], tuple(parts[1:]))

    def apply_rules(self) -> List[Statement]:
        """应用所有规则。"""
        new_statements = []
        for rule in self.rules:
            derived = rule.apply(self.state)
            for stmt in derived:
                self.state.add(stmt, is_derived=True)
                new_statements.append(stmt)
        return new_statements

    def deduce(self, max_steps: Optional[int] = None) -> int:
        """演绎推理。"""
        actual_max_steps = max_steps if max_steps is not None else self.max_iterations
        total_new = 0

        for _ in range(actual_max_steps):
            new = self.apply_rules()
            total_new += len(new)
            if not new:
                break

        return total_new

    def verify(self, stmt_str: str) -> bool:
        """验证命题。"""
        stmt = self._parse_statement(stmt_str)
        return self.state.contains(stmt)

    def can_derive(
        self, stmt_str: str, max_steps: Optional[int] = None
    ) -> Tuple[bool, List[Statement]]:
        """检查能否推导。"""
        if self.verify(stmt_str):
            return True, []

        original_state = ProofState(
            statements=self.state.statements.copy(), derived=self.state.derived.copy()
        )

        target = self._parse_statement(stmt_str)
        derivation_path = []

        actual_max_steps = max_steps if max_steps is not None else self.max_iterations

        for _ in range(actual_max_steps):
            new = self.apply_rules()
            derivation_path.extend(new)

            if self.state.contains(target):
                return True, derivation_path

        self.state = original_state
        return False, []

    def reset(self):
        """重置引擎。"""
        self.state = ProofState()

    def get_all_statements(self) -> List[str]:
        """获取所有命题。"""
        return [str(s) for s in self.state.statements]

    def get_derived_statements(self) -> List[str]:
        """获取推导命题。"""
        return [str(s) for s in self.state.derived]

    def get_rule_count(self) -> int:
        """获取规则数量。"""
        return len(self.rules)


if __name__ == "__main__":
    engine = ExtendedSymbolicEngine()

    print(f"加载了 {engine.get_rule_count()} 条演绎规则\n")

    # 测试垂直到平行规则
    print("=== 测试垂直到平行规则 ===")
    engine.reset()
    engine.add_statement("perp A B C D")
    engine.add_statement("perp E F C D")

    new = engine.deduce()
    print(f"推导出 {new} 条新语句")

    result, path = engine.can_derive("para A B E F")
    print(f"能否推导 'para A B E F': {result}")
    if path:
        print("推导路径:")
        for stmt in path:
            print(f"  {stmt}")

    # 测试共圆规则
    print("\n=== 测试共圆规则 ===")
    engine.reset()
    engine.add_statement("cong O A O B")
    engine.add_statement("cong O B O C")
    engine.add_statement("cong O C O D")

    new = engine.deduce()
    print(f"推导出 {new} 条新语句")

    result = engine.verify("cyclic A B C D")
    print(f"能否验证 'cyclic A B C D': {result}")

    # 测试中点规则
    print("\n=== 测试中点规则 ===")
    engine.reset()
    engine.add_statement("midp M A B")

    new = engine.deduce()
    print(f"推导出 {new} 条新语句")

    result = engine.verify("cong A M M B")
    print(f"能否验证 'cong A M M B': {result}")

    print("\n所有语句:")
    for stmt_str in engine.get_all_statements():
        print(f"  {stmt_str}")