# GENERATED BY AI
"""扩展的几何渲染引擎，支持所有 AlphaGeometry 谓词。"""

import math
from typing import List, Tuple, Optional, Dict, Any
from dataclasses import dataclass
import random


ATOM = 1e-9


@dataclass
class Point:
    """点。"""
    x: float
    y: float

    def __add__(self, other: "Point") -> "Point":
        return Point(self.x + other.x, self.y + other.y)

    def __sub__(self, other: "Point") -> "Point":
        return Point(self.x - other.x, self.y - other.y)

    def __mul__(self, scalar: float) -> "Point":
        return Point(self.x * scalar, self.y * scalar)

    def __rmul__(self, scalar: float) -> "Point":
        return self.__mul__(scalar)

    def distance(self, other: "Point") -> float:
        dx = self.x - other.x
        dy = self.y - other.y
        return math.sqrt(dx * dx + dy * dy)

    def close(self, other: "Point", tol: float = ATOM) -> bool:
        return abs(self.x - other.x) < tol and abs(self.y - other.y) < tol

    def __repr__(self):
        return f"Point({self.x:.6f}, {self.y:.6f})"


@dataclass
class Line:
    """线。"""
    a: float
    b: float
    c: float

    @classmethod
    def from_points(cls, p1: Point, p2: Point) -> "Line":
        if p1.close(p2):
            a, b, c = 0.0, 0.0, 0.0
        else:
            a = p1.y - p2.y
            b = p2.x - p1.x
            c = p1.x * p2.y - p2.x * p1.y
            if a < 0 or (a == 0 and b > 0):
                a, b, c = -a, -b, -c
        return cls(a, b, c)

    def distance(self, p: Point) -> float:
        denom = math.sqrt(self.a**2 + self.b**2)
        if denom < ATOM:
            return 0.0
        return abs(self.a * p.x + self.b * p.y + self.c) / denom

    def is_parallel(self, other: "Line") -> bool:
        return abs(self.a * other.b - self.b * other.a) < ATOM

    def is_perpendicular(self, other: "Line") -> bool:
        return abs(self.a * other.a + self.b * other.b) < ATOM

    def intersect(self, other: "Line") -> Optional[Point]:
        d = self.a * other.b - other.a * self.b
        if abs(d) < ATOM:
            return None
        x = (other.c * self.b - self.c * other.b) / d
        y = (self.c * other.a - other.c * self.a) / d
        return Point(x, y)


@dataclass
class Circle:
    """圆。"""
    center: Point
    radius: float

    @classmethod
    def from_three_points(cls, p1: Point, p2: Point, p3: Point) -> Optional["Circle"]:
        l12 = Line.from_points(p1, p2)
        l23 = Line.from_points(p2, p3)

        mid12 = Point((p1.x + p2.x) / 2, (p1.y + p2.y) / 2)
        mid23 = Point((p2.x + p3.x) / 2, (p2.y + p3.y) / 2)

        perp12 = Line(-l12.b, l12.a, l12.b * mid12.x - l12.a * mid12.y)
        perp23 = Line(-l23.b, l23.a, l23.b * mid23.x - l23.a * mid23.y)

        center = perp12.intersect(perp23)
        if center is None:
            return None

        radius = center.distance(p1)
        return cls(center, radius)

    def contains(self, p: Point, tol: float = ATOM) -> bool:
        return abs(self.center.distance(p) - self.radius) < tol

    def intersect_circle(self, other: "Circle") -> Tuple[Optional[Point], Optional[Point]]:
        """计算两圆的交点。"""
        d = self.center.distance(other.center)
        if d > self.radius + other.radius + ATOM:
            return None, None
        if d < abs(self.radius - other.radius) - ATOM:
            return None, None
        if d < ATOM and abs(self.radius - other.radius) < ATOM:
            return None, None

        a = (self.radius**2 - other.radius**2 + d**2) / (2 * d)
        h = math.sqrt(max(0, self.radius**2 - a**2))

        x2 = self.center.x + a * (other.center.x - self.center.x) / d
        y2 = self.center.y + a * (other.center.y - self.center.y) / d

        x3_1 = x2 + h * (other.center.y - self.center.y) / d
        y3_1 = y2 - h * (other.center.x - self.center.x) / d
        x3_2 = x2 - h * (other.center.y - self.center.y) / d
        y3_2 = y2 + h * (other.center.x - self.center.x) / d

        return Point(x3_1, y3_1), Point(x3_2, y3_2)


class ExtendedRenderEngine:
    """扩展的渲染引擎，支持所有 AlphaGeometry 谓词。"""

    def __init__(self, seed: int = 42):
        random.seed(seed)
        self.points: Dict[str, Point] = {}
        self.lines: Dict[str, Line] = {}
        self.circles: Dict[str, Circle] = {}

    def reset(self):
        """重置引擎状态。"""
        self.points = {}
        self.lines = {}
        self.circles = {}

    def create_random_point(
        self, name: str, existing: Optional[List[Point]] = None
    ) -> Point:
        """创建随机点。"""
        if existing:
            cx = sum(p.x for p in existing) / len(existing)
            cy = sum(p.y for p in existing) / len(existing)
            scale = (
                max(p.distance(Point(cx, cy)) for p in existing) if existing else 1.0
            )
        else:
            cx, cy = 0.0, 0.0
            scale = 1.0

        for _ in range(100):
            angle = random.uniform(0, 2 * math.pi)
            dist = random.uniform(0.5, 2.0) * scale
            p = Point(cx + dist * math.cos(angle), cy + dist * math.sin(angle))

            valid = True
            if existing:
                for ep in existing:
                    if p.close(ep, tol=0.1 * scale):
                        valid = False
                        break

            if valid:
                return p

        return Point(random.uniform(-1, 1), random.uniform(-1, 1))

    def _get_points(self, point_names: List[str]) -> List[Point]:
        """获取点列表。"""
        points = []
        for name in point_names:
            pt = self.points.get(name)
            if pt is None:
                pt = self.create_random_point(name, list(self.points.values()))
                self.points[name] = pt
            points.append(pt)
        return points

    # 基本关系验证

    def verify_collinear(self, points: List[Point]) -> bool:
        """验证共线。"""
        if len(points) < 3:
            return True

        line = Line.from_points(points[0], points[1])
        for p in points[2:]:
            if line.distance(p) > ATOM:
                return False
        return True

    def verify_parallel(self, p1: Point, p2: Point, p3: Point, p4: Point) -> bool:
        """验证平行。"""
        l1 = Line.from_points(p1, p2)
        l2 = Line.from_points(p3, p4)
        return l1.is_parallel(l2)

    def verify_perpendicular(self, p1: Point, p2: Point, p3: Point, p4: Point) -> bool:
        """验证垂直。"""
        l1 = Line.from_points(p1, p2)
        l2 = Line.from_points(p3, p4)
        return l1.is_perpendicular(l2)

    def verify_congruent(self, p1: Point, p2: Point, p3: Point, p4: Point) -> bool:
        """验证全等（线段相等）。"""
        d1 = p1.distance(p2)
        d2 = p3.distance(p4)
        return abs(d1 - d2) < ATOM

    def verify_midpoint(self, m: Point, a: Point, b: Point) -> bool:
        """验证中点。"""
        return self.verify_collinear([m, a, b]) and self.verify_congruent(m, a, m, b)

    def verify_cyclic(self, points: List[Point]) -> bool:
        """验证共圆。"""
        if len(points) < 4:
            return True

        circle = Circle.from_three_points(points[0], points[1], points[2])
        if circle is None:
            return False

        for p in points[3:]:
            if not circle.contains(p):
                return False
        return True

    def verify_circle(self, center: Point, radius: float, point: Point) -> bool:
        """验证点在圆上。"""
        return abs(center.distance(point) - radius) < ATOM

    # 角度相关验证

    def _angle(self, p1: Point, p2: Point, p3: Point) -> float:
        """计算角度 p1-p2-p3。"""
        v1 = p1 - p2
        v2 = p3 - p2
        dot = v1.x * v2.x + v1.y * v2.y
        cross = v1.x * v2.y - v1.y * v2.x
        return math.atan2(abs(cross), dot)

    def verify_eqangle(
        self, p1: Point, p2: Point, p3: Point, p4: Point, p5: Point, p6: Point
    ) -> bool:
        """验证等角 (eqangle p1 p2 p3 p4 p5 p6)。"""
        angle1 = self._angle(p1, p2, p3)
        angle2 = self._angle(p4, p5, p6)
        return abs(angle1 - angle2) < ATOM

    def verify_eqangle6(
        self,
        p1: Point, p2: Point, p3: Point,
        p4: Point, p5: Point, p6: Point
    ) -> bool:
        """验证六点等角 (eqangle6 p1 p2 p3 p4 p5 p6)。"""
        return self.verify_eqangle(p1, p2, p3, p4, p5, p6)

    # 比例相关验证

    def _ratio(self, p1: Point, p2: Point, p3: Point, p4: Point) -> float:
        """计算比例 (p1p2)/(p3p4)。"""
        d1 = p1.distance(p2)
        d2 = p3.distance(p4)
        if d2 < ATOM:
            return float('inf')
        return d1 / d2

    def verify_eqratio(
        self,
        p1: Point, p2: Point, p3: Point, p4: Point,
        p5: Point, p6: Point, p7: Point, p8: Point
    ) -> bool:
        """验证等比 (eqratio p1 p2 p3 p4 p5 p6 p7 p8)。"""
        ratio1 = self._ratio(p1, p2, p3, p4)
        ratio2 = self._ratio(p5, p6, p7, p8)
        return abs(ratio1 - ratio2) < ATOM

    def verify_eqratio6(
        self,
        p1: Point, p2: Point, p3: Point, p4: Point,
        p5: Point, p6: Point, p7: Point, p8: Point
    ) -> bool:
        """验证六点等比。"""
        return self.verify_eqratio(p1, p2, p3, p4, p5, p6, p7, p8)

    # 否定关系验证

    def verify_ncoll(self, points: List[Point]) -> bool:
        """验证不共线。"""
        return not self.verify_collinear(points)

    def verify_npara(self, p1: Point, p2: Point, p3: Point, p4: Point) -> bool:
        """验证不平行。"""
        return not self.verify_parallel(p1, p2, p3, p4)

    def verify_nperp(self, p1: Point, p2: Point, p3: Point, p4: Point) -> bool:
        """验证不垂直。"""
        return not self.verify_perpendicular(p1, p2, p3, p4)

    def verify_diff(self, p1: Point, p2: Point) -> bool:
        """验证两点不同。"""
        return not p1.close(p2)

    # 特殊关系验证

    def verify_sameside(
        self, p1: Point, p2: Point, p3: Point, p4: Point
    ) -> bool:
        """验证 p1 和 p2 在直线 p3p4 同侧。"""
        line = Line.from_points(p3, p4)
        val1 = line.a * p1.x + line.b * p1.y + line.c
        val2 = line.a * p2.x + line.b * p2.y + line.c
        return val1 * val2 > 0

    # 三角形关系验证

    def verify_contri(
        self,
        a: Point, b: Point, c: Point,
        p: Point, q: Point, r: Point
    ) -> bool:
        """验证全等三角形 (contri a b c p q r)。"""
        ab = a.distance(b)
        bc = b.distance(c)
        ca = c.distance(a)
        pq = p.distance(q)
        qr = q.distance(r)
        rp = r.distance(p)

        return (
            abs(ab - pq) < ATOM and
            abs(bc - qr) < ATOM and
            abs(ca - rp) < ATOM
        )

    def verify_simtri(
        self,
        a: Point, b: Point, c: Point,
        p: Point, q: Point, r: Point
    ) -> bool:
        """验证相似三角形 (simtri a b c p q r)。"""
        ab = a.distance(b)
        bc = b.distance(c)
        ca = c.distance(a)
        pq = p.distance(q)
        qr = q.distance(r)
        rp = r.distance(p)

        ratio1 = ab / pq if pq > ATOM else float('inf')
        ratio2 = bc / qr if qr > ATOM else float('inf')
        ratio3 = ca / rp if rp > ATOM else float('inf')

        return (
            abs(ratio1 - ratio2) < ATOM and
            abs(ratio2 - ratio3) < ATOM
        )

    def verify_contri2(
        self,
        a: Point, b: Point, c: Point,
        p: Point, q: Point, r: Point
    ) -> bool:
        """验证全等三角形变体 (contri2)。"""
        return self.verify_contri(a, b, c, p, q, r)

    def verify_simtri2(
        self,
        a: Point, b: Point, c: Point,
        p: Point, q: Point, r: Point
    ) -> bool:
        """验证相似三角形变体 (simtri2)。"""
        return self.verify_simtri(a, b, c, p, q, r)

    # 主验证函数

    def verify_proposition(self, prop_type: str, points: List[Point]) -> bool:
        """验证命题。"""
        if len(points) < 2:
            return True

        # 基本关系
        if prop_type == "coll":
            return self.verify_collinear(points)
        if prop_type == "para":
            if len(points) < 4:
                return True
            return self.verify_parallel(points[0], points[1], points[2], points[3])
        if prop_type == "perp":
            if len(points) < 4:
                return True
            return self.verify_perpendicular(points[0], points[1], points[2], points[3])
        if prop_type == "cong":
            if len(points) < 4:
                return True
            return self.verify_congruent(points[0], points[1], points[2], points[3])
        if prop_type == "midp":
            if len(points) < 3:
                return True
            return self.verify_midpoint(points[0], points[1], points[2])
        if prop_type == "cyclic":
            return self.verify_cyclic(points)

        # 角度关系
        if prop_type == "eqangle":
            if len(points) < 6:
                return True
            return self.verify_eqangle(points[0], points[1], points[2],
                                   points[3], points[4], points[5])
        if prop_type == "eqangle6":
            if len(points) < 6:
                return True
            return self.verify_eqangle6(points[0], points[1], points[2],
                                     points[3], points[4], points[5])

        # 比例关系
        if prop_type == "eqratio":
            if len(points) < 8:
                return True
            return self.verify_eqratio(points[0], points[1], points[2], points[3],
                                   points[4], points[5], points[6], points[7])
        if prop_type == "eqratio6":
            if len(points) < 8:
                return True
            return self.verify_eqratio6(points[0], points[1], points[2], points[3],
                                     points[4], points[5], points[6], points[7])

        # 否定关系
        if prop_type == "ncoll":
            return self.verify_ncoll(points)
        if prop_type == "npara":
            if len(points) < 4:
                return True
            return self.verify_npara(points[0], points[1], points[2], points[3])
        if prop_type == "nperp":
            if len(points) < 4:
                return True
            return self.verify_nperp(points[0], points[1], points[2], points[3])
        if prop_type == "diff":
            if len(points) < 2:
                return True
            return self.verify_diff(points[0], points[1])

        # 特殊关系
        if prop_type == "sameside":
            if len(points) < 4:
                return True
            return self.verify_sameside(points[0], points[1], points[2], points[3])

        # 三角形关系
        if prop_type == "contri":
            if len(points) < 6:
                return True
            return self.verify_contri(points[0], points[1], points[2],
                                   points[3], points[4], points[5])
        if prop_type == "simtri":
            if len(points) < 6:
                return True
            return self.verify_simtri(points[0], points[1], points[2],
                                   points[3], points[4], points[5])
        if prop_type == "contri2":
            if len(points) < 6:
                return True
            return self.verify_contri2(points[0], points[1], points[2],
                                     points[3], points[4], points[5])
        if prop_type == "simtri2":
            if len(points) < 6:
                return True
            return self.verify_simtri2(points[0], points[1], points[2],
                                     points[3], points[4], points[5])

        return True


if __name__ == "__main__":
    engine = ExtendedRenderEngine()

    # 测试基本关系
    print("=== 测试基本关系 ===")
    engine.points = {
        "A": Point(0, 0),
        "B": Point(1, 0),
        "C": Point(0, 1),
        "D": Point(1, 1),
    }

    points = engine._get_points(["A", "B", "C"])
    result = engine.verify_collinear(points)
    print(f"coll A B C: {result}")

    points = engine._get_points(["A", "B", "C", "D"])
    result = engine.verify_parallel(points[0], points[1], points[2], points[3])
    print(f"para A B C D: {result}")

    result = engine.verify_perpendicular(points[0], points[1], points[2], points[3])
    print(f"perp A B C D: {result}")

    # 测试角度关系
    print("\n=== 测试角度关系 ===")
    engine.points = {
        "A": Point(0, 0),
        "B": Point(1, 0),
        "C": Point(0, 1),
        "D": Point(1, 1),
        "E": Point(0, 0),
        "F": Point(1, 0),
    }

    points = engine._get_points(["A", "B", "C", "D", "E", "F"])
    result = engine.verify_eqangle(points[0], points[1], points[2],
                              points[3], points[4], points[5])
    print(f"eqangle A B C D E F: {result}")

    # 测试比例关系
    print("\n=== 测试比例关系 ===")
    engine.points = {
        "A": Point(0, 0),
        "B": Point(1, 0),
        "C": Point(0, 0),
        "D": Point(2, 0),
        "E": Point(0, 0),
        "F": Point(1, 0),
        "G": Point(0, 0),
        "H": Point(2, 0),
    }

    points = engine._get_points(["A", "B", "C", "D", "E", "F", "G", "H"])
    result = engine.verify_eqratio(points[0], points[1], points[2], points[3],
                              points[4], points[5], points[6], points[7])
    print(f"eqratio A B C D E F G H: {result}")

    # 测试三角形关系
    print("\n=== 测试三角形关系 ===")
    engine.points = {
        "A": Point(0, 0),
        "B": Point(1, 0),
        "C": Point(0.5, math.sqrt(3) / 2),
        "D": Point(2, 0),
        "E": Point(3, 0),
        "F": Point(2.5, math.sqrt(3) / 2),
    }

    points = engine._get_points(["A", "B", "C", "D", "E", "F"])
    result = engine.verify_simtri(points[0], points[1], points[2],
                           points[3], points[4], points[5])
    print(f"simtri A B C D E F: {result}")
