# GENERATED BY AI
"""
训练数据生成脚本
通过受控的逐步推理生成训练数据
"""

import os
import sys
import random
import json

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from data_generator import (
    GeometryDefinitions,
    DeductionRules,
    ProofStep,
    ProofData,
)  # pylint: disable=wrong-import-position

# ==================== 配置参数 ====================
MAX_STEPS = 20
MIN_STEPS = 10
NUM_PROBLEMS = 10
OUTPUT_FILE = os.path.join(os.path.dirname(__file__), "generated_training_data.json")
# =================================================


class ControlledReasoningEngine:
    """受控推理引擎 - 每步只产生一个新命题"""

    def __init__(self):
        self.definitions = GeometryDefinitions.DEFINITIONS
        self.rules = DeductionRules.RULES
        self.predicates = {}
        self.predicate_list = []
        self.proof_steps = []
        self.level = 0

    def reset(self):
        self.predicates = {}
        self.predicate_list = []
        self.proof_steps = []
        self.level = 0

    def normalize(self, pred):
        parts = pred.strip().split()
        if not parts:
            return ()
        name = parts[0]
        args = (
            tuple(sorted(parts[1:]))
            if name in ["coll", "cyclic", "ncoll"]
            else tuple(parts[1:])
        )
        return (name, args)

    def add(self, pred):
        key = self.normalize(pred)
        if key not in self.predicates:
            self.predicates[key] = pred
            self.predicate_list.append(pred)
            return True
        return False

    def expand_construction(self, construction):
        if " = " not in construction:
            return []
        _points_part, const_part = construction.split(" = ", 1)
        const_parts = const_part.strip().split()
        const_name = const_parts[0] if const_parts else ""
        const_args = const_parts[1:] if len(const_parts) > 1 else []
        if const_name not in self.definitions:
            return []
        definition = self.definitions[const_name]
        predicates = []
        arg_names = definition.get("args", [])
        var_mapping = {}
        for i, arg_name in enumerate(arg_names):
            if i < len(const_args):
                var_mapping[arg_name] = const_args[i]
        for template in definition.get("predicates", []):
            parts = template.split()
            result = [parts[0]]
            valid = True
            for arg in parts[1:]:
                if arg in var_mapping:
                    result.append(var_mapping[arg])
                elif len(arg) == 1 and arg.isalpha():
                    result.append(arg)
                else:
                    valid = False
                    break
            if valid:
                predicates.append(" ".join(result))
        return predicates

    def step_forward(self):
        """向前推理一步，只返回一个随机选择的新命题（优化版：预先过滤已存在的结论）"""
        self.level += 1
        valid_matches = []
        for rule in self.rules:
            matches = self._find_all_matches(rule)
            for m in matches:
                conclusion = self._apply(rule, m)
                if conclusion:
                    normalized = self.normalize(conclusion)
                    if normalized not in self.predicates:
                        valid_matches.append((rule, m, conclusion))
        if not valid_matches:
            return []
        chosen_rule, chosen_match, conclusion = random.choice(valid_matches)
        self.predicates[self.normalize(conclusion)] = conclusion
        self.predicate_list.append(conclusion)
        premises = self._get_matched_premises(chosen_rule, chosen_match)
        step = ProofStep(premises, conclusion, chosen_rule["name"], self.level)
        self.proof_steps.append(step)
        return [step]

    def _find_all_matches(self, rule):
        matches = []
        premises = rule["premises"]
        if len(premises) == 1:
            for pred in self.predicate_list:
                mapping = self._match_single(premises[0], pred, {})
                if mapping is not None:
                    matches.append((mapping, [pred]))
        elif len(premises) == 2:
            for pred in self.predicate_list:
                mapping = self._match_single(premises[0], pred, {})
                if mapping is None:
                    continue
                for pred2 in self.predicate_list:
                    if pred2 == pred:
                        continue
                    mapping2 = self._match_single(premises[1], pred2, mapping.copy())
                    if mapping2 is not None:
                        matches.append((mapping2, [pred, pred2]))
        return matches

    def _match_single(self, template, actual, mapping):
        t_parts = template.split()
        a_parts = actual.split()
        if len(t_parts) != len(a_parts):
            return None
        if t_parts[0] != a_parts[0]:
            return None
        new_mapping = mapping.copy()
        for t, a in zip(t_parts[1:], a_parts[1:]):
            if t in new_mapping:
                if new_mapping[t] != a:
                    return None
            else:
                new_mapping[t] = a
        return new_mapping

    def _apply(self, rule, match_data):
        mapping = match_data[0]
        conclusion = rule["conclusion"]
        parts = conclusion.split()
        result = [parts[0]]
        for arg in parts[1:]:
            if arg in mapping:
                result.append(mapping[arg])
            else:
                return ""
        return " ".join(result)

    def _get_matched_premises(self, _rule, match_data):
        return match_data[1]


def generate_random_construction():
    point_names = list("abcdefghijklmnopqrstuvwxyz")
    construction_types = [
        ("triangle", lambda: [f"{' '.join(random.sample(point_names, 3))} = triangle"]),
        (
            "midpoint",
            lambda: _gen_midpoint_construction(point_names),
        ),
        (
            "circumcenter",
            lambda: _gen_circumcenter_construction(point_names),
        ),
        (
            "orthocenter",
            lambda: _gen_orthocenter_construction(point_names),
        ),
        (
            "parallelogram",
            lambda: [
                f"{' '.join(random.sample(point_names, 4))} = parallelogram {' '.join(random.sample(point_names, 4))}"
            ],
        ),
    ]
    _, constructor = random.choice(construction_types)
    return constructor()


def _gen_midpoint_construction(point_names):
    a, b, c, m = random.sample(point_names, 4)
    return [
        f"{a} {b} {c} = triangle",
        f"{m} = midpoint {m} {a} {b}",
    ]


def _gen_circumcenter_construction(point_names):
    a, b, c, o = random.sample(point_names, 4)
    return [
        f"{a} {b} {c} = triangle",
        f"{o} = circumcenter {o} {a} {b} {c}",
    ]


def _gen_orthocenter_construction(point_names):
    a, b, c, h = random.sample(point_names, 4)
    return [
        f"{a} {b} {c} = triangle",
        f"{h} = orthocenter {h} {a} {b} {c}",
    ]


def generate_training_data():
    """生成训练数据主函数"""
    print("=" * 60)
    print("几何证明训练数据生成器 (受控推理)")
    print("=" * 60)
    print("\n配置参数:")
    print(f"  最小步数: {MIN_STEPS}")
    print(f"  最大步数: {MAX_STEPS}")
    print(f"  目标数量: {NUM_PROBLEMS}")
    print(f"  输出文件: {OUTPUT_FILE}")
    print()

    engine = ControlledReasoningEngine()
    valid_data = []
    attempts = 0
    max_attempts = 1000

    print("开始生成数据...\n")

    while len(valid_data) < NUM_PROBLEMS and attempts < max_attempts:
        attempts += 1
        engine.reset()
        constructions = generate_random_construction()
        setup_predicates = []
        for const in constructions:
            for pred in engine.expand_construction(const):
                if engine.add(pred):
                    setup_predicates.append(pred)
        if not setup_predicates:
            continue
        target_steps = random.randint(MIN_STEPS, MAX_STEPS)
        for _ in range(target_steps):
            new_steps = engine.step_forward()
            if not new_steps:
                break
        total_steps = len(engine.proof_steps)
        if MIN_STEPS <= total_steps <= MAX_STEPS and engine.proof_steps:
            goal = engine.proof_steps[-1].conclusion
            proof_data = ProofData(
                problem_name=f"controlled_{len(valid_data)}",
                problem_statement="; ".join(constructions) + f" ? {goal}",
                constructions=constructions,
                goal=goal,
                proof_steps=engine.proof_steps,
                is_solved=True,
                setup_predicates=setup_predicates,
            )
            valid_data.append(proof_data)
            print(f"  [✓] 问题 {len(valid_data)}: {total_steps} 步, 目标: {goal}")
        else:
            if attempts % 50 == 0:
                print(
                    f"  已尝试 {attempts} 次, 已收集 {len(valid_data)}/{NUM_PROBLEMS} (上次: {total_steps}步)"
                )

    print("\n" + "=" * 60)
    print("生成统计:")
    print(f"  总尝试数: {attempts}")
    print(f"  有效数据: {len(valid_data)}")
    if valid_data:
        step_counts = [len(d.proof_steps) for d in valid_data]
        print(f"  步数范围: {min(step_counts)} - {max(step_counts)}")
        print(f"  平均步数: {sum(step_counts)/len(step_counts):.1f}")
        data_list = [d.to_training_format() for d in valid_data]
        with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
            json.dump(data_list, f, ensure_ascii=False, indent=2)
        print(f"\n已保存到: {OUTPUT_FILE}")
    else:
        print("\n警告: 没有生成有效数据!")
    print("=" * 60)
    return valid_data


def verify_generated_data():
    """验证生成的训练数据"""
    print("\n" + "=" * 60)
    print("验证生成的训练数据")
    print("=" * 60)
    if not os.path.exists(OUTPUT_FILE):
        print("错误: 数据文件不存在!")
        return
    with open(OUTPUT_FILE, "r", encoding="utf-8") as f:
        data = json.load(f)
    print(f"\n共加载 {len(data)} 条数据")
    print(f"步数要求: {MIN_STEPS} - {MAX_STEPS} 步\n")
    all_valid = True
    for item in data:
        step_count = len(item.get("proof_steps", []))
        is_valid = MIN_STEPS <= step_count <= MAX_STEPS
        status = "✓" if is_valid else "✗"
        if not is_valid:
            all_valid = False
        print(
            f"  [{status}] {item['problem_name']}: {step_count} 步, 目标: {item['goal']}"
        )
    print("\n" + "=" * 60)
    if all_valid:
        print("验证结果: 所有数据都符合步数要求 ✓")
    else:
        print("验证结果: 存在不符步数要求的数据 ✗")
    print("=" * 60)


if __name__ == "__main__":
    generate_training_data()
    verify_generated_data()
