# GENERATED BY AI
"""几何命题语法解析器。

支持 AlphaGeometry 格式的命题、构造和问题解析。
"""

from typing import List, Tuple, Optional, Dict, Any
from dataclasses import dataclass
import re


@dataclass
class Proposition:
    """几何命题。"""
    predicate: str
    args: Tuple[str, ...]

    def __str__(self):
        return f"{self.predicate} {' '.join(self.args)}"

    def __hash__(self):
        return hash((self.predicate, self.args))

    def __eq__(self, other):
        if not isinstance(other, Proposition):
            return False
        return self.predicate == other.predicate and self.args == other.args


@dataclass
class Construction:
    """几何构造。"""
    predicate: str
    args: List[str]

    def __str__(self):
        return f"{self.predicate} {' '.join(self.args)}"

    def translate(self, mapping: Dict[str, str]) -> "Construction":
        """使用点名称映射转换构造。"""
        args = []
        for a in self.args:
            if a.isdigit():
                args.append(a)
            else:
                args.append(mapping.get(a, a))
        return Construction(self.predicate, args)


@dataclass
class Clause:
    """一个子句，包含点声明和构造列表。"""
    points: List[str]
    constructions: List[Construction]

    def __str__(self):
        if not self.points:
            return " ="
        points_str = ' '.join(self.points)
        if not self.constructions:
            return f"{points_str} ="
        cons_str = ', '.join(str(c) for c in self.constructions)
        return f"{points_str} = {cons_str}"

    def translate(self, mapping: Dict[str, str]) -> "Clause":
        """使用点名称映射转换子句。"""
        points = [mapping.get(p, p) for p in self.points]
        constructions = [c.translate(mapping) for c in self.constructions]
        return Clause(points, constructions)


@dataclass
class Problem:
    """几何问题。"""
    name: str
    premises: List[Clause]
    goal: Optional[Proposition]

    def __str__(self):
        lines = [self.name]
        for clause in self.premises:
            lines.append(str(clause))
        if self.goal:
            lines.append(f"? {self.goal}")
        return '\n'.join(lines)


class GeometryParser:
    """AlphaGeometry 格式语法解析器。"""

    def __init__(self):
        self._init_predicates()

    def _init_predicates(self):
        """初始化支持的谓词列表。"""
        # 基本关系谓词
        self.basic_predicates = {
            'coll', 'para', 'perp', 'cong', 'midp', 'cyclic',
            'circle', 'eqangle', 'eqangle6', 'eqratio', 'eqratio6',
            'contri', 'simtri', 'contri2', 'simtri2', 'contri*', 'simtri*',
            'sameside', 'ncoll', 'npara', 'nperp', 'diff', 'rconst'
        }

        # 构造谓词
        self.construction_predicates = {
            # 点构造
            'free', 'midpoint', 'foot',
            'intersection_ll', 'intersection_lc', 'intersection_cc',
            'intersection_lp', 'intersection_lt', 'intersection_pp', 'intersection_tt',
            # 线构造
            'on_line', 'on_pline', 'on_tline', 'on_bline',
            'on_aline', 'on_aline2', 'on_opline',
            # 圆构造
            'on_circle', 'circle', 'circumcenter', 'on_circum',
            # 特殊点
            'orthocenter', 'incenter', 'excenter', 'incenter2', 'excenter2',
            'centroid', 'ninepoints',
            # 多边形
            'triangle', 'iso_triangle', 'r_triangle', 'triangle12', 'ieq_triangle',
            'rectangle', 'parallelogram', 'trapezoid', 'r_trapezoid',
            'square', 'isquare', 'pentagon', 'quadrangle',
            'eq_quadrangle', 'eq_trapezoid', 'eqdia_quadrangle',
            # 角度构造
            'angle_bisector', 'angle_mirror', 'eqangle2', 'eqangle3',
            # 反射和旋转
            'mirror', 'reflect', 'nsquare', 'psquare', 'shift',
            # 其他
            'eq_triangle', 'eqdistance', 'trisect', 'trisegment',
            'on_dia', 'lc_tangent', 'cc_tangent', 'cc_tangent0', 'tangent',
            's_angle', '2l1c', 'e5128', '3peq', 'segment'
        }

    def parse_proposition(self, text: str) -> Optional[Proposition]:
        """解析单个命题。"""
        text = text.strip()
        if not text:
            return None

        # 移除注释
        if '#' in text:
            text = text.split('#')[0].strip()

        parts = text.split()
        if not parts:
            return None

        predicate = parts[0]
        args = tuple(parts[1:])

        return Proposition(predicate, args)

    def parse_construction(self, text: str) -> Optional[Construction]:
        """解析单个构造。"""
        text = text.strip()
        if not text:
            return None

        parts = text.split()
        if not parts:
            return None

        predicate = parts[0]
        args = parts[1:]

        return Construction(predicate, args)

    def parse_clause(self, text: str) -> Optional[Clause]:
        """解析一个子句。"""
        text = text.strip()
        if not text:
            return None

        # 分割点声明和构造
        if ' = ' in text:
            parts = text.split(' = ')
            points_part = parts[0].strip()
            cons_part = parts[1].strip() if len(parts) > 1 else ''
        else:
            points_part = text
            cons_part = ''

        # 解析点
        points = []
        if points_part:
            points = points_part.split()

        # 解析构造
        constructions = []
        if cons_part:
            for cons_text in cons_part.split(', '):
                cons = self.parse_construction(cons_text.strip())
                if cons:
                    constructions.append(cons)

        return Clause(points, constructions)

    def parse_problem(self, text: str) -> Optional[Problem]:
        """解析完整的问题。"""
        lines = [line.strip() for line in text.strip().split('\n') if line.strip()]

        if not lines:
            return None

        # 第一行是问题名称
        name = lines[0]

        # 解析前提和目标
        premises = []
        goal = None

        for line in lines[1:]:
            if line.startswith('? '):
                # 目标
                goal_text = line[2:].strip()
                goal = self.parse_proposition(goal_text)
            else:
                # 前提
                clause = self.parse_clause(line)
                if clause:
                    premises.append(clause)

        return Problem(name, premises, goal)

    def parse_problem_file(self, content: str) -> List[Problem]:
        """解析包含多个问题的文件。"""
        problems = []
        current_problem_lines = []

        for line in content.split('\n'):
            line = line.strip()

            if not line:
                if current_problem_lines:
                    problem_text = '\n'.join(current_problem_lines)
                    problem = self.parse_problem(problem_text)
                    if problem:
                        problems.append(problem)
                    current_problem_lines = []
            else:
                current_problem_lines.append(line)

        # 处理最后一个问题
        if current_problem_lines:
            problem_text = '\n'.join(current_problem_lines)
            problem = self.parse_problem(problem_text)
            if problem:
                problems.append(problem)

        return problems

    def parse_premises(self, text: str) -> List[Proposition]:
        """解析前提列表，返回命题列表。"""
        propositions = []

        # 解析子句
        clauses = []
        for line in text.split(';'):
            line = line.strip()
            if line:
                clause = self.parse_clause(line)
                if clause:
                    clauses.append(clause)

        # 从子句中提取命题
        for clause in clauses:
            for cons in clause.constructions:
                prop = Proposition(cons.predicate, tuple(cons.args))
                propositions.append(prop)

        return propositions

    def is_valid_predicate(self, predicate: str) -> bool:
        """检查谓词是否有效。"""
        return predicate in self.basic_predicates or predicate in self.construction_predicates

    def is_construction(self, predicate: str) -> bool:
        """检查是否为构造谓词。"""
        return predicate in self.construction_predicates

    def is_basic_relation(self, predicate: str) -> bool:
        """检查是否为基本关系谓词。"""
        return predicate in self.basic_predicates


if __name__ == "__main__":
    parser = GeometryParser()

    # 测试命题解析
    print("=== 测试命题解析 ===")
    prop = parser.parse_proposition("perp A B C D")
    print(f"命题: {prop}")

    prop = parser.parse_proposition("coll A B C")
    print(f"命题: {prop}")

    # 测试构造解析
    print("\n=== 测试构造解析 ===")
    cons = parser.parse_construction("on_line X A B")
    print(f"构造: {cons}")

    cons = parser.parse_construction("on_tline H B A C")
    print(f"构造: {cons}")

    # 测试子句解析
    print("\n=== 测试子句解析 ===")
    clause = parser.parse_clause("a b c = triangle")
    print(f"子句: {clause}")

    clause = parser.parse_clause("h = on_tline h b a c, on_tline h c a b")
    print(f"子句: {clause}")

    # 测试问题解析
    print("\n=== 测试问题解析 ===")
    problem_text = """orthocenter
a b c = triangle
h = on_tline h b a c, on_tline h c a b ? perp a h b c"""

    problem = parser.parse_problem(problem_text)
    print(f"问题:\n{problem}")

    # 测试问题文件解析
    print("\n=== 测试问题文件解析 ===")
    file_content = """orthocenter
a b c = triangle
h = on_tline h b a c, on_tline h c a b ? perp a h b c

incenter_excenter
a b c = triangle a b c
d1 d2 d3 d = incenter2 a b c
e1 e2 e3 e = excenter2 a b c ? perp d c c e"""

    problems = parser.parse_problem_file(file_content)
    print(f"解析到 {len(problems)} 个问题")
    for i, prob in enumerate(problems, 1):
        print(f"\n问题 {i}: {prob.name}")
