# GENERATED BY AI
"""
几何定义 - 单一数据源

所有谓词、构造、演绎规则的统一定义。
其他模块应该从这里导入，而不是各自定义。
"""

from typing import Dict, List, Optional, Any
from dataclasses import dataclass, field


@dataclass
class PredicateDef:
    """谓词定义"""
    name: str
    arity: int  # 参数数量，-1 表示可变
    description: str
    normalize_args: bool = False  # 是否对参数排序进行规范化


@dataclass
class ConstructionDef:
    """构造定义"""
    name: str
    args: List[str]
    predicates: List[str]
    description: str
    requires: List[str] = field(default_factory=list)  # 依赖的其他构造
    requires_args: List[int] = field(default_factory=list)  # 从依赖构造中取参数的索引


@dataclass
class RuleDef:
    """演绎规则定义"""
    name: str
    premises: List[str]
    conclusion: str


class GeometryPredicates:
    """几何谓词定义 - 单一数据源"""

    PREDICATES: Dict[str, PredicateDef] = {
        # 基本关系
        "coll": PredicateDef("coll", 3, "共线: coll A B C 表示 A, B, C 三点共线", normalize_args=True),
        "para": PredicateDef("para", 4, "平行: para A B C D 表示 AB 平行于 CD"),
        "perp": PredicateDef("perp", 4, "垂直: perp A B C D 表示 AB 垂直于 CD"),
        "cong": PredicateDef("cong", 4, "全等: cong A B C D 表示 AB = CD"),
        "midp": PredicateDef("midp", 3, "中点: midp M A B 表示 M 是 AB 的中点"),
        "cyclic": PredicateDef("cyclic", 4, "共圆: cyclic A B C D 表示 A, B, C, D 四点共圆", normalize_args=True),
        "circle": PredicateDef("circle", 4, "圆: circle O A B C 表示 O 是过 A, B, C 的圆心"),

        # 角度关系
        "eqangle": PredicateDef("eqangle", 8, "等角: eqangle A B C D E F G H"),
        "eqangle6": PredicateDef("eqangle6", 8, "六点等角"),
        "eqangle3": PredicateDef("eqangle3", 6, "三点等角"),
        "eqangle2": PredicateDef("eqangle2", 4, "二点等角"),

        # 比例关系
        "eqratio": PredicateDef("eqratio", 8, "等比: eqratio A B C D E F G H"),
        "eqratio6": PredicateDef("eqratio6", 8, "六点等比"),
        "eqratio3": PredicateDef("eqratio3", 6, "三点等比"),

        # 否定关系
        "ncoll": PredicateDef("ncoll", -1, "不共线", normalize_args=True),
        "npara": PredicateDef("npara", 4, "不平行"),
        "nperp": PredicateDef("nperp", 4, "不垂直"),
        "diff": PredicateDef("diff", 2, "不同点"),

        # 特殊关系
        "sameside": PredicateDef("sameside", -1, "同侧"),
        "rconst": PredicateDef("rconst", 6, "比例常数"),

        # 三角形关系
        "contri": PredicateDef("contri", 6, "全等三角形"),
        "contri2": PredicateDef("contri2", 6, "全等三角形2"),
        "simtri": PredicateDef("simtri", 6, "相似三角形"),
        "simtri2": PredicateDef("simtri2", 6, "相似三角形2"),
        "contri*": PredicateDef("contri*", 6, "全等三角形*"),
        "simtri*": PredicateDef("simtri*", 6, "相似三角形*"),

        # 其他
        "collx": PredicateDef("collx", 4, "共线扩展"),
    }

    @classmethod
    def get_predicate_names(cls) -> List[str]:
        """获取所有谓词名称"""
        return list(cls.PREDICATES.keys())

    @classmethod
    def get_arity(cls, name: str) -> int:
        """获取谓词参数数量"""
        pred = cls.PREDICATES.get(name)
        return pred.arity if pred else -1

    @classmethod
    def is_supported(cls, name: str) -> bool:
        """检查谓词是否支持"""
        return name in cls.PREDICATES

    @classmethod
    def should_normalize_args(cls, name: str) -> bool:
        """检查谓词参数是否需要规范化排序"""
        pred = cls.PREDICATES.get(name)
        return pred.normalize_args if pred else False


class GeometryConstructions:
    """几何构造定义 - 单一数据源"""

    CONSTRUCTIONS: Dict[str, ConstructionDef] = {
        "triangle": ConstructionDef(
            "triangle", ["a", "b", "c"], [],
            "三角形ABC", [], []
        ),
        "midpoint": ConstructionDef(
            "midpoint", ["m", "a", "b"],
            ["midp m a b", "coll m a b", "cong m a m b"],
            "M是AB的中点", ["triangle"], [0, 1]
        ),
        "foot": ConstructionDef(
            "foot", ["x", "a", "b", "c"],
            ["perp x a b c", "coll x b c"],
            "X是A到BC的垂足", ["triangle"], [0, 1, 2]
        ),
        "orthocenter": ConstructionDef(
            "orthocenter", ["h", "a", "b", "c"],
            ["perp h a b c", "perp h b c a", "perp h c a b"],
            "H是三角形ABC的垂心", ["triangle"], [0, 1, 2]
        ),
        "circumcenter": ConstructionDef(
            "circumcenter", ["o", "a", "b", "c"],
            ["cong o a o b", "cong o b o c"],
            "O是三角形ABC的外心", ["triangle"], [0, 1, 2]
        ),
        "incenter": ConstructionDef(
            "incenter", ["i", "a", "b", "c"],
            ["eqangle a b a i a i a c", "eqangle c a c i c i c b", "eqangle b c b i b i b a"],
            "I是三角形ABC的内心", ["triangle"], [0, 1, 2]
        ),
        "centroid": ConstructionDef(
            "centroid", ["g", "a", "b", "c"], [],
            "G是三角形ABC的重心（需要中点构造）", ["triangle"], [0, 1, 2]
        ),
        "on_line": ConstructionDef(
            "on_line", ["x", "a", "b"],
            ["coll x a b"],
            "X在直线AB上", ["triangle"], [0, 1]
        ),
        "on_tline": ConstructionDef(
            "on_tline", ["x", "a", "b", "c"],
            ["perp x a b c"],
            "X在过A垂直于BC的直线上", ["triangle"], [0, 1, 2]
        ),
        "on_pline": ConstructionDef(
            "on_pline", ["x", "a", "b", "c"],
            ["para x a b c"],
            "X在过A平行于BC的直线上", ["triangle"], [0, 1, 2]
        ),
        "on_circle": ConstructionDef(
            "on_circle", ["x", "o", "a"],
            ["cong o x o a"],
            "X在以O为圆心过A的圆上", ["circumcenter"], []
        ),
        "on_circum": ConstructionDef(
            "on_circum", ["x", "a", "b", "c"],
            ["cyclic a b c x"],
            "X在三角形ABC的外接圆上", ["triangle"], [0, 1, 2]
        ),
        "intersection_ll": ConstructionDef(
            "intersection_ll", ["x", "a", "b", "c", "d"],
            ["coll x a b", "coll x c d"],
            "X是直线AB和CD的交点", ["triangle"], [0, 1, 1, 2]
        ),
        "angle_bisector": ConstructionDef(
            "angle_bisector", ["x", "a", "b", "c"],
            ["eqangle b a b x b x b c"],
            "AX是角BAC的角平分线", ["triangle"], [0, 1, 2]
        ),
        "free": ConstructionDef(
            "free", ["a"], [],
            "自由点A", [], []
        ),
        "segment": ConstructionDef(
            "segment", ["a", "b"], [],
            "线段AB", [], []
        ),
        "r_triangle": ConstructionDef(
            "r_triangle", ["a", "b", "c"],
            ["perp a b a c"],
            "直角三角形ABC（A为直角）", [], []
        ),
        "iso_triangle": ConstructionDef(
            "iso_triangle", ["a", "b", "c"],
            ["cong a b a c", "eqangle b a b c c b c a"],
            "等腰三角形ABC", [], []
        ),
        "parallelogram": ConstructionDef(
            "parallelogram", ["a", "b", "c", "d"],
            ["para a b c d", "para a d b c", "cong a b c d", "cong a d b c"],
            "平行四边形ABCD（对边平行且相等）", [], []
        ),
        "rectangle": ConstructionDef(
            "rectangle", ["a", "b", "c", "d"],
            ["perp a b b c", "para a b c d", "para a d b c", "cong a b c d", "cong a d b c", "cong a c b d"],
            "矩形ABCD", [], []
        ),
        "square": ConstructionDef(
            "square", ["a", "b", "c", "d"],
            ["perp a b b c", "cong a b b c", "para a b c d", "para a d b c", "cong b c c d", "cong c d d a", "cong a c b d"],
            "正方形ABCD", [], []
        ),
        "trapezoid": ConstructionDef(
            "trapezoid", ["a", "b", "c", "d"],
            ["para a b c d"],
            "梯形ABCD", [], []
        ),
    }

    @classmethod
    def get_construction_names(cls) -> List[str]:
        """获取所有构造名称"""
        return list(cls.CONSTRUCTIONS.keys())

    @classmethod
    def get_construction(cls, name: str) -> Optional[ConstructionDef]:
        """获取构造定义"""
        return cls.CONSTRUCTIONS.get(name)

    @classmethod
    def is_supported(cls, name: str) -> bool:
        """检查构造是否支持"""
        return name in cls.CONSTRUCTIONS

    @classmethod
    def get_constructions_with_predicates(cls) -> List[str]:
        """获取所有会产生谓词的构造名称"""
        return [name for name, defn in cls.CONSTRUCTIONS.items() if defn.predicates]


class GeometryRules:
    """几何演绎规则定义 - 单一数据源"""

    RULES: List[RuleDef] = [
        RuleDef("r01", ["perp A B C D", "perp C D E F", "ncoll A B E"], "para A B E F"),
        RuleDef("r02", ["cong O A O B", "cong O B O C", "cong O C O D"], "cyclic A B C D"),
        RuleDef("r03", ["eqangle A B P Q C D P Q"], "para A B C D"),
        RuleDef("r04", ["cyclic A B P Q"], "eqangle P A P B Q A Q B"),
        RuleDef("r05", ["eqangle6 P A P B Q A Q B", "ncoll P Q A B"], "cyclic A B P Q"),
        RuleDef("r06", ["cyclic A B C P Q R", "eqangle C A C B R P R Q"], "cong A B P Q"),
        RuleDef("r07", ["midp E A B", "midp F A C"], "para E F B C"),
        RuleDef("r08", ["para A B C D", "coll O A C", "coll O B D"], "eqratio3 A B C D O O"),
        RuleDef("r09", ["perp A B C D", "perp E F G H", "npara A B E F"], "eqangle A B E F C D G H"),
        RuleDef("r10", ["eqangle A B C D M N P Q", "eqangle C D E F P Q R U"], "eqangle A B E F M N R U"),
        RuleDef("r11", ["eqratio A B C D M N P Q", "eqratio C D E F P Q R U"], "eqratio A B E F M N R U"),
        RuleDef("r12", ["eqratio6 D B D C A B A C", "coll D B C", "ncoll A B C"], "eqangle6 A B A D A D A C"),
        RuleDef("r13", ["eqangle6 A B A D A D A C", "coll D B C", "ncoll A B C"], "eqratio6 D B D C A B A C"),
        RuleDef("r14", ["cong O A O B", "ncoll O A B"], "eqangle O A A B A B O B"),
        RuleDef("r15", ["eqangle6 A O A B B A B O", "ncoll O A B"], "cong O A O B"),
        RuleDef("r16", ["circle O A B C", "perp O A A X"], "eqangle A X A B C A C B"),
        RuleDef("r17", ["circle O A B C", "eqangle A X A B C A C B"], "perp O A A X"),
        RuleDef("r18", ["circle O A B C", "midp M B C"], "eqangle A B A C O B O M"),
        RuleDef("r19", ["circle O A B C", "coll M B C", "eqangle A B A C O B O M"], "midp M B C"),
        RuleDef("r20", ["perp A B B C", "midp M A C"], "cong A M B M"),
        RuleDef("r21", ["circle O A B C", "coll O A C"], "perp A B B C"),
        RuleDef("r22", ["cyclic A B C D", "para A B C D"], "eqangle A D C D C D C B"),
        RuleDef("r23", ["midp M A B", "perp O M A B"], "cong O A O B"),
        RuleDef("r24", ["cong A P B P", "cong A Q B Q"], "perp A B P Q"),
        RuleDef("r25", ["cong A P B P", "cong A Q B Q", "cyclic A B P Q"], "perp P A A Q"),
        RuleDef("r26", ["midp M A B", "midp M C D"], "para A C B D"),
        RuleDef("r27", ["midp M A B", "para A C B D", "para A D B C"], "midp M C D"),
        RuleDef("r28", ["eqratio O A A C O B B D", "coll O A C", "coll O B D", "ncoll A B C", "sameside A O C B O D"], "para A B C D"),
        RuleDef("r29", ["para A B A C"], "coll A B C"),
        RuleDef("r30", ["midp M A B", "midp N C D"], "eqratio M A A B N C C D"),
        RuleDef("r31", ["eqangle A B P Q C D U V", "perp P Q U V"], "perp A B C D"),
        RuleDef("r32", ["eqratio A B P Q C D U V", "cong P Q U V"], "cong A B C D"),
        RuleDef("r33", ["cong A B P Q", "cong B C Q R", "cong C A R P", "ncoll A B C"], "contri A B C P Q R"),
        RuleDef("r34", ["cong A B P Q", "cong B C Q R", "eqangle6 B A B C Q P Q R", "ncoll A B C"], "contri A B C P Q R"),
        RuleDef("r35", ["eqangle6 B A B C Q P Q R", "eqangle6 C A C B R P R Q", "ncoll A B C"], "simtri A B C P Q R"),
        RuleDef("r36", ["eqangle6 B A B C Q R Q P", "eqangle6 C A C B R Q R P", "ncoll A B C"], "simtri2 A B C P Q R"),
        RuleDef("r37", ["eqangle6 B A B C Q P Q R", "eqangle6 C A C B R P R Q", "ncoll A B C", "cong A B P Q"], "contri A B C P Q R"),
        RuleDef("r38", ["eqangle6 B A B C Q R Q P", "eqangle6 C A C B R Q R P", "ncoll A B C", "cong A B P Q"], "contri2 A B C P Q R"),
        RuleDef("r39", ["eqratio6 B A B C Q P Q R", "eqratio6 C A C B R P R Q", "ncoll A B C"], "simtri A B C P Q R"),
        RuleDef("r40", ["eqratio6 B A B C Q P Q R", "eqangle6 B A B C Q P Q R", "ncoll A B C"], "simtri A B C P Q R"),
        RuleDef("r41", ["eqratio6 B A B C Q P Q R", "eqratio6 C A C B R P R Q", "ncoll A B C", "cong A B P Q"], "contri A B C P Q R"),
        RuleDef("r42", ["para A B C D", "coll M A D", "coll N B C", "eqratio6 M A M D N B N C", "sameside M A D N B C"], "para M N A B"),
        RuleDef("r43", ["para A B C D", "coll M A D", "coll N B C", "para M N A B"], "eqratio6 M A M D N B N C"),
        RuleDef("r44", ["coll A B C", "coll A B D"], "coll A C D"),
        RuleDef("r45", ["coll A B C", "coll A B D"], "coll B C D"),
        RuleDef("r46", ["para A B C D", "para C D E F"], "para A B E F"),
        RuleDef("r47", ["perp A B C D", "perp C D E F"], "para A B E F"),
        RuleDef("r48", ["perp A B C D", "para C D E F"], "perp A B E F"),
        RuleDef("r49", ["cong A B C D", "cong C D E F"], "cong A B E F"),
        RuleDef("r50", ["midp M A B", "midp M C D"], "cong A C B D"),
        RuleDef("r51", ["cyclic A B C D", "cyclic A B C E"], "cyclic A B D E"),
        RuleDef("r52", ["eqangle A B C D E F G H", "eqangle E F G H I J K L"], "eqangle A B C D I J K L"),
        RuleDef("r53", ["eqratio A B C D E F G H", "eqratio E F G H I J K L"], "eqratio A B C D I J K L"),
        RuleDef("r54", ["para A B C D", "para A B E F"], "para C D E F"),
        RuleDef("r55", ["cong A B C D", "cong A B E F"], "cong C D E F"),
        RuleDef("r56", ["midp M A B"], "coll M A B"),
        RuleDef("r57", ["midp M A B"], "cong M A M B"),
        RuleDef("r58", ["perp A B C D", "perp A B E F"], "para C D E F"),
        RuleDef("r59", ["cyclic A B C D"], "cyclic B C D A"),
        RuleDef("r60", ["cyclic A B C D"], "cyclic A C D B"),
        RuleDef("r61", ["coll A B C", "coll A B D"], "coll C D A"),
        RuleDef("r62", ["coll A B C", "coll D E F"], "ncoll A B D"),
        RuleDef("r63", ["para A B C D"], "para B A D C"),
        RuleDef("r64", ["perp A B C D"], "perp B A D C"),
        RuleDef("r65", ["cong A B C D"], "cong B A D C"),
        RuleDef("r66", ["cong A B C D"], "cong C D A B"),
        RuleDef("r67", ["para A B C D"], "para C D A B"),
        RuleDef("r68", ["perp A B C D"], "perp C D A B"),
        RuleDef("r69", ["cong O A O B", "cong O A O C"], "cong O B O C"),
        RuleDef("r70", ["cong O A O B"], "cong O B O A"),
        RuleDef("r71", ["coll A B C"], "coll B A C"),
        RuleDef("r72", ["coll A B C"], "coll A C B"),
        RuleDef("r73", ["coll A B C"], "coll C B A"),
        RuleDef("r74", ["para A B C D"], "para A B D C"),
        RuleDef("r75", ["para A B C D"], "para B A C D"),
        RuleDef("r76", ["cyclic A B C D"], "cyclic A B D C"),
        RuleDef("r77", ["cyclic A B C D"], "cyclic D A B C"),
        RuleDef("r78", ["midp M A B"], "midp M B A"),
        RuleDef("r79", ["perp A B C D"], "perp A B D C"),
        RuleDef("r80", ["perp A B C D"], "perp B A C D"),
    ]

    @classmethod
    def get_rule_names(cls) -> List[str]:
        """获取所有规则名称"""
        return [r.name for r in cls.RULES]

    @classmethod
    def get_rules_dict(cls) -> Dict[str, Dict[str, Any]]:
        """获取规则字典格式（兼容旧代码）"""
        return {
            r.name: {
                "name": r.name,
                "premises": r.premises,
                "conclusion": r.conclusion,
            }
            for r in cls.RULES
        }

    @classmethod
    def get_rules_dict_list(cls) -> List[Dict[str, Any]]:
        """获取规则列表格式（兼容旧代码）"""
        return [
            {
                "name": r.name,
                "premises": r.premises,
                "conclusion": r.conclusion,
            }
            for r in cls.RULES
        ]


class GeometryKeywords:
    """几何关键词 - 用于分词器等"""

    POINTS_LOWER = list("abcdefghijklmnopqrstuvwxyz")
    POINTS_UPPER = list("ABCDEFGHIJKLMNOPQRSTUVWXYZ")
    DIGITS = list("0123456789")

    PREDICATES = GeometryPredicates.get_predicate_names()
    CONSTRUCTIONS = GeometryConstructions.get_construction_names()

    SPECIAL = ["pi", "perp", "para", "cong", "coll", "cyclic", "midp"]

    @classmethod
    def get_all_keywords(cls) -> List[str]:
        """获取所有关键词"""
        return (
            cls.POINTS_LOWER +
            cls.POINTS_UPPER +
            cls.DIGITS +
            cls.PREDICATES +
            cls.CONSTRUCTIONS +
            cls.SPECIAL
        )


# 兼容旧代码的别名
GeometryDefinitions = GeometryConstructions
DeductionRules = GeometryRules
