# GENERATED BY AI
"""
几何语法解析器 - 统一解析 AlphaGeometry 格式的几何命题和构造
"""

from typing import List, Dict, Tuple, Optional
from dataclasses import dataclass
import re

try:
    from .geometry_definitions import (
        GeometryPredicates,
        GeometryConstructions,
    )
except ImportError:
    from geometry_definitions import (
        GeometryPredicates,
        GeometryConstructions,
    )


@dataclass
class Proposition:
    """几何命题"""

    predicate: str  # 谓词名称
    args: Tuple[str, ...]  # 参数列表(点、线、圆等)

    def __str__(self):
        return f"{self.predicate} {' '.join(self.args)}"

    def __repr__(self):
        return f"Proposition({self.predicate}, {self.args})"

    def __hash__(self):
        return hash((self.predicate, self.args))

    def __eq__(self, other):
        if not isinstance(other, Proposition):
            return False
        return self.predicate == other.predicate and self.args == other.args

    @classmethod
    def from_string(cls, text: str) -> "Proposition":
        """从字符串创建命题对象"""
        return GeometryParser.parse_proposition(text)


@dataclass
class Construction:
    """几何构造"""

    name: str  # 构造名称
    output_points: Tuple[str, ...]  # 输出点
    input_points: Tuple[str, ...]  # 输入点
    conditions: List[Proposition]  # 构造条件

    def __str__(self):
        return f"{self.name} {' '.join(self.output_points)} = {' '.join(self.input_points)}"

    def __repr__(self):
        return f"Construction({self.name}, {self.output_points}, {self.input_points})"


@dataclass
class Problem:
    """几何问题"""

    constructions: List[Construction]  # 构造列表
    goal: Proposition  # 目标命题

    def __str__(self):
        const_str = "; ".join(str(c) for c in self.constructions)
        return f"{const_str} ? {self.goal}"


class GeometryParser:
    """几何语法解析器"""

    # 支持的谓词列表 - 从统一数据源获取
    SUPPORTED_PREDICATES = GeometryPredicates.get_predicate_names()

    # 谓词参数数量映射 - 从统一数据源获取
    PREDICATE_ARITIES = {
        name: pred.arity for name, pred in GeometryPredicates.PREDICATES.items()
    }

    # 支持的构造列表 - 从统一数据源获取
    SUPPORTED_CONSTRUCTIONS = GeometryConstructions.get_construction_names()

    @staticmethod
    def parse_proposition(text: str) -> Proposition:
        """解析命题文本

        Args:
            text: 命题文本,如 "perp A B C D"

        Returns:
            Proposition 对象
        """
        parts = text.strip().split()
        if not parts:
            raise ValueError(f"空命题: {text}")

        predicate = parts[0]
        args = tuple(parts[1:])

        if predicate not in GeometryParser.SUPPORTED_PREDICATES:
            raise ValueError(f"不支持的谓词: {predicate}")

        expected_arity = GeometryParser.PREDICATE_ARITIES.get(predicate)
        if expected_arity is not None:
            if isinstance(expected_arity, list):
                if len(args) not in expected_arity:
                    raise ValueError(
                        f"谓词 {predicate} 需要 {expected_arity} 中的一个参数数量,但得到 {len(args)} 个"
                    )
            elif len(args) != expected_arity:
                raise ValueError(
                    f"谓词 {predicate} 需要 {expected_arity} 个参数,但得到 {len(args)} 个"
                )

        return Proposition(predicate=predicate, args=args)

    @staticmethod
    def parse_construction(text: str) -> Construction:
        """解析构造文本

        Args:
            text: 构造文本,如 "a b c = triangle" 或 "h = on_tline b a c"

        Returns:
            Construction 对象
        """
        # 移除注释和多余空格
        text = text.strip()

        # 匹配模式: output = construction inputs
        match = re.match(r"^(.+?)\s*=\s*(.+)$", text)
        if not match:
            raise ValueError(f"无效的构造格式: {text}")

        output_str, input_str = match.groups()
        output_parts = output_str.strip().split()

        # 解析输入
        input_parts = input_str.strip().split()
        if not input_parts:
            raise ValueError(f"构造缺少名称: {text}")

        construction_name = input_parts[0]
        input_points = tuple(input_parts[1:])
        output_points = tuple(output_parts)

        if construction_name not in GeometryParser.SUPPORTED_CONSTRUCTIONS:
            raise ValueError(f"不支持的构造: {construction_name}")

        return Construction(
            name=construction_name,
            output_points=output_points,
            input_points=input_points,
            conditions=[],  # 条件需要从 defs.txt 中加载
        )

    @staticmethod
    def parse_problem(text: str) -> Problem:
        """解析完整的问题文本

        Args:
            text: 问题文本,如 "a b c = triangle; h = on_tline b a c ? perp a h b c"

        Returns:
            Problem 对象
        """
        # 分割构造和目标
        parts = text.split("?")
        if len(parts) != 2:
            raise ValueError(f"无效的问题格式,缺少 '?': {text}")

        constructions_str, goal_str = parts

        # 解析构造
        constructions = []
        if constructions_str.strip():
            for const_str in constructions_str.split(";"):
                const_str = const_str.strip()
                if const_str:
                    constructions.append(GeometryParser.parse_construction(const_str))

        # 解析目标
        goal = GeometryParser.parse_proposition(goal_str.strip())

        return Problem(constructions=constructions, goal=goal)

    @staticmethod
    def parse_proposition_list(text: str) -> List[Proposition]:
        """解析命题列表

        Args:
            text: 命题列表文本,用逗号分隔,如 "coll A B C, perp A B C D"

        Returns:
            Proposition 列表
        """
        propositions = []
        for prop_str in text.split(","):
            prop_str = prop_str.strip()
            if prop_str:
                propositions.append(GeometryParser.parse_proposition(prop_str))
        return propositions

    @staticmethod
    def proposition_to_string(prop: Proposition) -> str:
        """将命题转换为字符串"""
        return str(prop)

    @staticmethod
    def construction_to_string(const: Construction) -> str:
        """将构造转换为字符串"""
        output_str = " ".join(const.output_points)
        input_str = " ".join(const.input_points)
        return f"{output_str} = {const.name} {input_str}"

    @staticmethod
    def problem_to_string(problem: Problem) -> str:
        """将问题转换为字符串"""
        const_str = "; ".join(
            GeometryParser.construction_to_string(c) for c in problem.constructions
        )
        return f"{const_str} ? {GeometryParser.proposition_to_string(problem.goal)}"

    @staticmethod
    def load_rules_from_file(filepath: str) -> List[Dict]:
        """从 rules.txt 文件加载演绎规则

        Args:
            filepath: rules.txt 文件路径

        Returns:
            规则字典列表,每个规则包含 premises 和 conclusions
        """
        rules = []
        with open(filepath, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith("#"):
                    continue

                # 解析规则: premises => conclusions
                if "=>" in line:
                    parts = line.split("=>")
                    premises_str = parts[0].strip()
                    conclusions_str = parts[1].strip()

                    premises = GeometryParser.parse_proposition_list(premises_str)
                    conclusions = GeometryParser.parse_proposition_list(conclusions_str)

                    rules.append({"premises": premises, "conclusions": conclusions})

        return rules

    @staticmethod
    def load_constructions_from_file(filepath: str) -> Dict[str, List[Proposition]]:
        """从 defs.txt 文件加载构造定义

        Args:
            filepath: defs.txt 文件路径

        Returns:
            构造名称到条件列表的映射
        """
        construction_defs = {}
        current_construction = None
        current_conditions: List[Proposition] = []

        with open(filepath, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith("#"):
                    continue

                # 构造定义行
                if line and not line.startswith(" ") and not line.startswith("\t"):
                    # 保存上一个构造
                    if current_construction:
                        construction_defs[current_construction] = current_conditions

                    # 解析新构造名称
                    parts = line.split()
                    if len(parts) >= 1:
                        current_construction = parts[0]
                        current_conditions = []

                # 条件行
                elif line.startswith(" ") or line.startswith("\t"):
                    # 检查是否是命题
                    if ":" in line:
                        # 跳过变量定义行
                        continue
                    # 尝试解析为命题
                    try:
                        prop = GeometryParser.parse_proposition(line)
                        current_conditions.append(prop)
                    except ValueError:
                        # 跳过无法解析的行
                        pass

        # 保存最后一个构造
        if current_construction:
            construction_defs[current_construction] = current_conditions

        return construction_defs

    @staticmethod
    def get_predicate_info(predicate: str) -> Dict:
        """获取谓词信息

        Args:
            predicate: 谓词名称

        Returns:
            谓词信息字典
        """
        return {
            "name": predicate,
            "arity": GeometryParser.PREDICATE_ARITIES.get(predicate),
            "supported": predicate in GeometryParser.SUPPORTED_PREDICATES,
        }

    @staticmethod
    def get_construction_info(construction: str) -> Dict:
        """获取构造信息

        Args:
            construction: 构造名称

        Returns:
            构造信息字典
        """
        return {
            "name": construction,
            "supported": construction in GeometryParser.SUPPORTED_CONSTRUCTIONS,
        }

    @staticmethod
    def validate_proposition(prop: Proposition) -> Tuple[bool, Optional[str]]:
        """验证命题是否有效

        Args:
            prop: 命题对象

        Returns:
            (是否有效, 错误信息)
        """
        if prop.predicate not in GeometryParser.SUPPORTED_PREDICATES:
            return False, f"不支持的谓词: {prop.predicate}"

        expected_arity = GeometryParser.PREDICATE_ARITIES.get(prop.predicate)
        if expected_arity is not None:
            if isinstance(expected_arity, list):
                if len(prop.args) not in expected_arity:
                    return (
                        False,
                        f"谓词 {prop.predicate} 需要 {expected_arity} 中的一个参数数量,但得到 {len(prop.args)} 个",
                    )
            elif len(prop.args) != expected_arity:
                return (
                    False,
                    f"谓词 {prop.predicate} 需要 {expected_arity} 个参数,但得到 {len(prop.args)} 个",
                )

        return True, None

    @staticmethod
    def validate_construction(const: Construction) -> Tuple[bool, Optional[str]]:
        """验证构造是否有效

        Args:
            const: 构造对象

        Returns:
            (是否有效, 错误信息)
        """
        if const.name not in GeometryParser.SUPPORTED_CONSTRUCTIONS:
            return False, f"不支持的构造: {const.name}"

        return True, None
