# GENERATED BY AI
"""集成工作流，使用新的解析器和扩展引擎。"""

import torch
from torch import nn
from typing import Optional, List, Tuple, Dict
from dataclasses import dataclass

try:
    from .config import SystemConfig, get_default_config
    from .event_system import Event, EventSequence
    from .tokenizer import GeometryTokenizer
    from .models import Encoder, Decoder, ReasoningAI
    from .extended_render_engine import ExtendedRenderEngine
    from .extended_symbolic_engine import ExtendedSymbolicEngine
    from .geometry_parser import GeometryParser, Proposition, Problem
    from .proposition_manager import PropositionManager
except ImportError:
    from config import SystemConfig, get_default_config
    from event_system import Event, EventSequence
    from tokenizer import GeometryTokenizer
    from models import Encoder, Decoder, ReasoningAI
    from extended_render_engine import ExtendedRenderEngine
    from extended_symbolic_engine import ExtendedSymbolicEngine
    from geometry_parser import GeometryParser, Proposition, Problem
    from proposition_manager import PropositionManager


@dataclass
class ReasoningStep:
    """推理步骤。"""
    event_vector: torch.Tensor
    control_signal: torch.Tensor
    decoded_statement: Optional[str] = None
    symbolic_valid: Optional[bool] = None
    render_valid: Optional[bool] = None


class IntegratedGeometrySystem:
    """集成的几何推理系统。"""

    def __init__(self, config: Optional[SystemConfig] = None):
        self.config = config if config is not None else get_default_config()

        # 初始化组件
        self.tokenizer = GeometryTokenizer(vocab_size=self.config.encoder.vocab_size)
        self.parser = GeometryParser()
        self.render_engine = ExtendedRenderEngine()
        self.symbolic_engine = ExtendedSymbolicEngine()
        self.prop_manager = PropositionManager()

        # 初始化模型
        self.encoder = Encoder(
            vocab_size=self.config.encoder.vocab_size,
            embed_dim=self.config.encoder.embed_dim,
            num_heads=self.config.encoder.num_heads,
            num_layers=self.config.encoder.num_layers,
            ffn_dim=self.config.encoder.ffn_dim,
            max_seq_len=self.config.encoder.max_seq_len,
            dropout=self.config.encoder.dropout,
        )

        self.decoder = Decoder(
            vocab_size=self.config.decoder.vocab_size,
            embed_dim=self.config.decoder.embed_dim,
            num_heads=self.config.decoder.num_heads,
            num_layers=self.config.decoder.num_layers,
            ffn_dim=self.config.decoder.ffn_dim,
            max_seq_len=self.config.decoder.max_seq_len,
            dropout=self.config.decoder.dropout,
        )

        self.reasoning_ai = ReasoningAI(
            embed_dim=self.config.reasoning_ai.embed_dim,
            num_heads=self.config.reasoning_ai.num_heads,
            num_layers=self.config.reasoning_ai.num_layers,
            ffn_dim=self.config.reasoning_ai.ffn_dim,
            max_seq_len=self.config.reasoning_ai.max_seq_len,
            control_dim=self.config.reasoning_ai.control_dim,
            dropout=self.config.reasoning_ai.dropout,
        )

    def count_parameters(self) -> Dict[str, int]:
        """计算模型参数量。"""
        encoder_params = sum(p.numel() for p in self.encoder.parameters())
        decoder_params = sum(p.numel() for p in self.decoder.parameters())
        reasoning_ai_params = sum(p.numel() for p in self.reasoning_ai.parameters())

        return {
            "encoder": encoder_params,
            "decoder": decoder_params,
            "reasoning_ai": reasoning_ai_params,
            "total": encoder_params + decoder_params + reasoning_ai_params,
        }

    def encode_proposition(self, proposition: str) -> torch.Tensor:
        """编码几何命题为事件向量。"""
        # 使用分词器
        tokens = self.tokenizer.encode(proposition)

        # 转换为张量
        token_tensor = torch.tensor([tokens], dtype=torch.long)

        # 编码
        with torch.no_grad():
            event_vector = self.encoder(token_tensor)

        return event_vector.squeeze(0)

    def decode_event(self, event_vector: torch.Tensor) -> str:
        """解码事件向量为命题。"""
        # 添加批次维度
        event_vector = event_vector.unsqueeze(0)

        # 解码
        with torch.no_grad():
            output = self.decoder(event_vector)

        # 转换为 token
        tokens = output.argmax(dim=-1).squeeze(0).tolist()

        # 解码为文本
        return self.tokenizer.decode(tokens)

    def parse_problem(self, problem_text: str) -> Optional[Problem]:
        """解析问题。"""
        return self.parser.parse_problem(problem_text)

    def parse_premises(self, premises_text: str) -> List[Proposition]:
        """解析前提。"""
        return self.parser.parse_premises(premises_text)

    def verify_symbolic(self, proposition: str) -> bool:
        """使用符号引擎验证命题。"""
        # 添加命题到符号引擎
        self.symbolic_engine.add_statement(proposition)

        # 尝试推导
        self.symbolic_engine.deduce(max_steps=10)

        # 检查是否可验证
        return self.symbolic_engine.verify(proposition)

    def verify_render(self, proposition: str) -> bool:
        """使用渲染引擎验证命题。"""
        # 解析命题
        prop = self.parser.parse_proposition(proposition)
        if prop is None:
            return False

        # 获取点
        point_names = list(prop.args)
        points = self.render_engine._get_points(point_names)

        # 验证
        return self.render_engine.verify_proposition(prop.predicate, points)

    def solve_problem(
        self,
        problem: Problem,
        max_steps: int = 100
    ) -> Tuple[bool, List[ReasoningStep]]:
        """解决问题。"""
        # 重置引擎
        self.symbolic_engine.reset()
        self.render_engine.reset()
        self.prop_manager.clear()

        # 添加前提
        for clause in problem.premises:
            for cons in clause.constructions:
                stmt = f"{cons.predicate} {' '.join(cons.args)}"
                self.symbolic_engine.add_statement(stmt)
                self.prop_manager.add_symbolic(stmt, True)

        # 推理步骤
        reasoning_steps: List[ReasoningStep] = []

        for step in range(max_steps):
            # 检查是否达到目标
            if problem.goal:
                goal_str = str(problem.goal)
                if self.symbolic_engine.verify(goal_str):
                    return True, reasoning_steps

            # 生成新事件（这里简化处理，实际应该使用 reasoning_ai）
            # 对于演示，我们使用符号引擎的推导
            new_statements = self.symbolic_engine.apply_rules()

            if not new_statements:
                break

            # 处理新命题
            for stmt in new_statements:
                stmt_str = str(stmt)

                # 编码
                event_vector = self.encode_proposition(stmt_str)

                # 验证
                symbolic_valid = self.verify_symbolic(stmt_str)
                render_valid = self.verify_render(stmt_str)

                # 添加到命题管理器
                if symbolic_valid:
                    self.prop_manager.add_symbolic(stmt_str, True)
                if render_valid:
                    self.prop_manager.add_rendered(stmt_str, True)

                # 创建推理步骤
                step_obj = ReasoningStep(
                    event_vector=event_vector,
                    control_signal=torch.tensor([0.0, 0.0]),
                    decoded_statement=stmt_str,
                    symbolic_valid=symbolic_valid,
                    render_valid=render_valid,
                )
                reasoning_steps.append(step_obj)

        # 检查最终目标
        if problem.goal:
            goal_str = str(problem.goal)
            return self.symbolic_engine.verify(goal_str), reasoning_steps

        return False, reasoning_steps

    def get_proof(self, reasoning_steps: List[ReasoningStep]) -> str:
        """获取证明过程。"""
        lines = ["证明过程:"]
        for i, step in enumerate(reasoning_steps, 1):
            if step.decoded_statement:
                status = "✓" if step.symbolic_valid else "✗"
                lines.append(f"{i}. {step.decoded_statement} {status}")
        return '\n'.join(lines)


if __name__ == "__main__":
    system = IntegratedGeometrySystem()

    # 打印参数信息
    params = system.count_parameters()
    print("模型参数:")
    print(f"  编码器: {params['encoder']:,}")
    print(f"  解码器: {params['decoder']:,}")
    print(f"  推理AI: {params['reasoning_ai']:,}")
    print(f"  总计: {params['total']:,}")
    print(f"  小于0.05M: {params['total'] < 50000}\n")

    # 测试解析
    print("=== 测试解析 ===")
    problem_text = """orthocenter
a b c = triangle
h = on_tline h b a c, on_tline h c a b ? perp a h b c"""

    problem = system.parse_problem(problem_text)
    print(f"问题名称: {problem.name}")
    print(f"目标: {problem.goal}")
    print(f"前提数量: {len(problem.premises)}\n")

    # 测试编码和解码
    print("=== 测试编码和解码 ===")
    proposition = "perp A B C D"
    print(f"原始命题: {proposition}")

    event_vector = system.encode_proposition(proposition)
    print(f"事件向量形状: {event_vector.shape}")

    decoded = system.decode_event(event_vector)
    print(f"解码命题: {decoded}\n")

    # 测试符号验证
    print("=== 测试符号验证 ===")
    system.symbolic_engine.reset()
    system.symbolic_engine.add_statement("perp A B C D")
    system.symbolic_engine.add_statement("perp E F C D")

    result = system.verify_symbolic("para A B E F")
    print(f"符号验证 'para A B E F': {result}\n")

    # 测试渲染验证
    print("=== 测试渲染验证 ===")
    system.render_engine.reset()
    system.render_engine.points = {
        "A": system.render_engine.Point(0, 0),
        "B": system.render_engine.Point(1, 0),
        "C": system.render_engine.Point(0, 1),
        "D": system.render_engine.Point(1, 1),
    }

    result = system.verify_render("perp A B C D")
    print(f"渲染验证 'perp A B C D': {result}")

    result = system.verify_render("para A B C D")
    print(f"渲染验证 'para A B C D': {result}\n")

    # 测试解决问题
    print("=== 测试解决问题 ===")
    solved, steps = system.solve_problem(problem, max_steps=10)
    print(f"是否解决: {solved}")
    print(f"推理步骤数: {len(steps)}")

    if steps:
        print("\n" + system.get_proof(steps))