# GENERATED BY AI
"""几何题推理AI的Transformer模型。

包含编码器、解码器和推理AI三个核心组件。
统一使用可学习的位置编码实现。
"""

import math
from typing import Optional

import torch
import torch.nn.functional as F
from torch import nn


class PositionalEncoding(nn.Module):
    """统一的位置编码模块（可学习方式）"""

    def __init__(self, embed_dim: int, max_seq_len: int = 128):
        super().__init__()
        self.pos_encoding = nn.Parameter(torch.randn(1, max_seq_len, embed_dim) * 0.02)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        seq_len = x.size(1)
        return x + self.pos_encoding[:, :seq_len, :]


class MultiHeadAttention(nn.Module):
    def __init__(self, embed_dim: int, num_heads: int, dropout: float = 0.1):
        super().__init__()
        self.embed_dim = embed_dim
        self.num_heads = num_heads
        self.head_dim = embed_dim // num_heads

        assert embed_dim % num_heads == 0, "embed_dim必须能被num_heads整除"

        self.q_proj = nn.Linear(embed_dim, embed_dim)
        self.k_proj = nn.Linear(embed_dim, embed_dim)
        self.v_proj = nn.Linear(embed_dim, embed_dim)
        self.out_proj = nn.Linear(embed_dim, embed_dim)
        self.dropout = nn.Dropout(dropout)

    def forward(self, query, key, value, mask=None):
        batch_size = query.size(0)

        q = (
            self.q_proj(query)
            .view(batch_size, -1, self.num_heads, self.head_dim)
            .transpose(1, 2)
        )
        k = (
            self.k_proj(key)
            .view(batch_size, -1, self.num_heads, self.head_dim)
            .transpose(1, 2)
        )
        v = (
            self.v_proj(value)
            .view(batch_size, -1, self.num_heads, self.head_dim)
            .transpose(1, 2)
        )

        scores = torch.matmul(q, k.transpose(-2, -1)) / math.sqrt(self.head_dim)

        if mask is not None:
            scores = scores.masked_fill(mask.bool(), float("-inf"))

        attn = F.softmax(scores, dim=-1)
        attn = self.dropout(attn)

        out = torch.matmul(attn, v)
        out = out.transpose(1, 2).contiguous().view(batch_size, -1, self.embed_dim)

        return self.out_proj(out)


class FeedForward(nn.Module):
    def __init__(self, embed_dim: int, ffn_dim: int, dropout: float = 0.1):
        super().__init__()
        self.fc1 = nn.Linear(embed_dim, ffn_dim)
        self.fc2 = nn.Linear(ffn_dim, embed_dim)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):  # pylint: disable=no-member,not-callable
        x = torch.nn.functional.gelu(self.fc1(x))
        x = self.dropout(x)
        x = self.fc2(x)
        return x


class TransformerEncoderLayer(nn.Module):
    def __init__(
        self, embed_dim: int, num_heads: int, ffn_dim: int, dropout: float = 0.1
    ):
        super().__init__()
        self.self_attn = MultiHeadAttention(embed_dim, num_heads, dropout)
        self.ffn = FeedForward(embed_dim, ffn_dim, dropout)
        self.norm1 = nn.LayerNorm(embed_dim)
        self.norm2 = nn.LayerNorm(embed_dim)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x, mask=None):
        attn_out = self.self_attn(x, x, x, mask)
        x = self.norm1(x + self.dropout(attn_out))
        ffn_out = self.ffn(x)
        x = self.norm2(x + self.dropout(ffn_out))
        return x


class TransformerDecoderLayer(nn.Module):
    def __init__(
        self, embed_dim: int, num_heads: int, ffn_dim: int, dropout: float = 0.1
    ):
        super().__init__()
        self.self_attn = MultiHeadAttention(embed_dim, num_heads, dropout)
        self.cross_attn = MultiHeadAttention(embed_dim, num_heads, dropout)
        self.ffn = FeedForward(embed_dim, ffn_dim, dropout)
        self.norm1 = nn.LayerNorm(embed_dim)
        self.norm2 = nn.LayerNorm(embed_dim)
        self.norm3 = nn.LayerNorm(embed_dim)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x, memory, tgt_mask=None, memory_mask=None):
        self_attn_out = self.self_attn(x, x, x, tgt_mask)
        x = self.norm1(x + self.dropout(self_attn_out))

        cross_attn_out = self.cross_attn(x, memory, memory, memory_mask)
        x = self.norm2(x + self.dropout(cross_attn_out))

        ffn_out = self.ffn(x)
        x = self.norm3(x + self.dropout(ffn_out))
        return x


class Encoder(nn.Module):
    def __init__(  # pylint: disable=too-many-arguments,too-many-positional-arguments
        self,
        vocab_size: int,
        embed_dim: int,
        num_heads: int,
        num_layers: int,
        ffn_dim: int,
        max_seq_len: int = 128,
        dropout: float = 0.1,
    ):
        super().__init__()
        self.embedding = nn.Embedding(vocab_size, embed_dim)
        self.pos_encoding = PositionalEncoding(embed_dim, max_seq_len)

        self.layers = nn.ModuleList(
            [
                TransformerEncoderLayer(embed_dim, num_heads, ffn_dim, dropout)
                for _ in range(num_layers)
            ]
        )

        self.norm = nn.LayerNorm(embed_dim)
        self.output_proj = nn.Linear(embed_dim, embed_dim)

    def forward(
        self, x: torch.Tensor, mask: Optional[torch.Tensor] = None
    ) -> torch.Tensor:
        x = self.embedding(x)
        x = self.pos_encoding(x)

        for layer in self.layers:
            x = layer(x, mask)

        x = self.norm(x)
        x = x.mean(dim=1)
        x = self.output_proj(x)

        return x


class Decoder(nn.Module):
    def __init__(  # pylint: disable=too-many-arguments,too-many-positional-arguments
        self,
        vocab_size: int,
        embed_dim: int,
        num_heads: int,
        num_layers: int,
        ffn_dim: int,
        max_seq_len: int = 128,
        dropout: float = 0.1,
    ):
        super().__init__()
        self.embedding = nn.Embedding(vocab_size, embed_dim)
        self.pos_encoding = PositionalEncoding(embed_dim, max_seq_len)

        self.layers = nn.ModuleList(
            [
                TransformerDecoderLayer(embed_dim, num_heads, ffn_dim, dropout)
                for _ in range(num_layers)
            ]
        )

        self.norm = nn.LayerNorm(embed_dim)
        self.output_proj = nn.Linear(embed_dim, vocab_size)

    def forward(
        self,
        x: torch.Tensor,
        memory: torch.Tensor,
        tgt_mask: Optional[torch.Tensor] = None,
        memory_mask: Optional[torch.Tensor] = None,
    ) -> torch.Tensor:
        x = self.embedding(x)
        x = self.pos_encoding(x)

        if tgt_mask is None:
            tgt_mask = self._generate_causal_mask(x.size(1), x.device)

        for layer in self.layers:
            x = layer(x, memory, tgt_mask, memory_mask)

        x = self.norm(x)
        logits = self.output_proj(x)

        return logits

    def _generate_causal_mask(self, seq_len: int, device: torch.device) -> torch.Tensor:
        mask = torch.triu(torch.ones(seq_len, seq_len, device=device), diagonal=1)
        return mask.unsqueeze(0).unsqueeze(0)

    def generate(
        self,
        memory: torch.Tensor,
        bos_id: int,
        eos_id: int,
        max_len: int = 64,
    ) -> torch.Tensor:
        batch_size = memory.size(0)
        generated = torch.full(
            (batch_size, 1), bos_id, dtype=torch.long, device=memory.device
        )

        for _ in range(max_len - 1):
            logits = self.forward(generated, memory)
            next_token = logits[:, -1, :].argmax(dim=-1, keepdim=True)
            generated = torch.cat([generated, next_token], dim=1)

            if (next_token == eos_id).all():
                break

        return generated


class ReasoningAI(nn.Module):
    def __init__(  # pylint: disable=too-many-arguments,too-many-positional-arguments
        self,
        embed_dim: int,
        num_heads: int,
        num_layers: int,
        ffn_dim: int,
        control_dim: int = 2,
        max_seq_len: int = 128,
        dropout: float = 0.1,
    ):
        super().__init__()

        self.pos_encoding = PositionalEncoding(embed_dim, max_seq_len)

        self.layers = nn.ModuleList(
            [
                TransformerEncoderLayer(embed_dim, num_heads, ffn_dim, dropout)
                for _ in range(num_layers)
            ]
        )

        self.norm = nn.LayerNorm(embed_dim)
        self.event_proj = nn.Linear(embed_dim, embed_dim)
        self.control_proj = nn.Linear(embed_dim, control_dim)

    def forward(
        self, event_sequence: torch.Tensor, mask: Optional[torch.Tensor] = None
    ) -> tuple[torch.Tensor, torch.Tensor]:
        x = self.pos_encoding(event_sequence)

        for layer in self.layers:
            x = layer(x, mask)

        x = self.norm(x)

        last_hidden = x[:, -1, :]
        event_vector = self.event_proj(last_hidden)
        control_signal = torch.sigmoid(self.control_proj(last_hidden))

        return event_vector, control_signal


def count_parameters(model: nn.Module) -> int:
    return sum(p.numel() for p in model.parameters() if p.requires_grad)


if __name__ == "__main__":
    try:
        from .config import EncoderConfig, DecoderConfig, ReasoningAIConfig
    except ImportError:
        from config import EncoderConfig, DecoderConfig, ReasoningAIConfig

    enc_config = EncoderConfig()
    encoder = Encoder(
        vocab_size=enc_config.vocab_size,
        embed_dim=enc_config.embed_dim,
        num_heads=enc_config.num_heads,
        num_layers=enc_config.num_layers,
        ffn_dim=enc_config.ffn_dim,
        max_seq_len=enc_config.max_seq_len,
    )

    dec_config = DecoderConfig()
    decoder = Decoder(
        vocab_size=dec_config.vocab_size,
        embed_dim=dec_config.embed_dim,
        num_heads=dec_config.num_heads,
        num_layers=dec_config.num_layers,
        ffn_dim=dec_config.ffn_dim,
        max_seq_len=dec_config.max_seq_len,
    )

    rai_config = ReasoningAIConfig()
    reasoning_ai = ReasoningAI(
        embed_dim=rai_config.embed_dim,
        num_heads=rai_config.num_heads,
        num_layers=rai_config.num_layers,
        ffn_dim=rai_config.ffn_dim,
        control_dim=rai_config.control_dim,
        max_seq_len=rai_config.max_seq_len,
    )

    total_params = (
        count_parameters(encoder)
        + count_parameters(decoder)
        + count_parameters(reasoning_ai)
    )
    print(f"编码器参数量: {count_parameters(encoder):,}")
    print(f"解码器参数量: {count_parameters(decoder):,}")
    print(f"推理AI参数量: {count_parameters(reasoning_ai):,}")
    print(f"总参数量: {total_params:,}")
