# GENERATED BY GLM
"""几何题推理AI的命题列表管理。"""

from typing import List, Optional, Dict, Any, Set
from dataclasses import dataclass, field
from datetime import datetime

from .geometry_parser import Proposition


@dataclass
class PropositionRecord:
    statement: str
    is_valid: bool
    source: str
    timestamp: datetime = field(default_factory=datetime.now)
    metadata: Dict[str, Any] = field(default_factory=dict)

    def __str__(self):
        status = "✓" if self.is_valid else "✗"
        return f"[{status}] {self.statement} (from {self.source})"


class PropositionList:
    def __init__(self, name: str):
        self.name = name
        self.propositions: List[PropositionRecord] = []

    def add(
        self,
        statement: str,
        is_valid: bool,
        source: str,
        metadata: Optional[Dict[str, Any]] = None,
    ) -> PropositionRecord:
        record = PropositionRecord(
            statement=statement,
            is_valid=is_valid,
            source=source,
            metadata=metadata or {},
        )
        self.propositions.append(record)
        return record

    def get_last(self) -> Optional[PropositionRecord]:
        return self.propositions[-1] if self.propositions else None

    def get_all(self) -> List[PropositionRecord]:
        return self.propositions.copy()

    def get_valid(self) -> List[PropositionRecord]:
        return [p for p in self.propositions if p.is_valid]

    def get_invalid(self) -> List[PropositionRecord]:
        return [p for p in self.propositions if not p.is_valid]

    def contains(self, statement: str) -> bool:
        return any(p.statement == statement for p in self.propositions)

    def clear(self):
        self.propositions = []

    def __len__(self) -> int:
        return len(self.propositions)

    def __iter__(self):
        return iter(self.propositions)

    def __str__(self):
        lines = [f"=== {self.name} ==="]
        for p in self.propositions:
            lines.append(str(p))
        return "\n".join(lines)


class SymbolicPropositionList(PropositionList):
    def __init__(self):
        super().__init__("Symbolic Propositions")

    def add_symbolic(
        self,
        statement: str,
        is_valid: bool,
        derivation_path: Optional[List[str]] = None,
    ) -> PropositionRecord:
        metadata: Dict[str, Any] = {"derivation_path": derivation_path or []}
        return self.add(statement, is_valid, "symbolic_engine", metadata)


class RenderPropositionList(PropositionList):
    def __init__(self):
        super().__init__("Render Propositions")

    def add_rendered(
        self,
        statement: str,
        is_valid: bool,
        point_coords: Optional[Dict[str, Any]] = None,
    ) -> PropositionRecord:
        metadata: Dict[str, Any] = {"point_coords": point_coords or {}}
        return self.add(statement, is_valid, "render_engine", metadata)


class PropositionManager:
    def __init__(self) -> None:
        self.symbolic_list = SymbolicPropositionList()
        self.render_list = RenderPropositionList()
        self._all_propositions: Dict[str, PropositionRecord] = {}
        self._proof_state: Set[Proposition] = set()

    def add_symbolic(
        self,
        statement: str,
        is_valid: bool,
        derivation_path: Optional[List[str]] = None,
    ) -> PropositionRecord:
        record = self.symbolic_list.add_symbolic(statement, is_valid, derivation_path)
        self._all_propositions[statement] = record
        if is_valid:
            try:
                prop = Proposition.from_string(statement)
                self._proof_state.add(prop)
            except Exception:
                pass
        return record

    def add_rendered(
        self,
        statement: str,
        is_valid: bool,
        point_coords: Optional[Dict[str, Any]] = None,
    ) -> PropositionRecord:
        record = self.render_list.add_rendered(statement, is_valid, point_coords)
        if statement not in self._all_propositions:
            self._all_propositions[statement] = record
        if is_valid:
            try:
                prop = Proposition.from_string(statement)
                self._proof_state.add(prop)
            except Exception:
                pass
        return record

    def get_proposition(self, statement: str) -> Optional[PropositionRecord]:
        return self._all_propositions.get(statement)

    def is_verified(self, statement: str) -> bool:
        record = self._all_propositions.get(statement)
        return record.is_valid if record else False

    def get_all_unique(self) -> List[PropositionRecord]:
        return list(self._all_propositions.values())

    def get_last_symbolic(self) -> Optional[PropositionRecord]:
        return self.symbolic_list.get_last()

    def get_last_rendered(self) -> Optional[PropositionRecord]:
        return self.render_list.get_last()

    def get_proof_state(self):
        """获取证明状态"""
        from .symbolic_engine import ProofState as SEProofState  # pylint: disable=import-outside-toplevel

        state = SEProofState()
        for prop in self._proof_state:
            state.add(prop)
        return state

    def clear(self):
        self.symbolic_list.clear()
        self.render_list.clear()
        self._all_propositions.clear()
        self._proof_state.clear()

    def summary(self) -> str:
        lines = [
            f"Total unique propositions: {len(self._all_propositions)}",
            f"Symbolic propositions: {len(self.symbolic_list)}",
            f"  - Valid: {len(self.symbolic_list.get_valid())}",
            f"  - Invalid: {len(self.symbolic_list.get_invalid())}",
            f"Render propositions: {len(self.render_list)}",
            f"  - Valid: {len(self.render_list.get_valid())}",
            f"  - Invalid: {len(self.render_list.get_invalid())}",
        ]
        return "\n".join(lines)


if __name__ == "__main__":
    manager = PropositionManager()

    manager.add_symbolic("perp A B C D", True)
    manager.add_symbolic("para A B C D", True, ["perp A B C D", "perp E F C D"])
    manager.add_rendered("coll A B C", False, {"A": (0, 0), "B": (1, 0), "C": (0, 1)})

    print(manager.summary())
    print("\n" + str(manager.symbolic_list))
    print("\n" + str(manager.render_list))
