# GENERATED BY AI
"""几何渲染引擎 - 支持所有 AlphaGeometry 谓词的数值验证。

通过数值计算验证几何命题的正确性，类似于 GeoGebra 的图形验证方式。
"""

import math
from dataclasses import dataclass
from typing import Callable, Dict, Optional, Tuple

from .geometry_parser import Proposition


@dataclass
class RenderPoint:
    """渲染点数据结构"""

    name: str
    x: float
    y: float

    def __hash__(self) -> int:
        return hash(self.name)

    def __eq__(self, other: object) -> bool:
        if not isinstance(other, RenderPoint):
            return False
        return self.name == other.name


@dataclass
class RenderLine:
    """渲染线数据结构"""

    name: str
    p1: str
    p2: str

    def __hash__(self) -> int:
        return hash(self.name)

    def __eq__(self, other: object) -> bool:
        if not isinstance(other, RenderLine):
            return False
        return self.name == other.name


@dataclass
class RenderCircle:
    """渲染圆数据结构"""

    name: str
    center: str
    point: str

    def __hash__(self) -> int:
        return hash(self.name)

    def __eq__(self, other: object) -> bool:
        if not isinstance(other, RenderCircle):
            return False
        return self.name == other.name


class RenderEngine:
    """几何渲染引擎 - 用于数值验证

    通过数值计算验证几何命题的正确性。
    支持所有 AlphaGeometry 格式的谓词验证。
    """

    def __init__(self):
        self.points: Dict[str, RenderPoint] = {}
        self.lines: Dict[str, RenderLine] = {}
        self.circles: Dict[str, RenderCircle] = {}
        self.tolerance = 1e-6

    def add_point(self, name: str, x: float, y: float) -> RenderPoint:
        """添加点"""
        point = RenderPoint(name=name, x=x, y=y)
        self.points[name] = point
        return point

    def add_line(self, name: str, p1: str, p2: str) -> RenderLine:
        """添加线"""
        line = RenderLine(name=name, p1=p1, p2=p2)
        self.lines[name] = line
        return line

    def add_circle(self, name: str, center: str, point: str) -> RenderCircle:
        """添加圆"""
        circle = RenderCircle(name=name, center=center, point=point)
        self.circles[name] = circle
        return circle

    def get_point(self, name: str) -> Optional[RenderPoint]:
        """获取点"""
        return self.points.get(name)

    def get_line(self, name: str) -> Optional[RenderLine]:
        """获取线"""
        return self.lines.get(name)

    def get_circle(self, name: str) -> Optional[RenderCircle]:
        """获取圆"""
        return self.circles.get(name)

    def distance(self, p1: str, p2: str) -> float:
        """计算两点距离"""
        point1 = self.get_point(p1)
        point2 = self.get_point(p2)
        if point1 is None or point2 is None:
            raise ValueError(f"点不存在: {p1} 或 {p2}")
        return math.sqrt((point1.x - point2.x) ** 2 + (point1.y - point2.y) ** 2)

    def angle(self, p1: str, p2: str, p3: str) -> float:
        """计算角 p2p1p3 的大小(弧度)"""
        point1 = self.get_point(p1)
        point2 = self.get_point(p2)
        point3 = self.get_point(p3)
        if point1 is None or point2 is None or point3 is None:
            raise ValueError(f"点不存在: {p1}, {p2} 或 {p3}")

        v1x = point2.x - point1.x
        v1y = point2.y - point1.y
        v2x = point3.x - point1.x
        v2y = point3.y - point1.y

        dot = v1x * v2x + v1y * v2y
        cross = v1x * v2y - v1y * v2x

        return math.atan2(abs(cross), dot)

    def verify_proposition(self, prop: Proposition) -> bool:
        """验证命题是否成立

        Args:
            prop: 命题对象

        Returns:
            是否成立
        """
        prop_type = prop.predicate
        args = prop.args

        verify_map: Dict[str, Callable[[Tuple[str, ...]], bool]] = {
            "coll": self._verify_coll,
            "para": self._verify_para,
            "perp": self._verify_perp,
            "cong": self._verify_cong,
            "midp": self._verify_midp,
            "cyclic": self._verify_cyclic,
            "circle": self._verify_circle,
            "eqangle": self._verify_eqangle,
            "eqangle6": self._verify_eqangle6,
            "eqangle3": self._verify_eqangle3,
            "eqangle2": self._verify_eqangle2,
            "eqratio": self._verify_eqratio,
            "eqratio6": self._verify_eqratio6,
            "eqratio3": self._verify_eqratio3,
            "diff": self._verify_diff,
            "sameside": self._verify_sameside,
            "rconst": self._verify_rconst,
            "contri": self._verify_contri,
            "contri2": self._verify_contri,
            "simtri": self._verify_simtri,
            "simtri2": self._verify_simtri,
            "contri*": self._verify_contri_star,
            "simtri*": self._verify_simtri_star,
        }
        negate_map: Dict[str, Callable[[Tuple[str, ...]], bool]] = {
            "ncoll": self._verify_coll,
            "npara": self._verify_para,
            "nperp": self._verify_perp,
        }

        try:
            if prop_type in verify_map:
                return verify_map[prop_type](args)
            if prop_type in negate_map:
                return not negate_map[prop_type](args)
            print(f"警告: 未知的命题类型: {prop_type}")
            return False
        except Exception as e:
            print(f"验证命题 {prop} 时出错: {e}")
            return False

    def _verify_coll(self, args: Tuple[str, ...]) -> bool:
        """验证共线: coll A B C"""
        if len(args) != 3:
            return False
        A, B, C = args
        pA = self.get_point(A)
        pB = self.get_point(B)
        pC = self.get_point(C)
        if pA is None or pB is None or pC is None:
            return False
        cross = (pB.x - pA.x) * (pC.y - pA.y) - (pB.y - pA.y) * (pC.x - pA.x)
        return abs(cross) < self.tolerance

    def _verify_para(self, args: Tuple[str, ...]) -> bool:
        """验证平行: para A B C D"""
        if len(args) != 4:
            return False
        A, B, C, D = args
        pA = self.get_point(A)
        pB = self.get_point(B)
        pC = self.get_point(C)
        pD = self.get_point(D)
        if pA is None or pB is None or pC is None or pD is None:
            return False
        v1x = pB.x - pA.x
        v1y = pB.y - pA.y
        v2x = pD.x - pC.x
        v2y = pD.y - pC.y
        cross = v1x * v2y - v1y * v2x
        return abs(cross) < self.tolerance

    def _verify_perp(self, args: Tuple[str, ...]) -> bool:
        """验证垂直: perp A B C D"""
        if len(args) != 4:
            return False
        A, B, C, D = args
        pA = self.get_point(A)
        pB = self.get_point(B)
        pC = self.get_point(C)
        pD = self.get_point(D)
        if pA is None or pB is None or pC is None or pD is None:
            return False
        v1x = pB.x - pA.x
        v1y = pB.y - pA.y
        v2x = pD.x - pC.x
        v2y = pD.y - pC.y
        dot = v1x * v2x + v1y * v2y
        return abs(dot) < self.tolerance

    def _verify_cong(self, args: Tuple[str, ...]) -> bool:
        """验证全等: cong A B C D (AB = CD)"""
        if len(args) != 4:
            return False
        A, B, C, D = args
        d1 = self.distance(A, B)
        d2 = self.distance(C, D)
        return abs(d1 - d2) < self.tolerance

    def _verify_midp(self, args: Tuple[str, ...]) -> bool:
        """验证中点: midp M A B"""
        if len(args) != 3:
            return False
        M, A, B = args
        pM = self.get_point(M)
        pA = self.get_point(A)
        pB = self.get_point(B)
        if pM is None or pA is None or pB is None:
            return False
        mx = (pA.x + pB.x) / 2
        my = (pA.y + pB.y) / 2
        return abs(pM.x - mx) < self.tolerance and abs(pM.y - my) < self.tolerance

    def _verify_cyclic(self, args: Tuple[str, ...]) -> bool:
        """验证共圆: cyclic A B C D"""
        if len(args) != 4:
            return False
        A, B, C, D = args
        pA = self.get_point(A)
        pB = self.get_point(B)
        pC = self.get_point(C)
        pD = self.get_point(D)
        if pA is None or pB is None or pC is None or pD is None:
            return False
        angle1 = self.angle(A, B, C)
        angle2 = self.angle(A, D, C)
        return abs(angle1 - angle2) < self.tolerance

    def _verify_circle(self, args: Tuple[str, ...]) -> bool:
        """验证圆: circle O A (O 是圆心,A 在圆上)"""
        if len(args) != 2:
            return False
        return True

    def _verify_eqangle(self, args: Tuple[str, ...]) -> bool:
        """验证等角: eqangle A B P Q C D P Q"""
        if len(args) != 8:
            return False
        A, B, P, Q, C, D, _, _ = args
        angle1 = self.angle(B, A, P)
        angle2 = self.angle(D, C, Q)
        return abs(angle1 - angle2) < self.tolerance

    def _verify_eqangle6(self, args: Tuple[str, ...]) -> bool:
        """验证六点等角: eqangle6 A B C D E F G H"""
        if len(args) != 8:
            return False
        A, B, C, _, E, F, G, _ = args
        angle1 = self.angle(B, A, C)
        angle2 = self.angle(F, E, G)
        return abs(angle1 - angle2) < self.tolerance

    def _verify_eqangle3(self, args: Tuple[str, ...]) -> bool:
        """验证三点等角: eqangle3 A B C D E F"""
        if len(args) != 6:
            return False
        A, B, C, D, E, F = args
        angle1 = self.angle(B, A, C)
        angle2 = self.angle(E, D, F)
        return abs(angle1 - angle2) < self.tolerance

    def _verify_eqangle2(self, args: Tuple[str, ...]) -> bool:
        """验证二点等角: eqangle2 A B C D"""
        if len(args) != 4:
            return False
        A, B, C, D = args
        angle1 = self.angle(B, A, C)
        angle2 = self.angle(B, C, D)
        return abs(angle1 - angle2) < self.tolerance

    def _verify_eqratio(self, args: Tuple[str, ...]) -> bool:
        """验证等比: eqratio A B P Q C D P Q"""
        if len(args) != 8:
            return False
        A, B, P, Q, C, D, _, _ = args
        d1 = self.distance(A, B)
        d2 = self.distance(P, Q)
        d3 = self.distance(C, D)
        if d2 < self.tolerance or d3 < self.tolerance:
            return False
        ratio1 = d1 / d2
        ratio2 = d3 / d2
        return abs(ratio1 - ratio2) < self.tolerance

    def _verify_eqratio6(self, args: Tuple[str, ...]) -> bool:
        """验证六点等比: eqratio6 A B C D E F G H"""
        if len(args) != 8:
            return False
        A, B, C, D, E, F, G, H = args
        d1 = self.distance(A, B)
        d2 = self.distance(C, D)
        d3 = self.distance(E, F)
        d4 = self.distance(G, H)
        if d2 < self.tolerance or d4 < self.tolerance:
            return False
        ratio1 = d1 / d2
        ratio2 = d3 / d4
        return abs(ratio1 - ratio2) < self.tolerance

    def _verify_eqratio3(self, args: Tuple[str, ...]) -> bool:
        """验证三点等比: eqratio3 A B C D E F"""
        if len(args) != 6:
            return False
        A, B, C, D, E, F = args
        d1 = self.distance(A, B)
        d2 = self.distance(C, D)
        d3 = self.distance(E, F)
        if d2 < self.tolerance:
            return False
        ratio1 = d1 / d2
        ratio2 = d3 / d2
        return abs(ratio1 - ratio2) < self.tolerance

    def _verify_diff(self, args: Tuple[str, ...]) -> bool:
        """验证不同: diff A B"""
        if len(args) != 2:
            return False
        A, B = args
        pA = self.get_point(A)
        pB = self.get_point(B)
        if pA is None or pB is None:
            return False
        return abs(pA.x - pB.x) > self.tolerance or abs(pA.y - pB.y) > self.tolerance

    def _verify_sameside(self, args: Tuple[str, ...]) -> bool:
        """验证同侧: sameside A B C D 或 sameside A O C B O D"""
        if len(args) < 4:
            return False
        if len(args) == 4:
            A, B, C, D = args
            pA = self.get_point(A)
            pB = self.get_point(B)
            pC = self.get_point(C)
            pD = self.get_point(D)
            if pA is None or pB is None or pC is None or pD is None:
                return False
            cross1 = (pB.x - pC.x) * (pA.y - pC.y) - (pB.y - pC.y) * (pA.x - pC.x)
            cross2 = (pB.x - pC.x) * (pD.y - pC.y) - (pB.y - pC.y) * (pD.x - pC.x)
            return cross1 * cross2 > 0
        if len(args) == 6:
            A, O, C, B, O2, D = args
            pA = self.get_point(A)
            pO = self.get_point(O)
            pC = self.get_point(C)
            pB = self.get_point(B)
            pO2 = self.get_point(O2)
            pD = self.get_point(D)
            if (
                pA is None
                or pO is None
                or pC is None
                or pB is None
                or pO2 is None
                or pD is None
            ):
                return False
            cross1 = (pO.x - pC.x) * (pA.y - pC.y) - (pO.y - pC.y) * (pA.x - pC.x)
            cross2 = (pO.x - pC.x) * (pD.y - pC.y) - (pO.y - pC.y) * (pD.x - pC.x)
            cross3 = (pO.x - pC.x) * (pB.y - pC.y) - (pO.y - pC.y) * (pB.x - pC.x)
            cross4 = (pO.x - pC.x) * (pD.y - pC.y) - (pO.y - pC.y) * (pD.x - pC.x)
            return (cross1 * cross2 > 0) and (cross3 * cross4 > 0)
        return False

    def _verify_rconst(self, args: Tuple[str, ...]) -> bool:
        """验证比例常数: rconst A B C D m n (AB/CD = m/n)"""
        if len(args) != 6:
            return False
        A, B, C, D, m_str, n_str = args
        try:
            m = float(m_str)
            n = float(n_str)
        except ValueError:
            return False
        d1 = self.distance(A, B)
        d2 = self.distance(C, D)
        if d2 < self.tolerance:
            return False
        ratio = d1 / d2
        expected_ratio = m / n
        return abs(ratio - expected_ratio) < self.tolerance

    def _verify_contri(self, args: Tuple[str, ...]) -> bool:
        """验证全等三角形: contri A B C P Q R"""
        if len(args) != 6:
            return False
        A, B, C, P, Q, R = args
        return (
            self._verify_cong((A, B, P, Q))
            and self._verify_cong((B, C, Q, R))
            and self._verify_cong((C, A, R, P))
        )

    def _verify_contri_star(self, args: Tuple[str, ...]) -> bool:
        """验证全等三角形(带星号): contri* A B C P Q R"""
        return self._verify_contri(args)

    def _verify_simtri(self, args: Tuple[str, ...]) -> bool:
        """验证相似三角形: simtri A B C P Q R"""
        if len(args) != 6:
            return False
        A, B, C, P, Q, R = args
        return self._verify_eqangle6(
            (B, A, B, C, Q, P, Q, R)
        ) and self._verify_eqangle6((C, A, C, B, R, P, R, Q))

    def _verify_simtri_star(self, args: Tuple[str, ...]) -> bool:
        """验证相似三角形(带星号): simtri* A B C P Q R"""
        if len(args) != 6:
            return False
        A, B, C, P, Q, R = args
        d1 = self.distance(A, B)
        d2 = self.distance(P, Q)
        d3 = self.distance(B, C)
        d4 = self.distance(Q, R)
        d5 = self.distance(C, A)
        d6 = self.distance(R, P)
        if d2 < self.tolerance or d4 < self.tolerance or d6 < self.tolerance:
            return False
        ratio1 = d1 / d2
        ratio2 = d3 / d4
        ratio3 = d5 / d6
        return (
            abs(ratio1 - ratio2) < self.tolerance
            and abs(ratio2 - ratio3) < self.tolerance
        )

    def clear(self) -> None:
        """清空所有几何对象"""
        self.points.clear()
        self.lines.clear()
        self.circles.clear()

    def reset(self) -> None:
        """重置引擎（清空所有几何对象）"""
        self.clear()

    def __str__(self) -> str:
        return f"RenderEngine(points={len(self.points)}, lines={len(self.lines)}, circles={len(self.circles)})"
