# GENERATED BY AI
"""
简化的符号演绎引擎 - 基于 AlphaGeometry 的核心思想
"""

from typing import List, Set, Dict, Tuple, Optional
from dataclasses import dataclass
from itertools import permutations, combinations

try:
    from .geometry_parser import Proposition, GeometryParser
except ImportError:
    from geometry_parser import Proposition, GeometryParser


@dataclass
class ProofState:
    """证明状态"""

    propositions: Set[Proposition] = None  # 已知命题集合

    def __post_init__(self):
        if self.propositions is None:
            self.propositions = set()

    def add(self, prop: Proposition) -> None:
        """添加命题"""
        self.propositions.add(prop)

    def remove(self, prop: Proposition) -> None:
        """移除命题"""
        if prop in self.propositions:
            self.propositions.remove(prop)

    def contains(self, prop: Proposition) -> bool:
        """检查是否包含命题"""
        return prop in self.propositions

    def get_all(self) -> Set[Proposition]:
        """获取所有命题"""
        return self.propositions.copy()

    def __len__(self):
        return len(self.propositions)

    def __str__(self):
        return f"ProofState({len(self.propositions)} propositions)"


@dataclass
class DeductionRule:
    """演绎规则"""

    name: str  # 规则名称
    premises: List[Proposition]  # 前提条件
    conclusions: List[Proposition]  # 结论

    def __str__(self):
        premises_str = ", ".join(str(p) for p in self.premises)
        conclusions_str = ", ".join(str(p) for p in self.conclusions)
        return f"{self.name}: {premises_str} => {conclusions_str}"


class SymbolicEngine:
    """符号演绎引擎"""

    def __init__(self):
        self.rules: List[DeductionRule] = []
        self._init_default_rules()

    def _init_default_rules(self):
        """初始化默认规则"""
        # 从 rules.txt 加载所有规则
        rules_file = (
            "d:\\代码\\入\\入geometry_simple_glm\\alphageometry-main\\rules.txt"
        )
        try:
            rules_data = GeometryParser.load_rules_from_file(rules_file)
            for rule_data in rules_data:
                rule = DeductionRule(
                    name=f"rule_{len(self.rules)}",
                    premises=rule_data["premises"],
                    conclusions=rule_data["conclusions"],
                )
                self.rules.append(rule)
            print(f"已加载 {len(self.rules)} 条演绎规则")
        except Exception as e:
            print(f"加载规则失败: {e}")
            # 加载失败时使用基本规则
            self._init_basic_rules()

    def _init_basic_rules(self):
        """初始化基本规则(备用)"""
        self.rules = [
            DeductionRule(
                name="perp_to_para",
                premises=[
                    GeometryParser.parse_proposition("perp A B C D"),
                    GeometryParser.parse_proposition("perp E F C D"),
                ],
                conclusions=[GeometryParser.parse_proposition("para A B E F")],
            ),
            DeductionRule(
                name="para_to_para",
                premises=[
                    GeometryParser.parse_proposition("para A B C D"),
                    GeometryParser.parse_proposition("para C D E F"),
                ],
                conclusions=[GeometryParser.parse_proposition("para A B E F")],
            ),
            DeductionRule(
                name="midp_to_cong",
                premises=[GeometryParser.parse_proposition("midp M A B")],
                conclusions=[GeometryParser.parse_proposition("cong A M M B")],
            ),
            DeductionRule(
                name="cong_trans",
                premises=[
                    GeometryParser.parse_proposition("cong A B C D"),
                    GeometryParser.parse_proposition("cong C D E F"),
                ],
                conclusions=[GeometryParser.parse_proposition("cong A B E F")],
            ),
            DeductionRule(
                name="cong_refl",
                premises=[],
                conclusions=[GeometryParser.parse_proposition("cong A A B B")],
            ),
            DeductionRule(
                name="circle_def",
                premises=[
                    GeometryParser.parse_proposition("circle O A"),
                    GeometryParser.parse_proposition("circle O B"),
                ],
                conclusions=[GeometryParser.parse_proposition("cong O A O B")],
            ),
            DeductionRule(
                name="cyclic_perp",
                premises=[
                    GeometryParser.parse_proposition("cyclic A B C D"),
                    GeometryParser.parse_proposition("perp A B B C"),
                ],
                conclusions=[GeometryParser.parse_proposition("perp C D D A")],
            ),
        ]

    def add_rule(self, rule: DeductionRule) -> None:
        """添加规则"""
        self.rules.append(rule)

    def add_rules_from_file(self, filepath: str) -> None:
        """从文件加载规则"""
        rules_data = GeometryParser.load_rules_from_file(filepath)
        for rule_data in rules_data:
            rule = DeductionRule(
                name=f"rule_{len(self.rules)}",
                premises=rule_data["premises"],
                conclusions=rule_data["conclusions"],
            )
            self.rules.append(rule)

    def match_proposition(
        self, pattern: Proposition, prop: Proposition, bindings: Dict[str, str]
    ) -> Optional[Dict[str, str]]:
        """匹配命题模式

        Args:
            pattern: 模式命题(可能包含变量)
            prop: 实际命题
            bindings: 当前绑定

        Returns:
            更新后的绑定,如果不匹配则返回 None
        """
        if pattern.predicate != prop.predicate:
            return None

        # 对于对称关系，支持参数顺序交换
        symmetric_predicates = {"perp", "para", "cong", "coll"}
        if pattern.predicate in symmetric_predicates:
            # 尝试直接匹配
            result = self._try_match_args(pattern.args, prop.args, bindings)
            if result is not None:
                return result
            # 尝试交换前两个参数
            if len(pattern.args) >= 2:
                swapped_pattern_args = (
                    pattern.args[1],
                    pattern.args[0],
                ) + pattern.args[2:]
                result = self._try_match_args(swapped_pattern_args, prop.args, bindings)
                if result is not None:
                    return result
            # 尝试交换后两个参数
            if len(pattern.args) >= 4:
                swapped_pattern_args = pattern.args[:2] + (
                    pattern.args[3],
                    pattern.args[2],
                )
                result = self._try_match_args(swapped_pattern_args, prop.args, bindings)
                if result is not None:
                    return result
            return None

        # 对于非对称关系，直接匹配
        return self._try_match_args(pattern.args, prop.args, bindings)

    def _try_match_args(
        self,
        pattern_args: Tuple[str, ...],
        actual_args: Tuple[str, ...],
        bindings: Dict[str, str],
    ) -> Optional[Dict[str, str]]:
        """尝试匹配参数

        Args:
            pattern_args: 模式参数
            actual_args: 实际参数
            bindings: 当前绑定

        Returns:
            更新后的绑定,如果不匹配则返回 None
        """
        if len(pattern_args) != len(actual_args):
            return None

        new_bindings = bindings.copy()

        for pattern_arg, actual_arg in zip(pattern_args, actual_args):
            # 如果模式参数是大写字母,则视为变量
            if pattern_arg.isupper():
                if pattern_arg in new_bindings:
                    # 检查是否与已有绑定一致
                    if new_bindings[pattern_arg] != actual_arg:
                        return None
                else:
                    new_bindings[pattern_arg] = actual_arg
            else:
                # 字面量匹配
                if pattern_arg != actual_arg:
                    return None

        return new_bindings

    def apply_rule(self, rule: DeductionRule, state: ProofState) -> List[Proposition]:
        """应用规则到证明状态

        Args:
            rule: 演绎规则
            state: 证明状态

        Returns:
            可以推导出的新命题列表
        """
        new_props = []

        # 获取状态中的所有命题
        state_props = list(state.get_all())

        # 尝试所有前提的排列
        for perm in permutations(rule.premises):
            # 尝试所有可能的匹配
            matches = self._find_all_matches(list(perm), state_props)
            for bindings in matches:
                # 应用绑定到结论
                for conclusion in rule.conclusions:
                    new_prop = self._apply_bindings(conclusion, bindings)
                    if new_prop and not state.contains(new_prop):
                        new_props.append(new_prop)

        return new_props

    def _find_all_matches(
        self, premises: List[Proposition], state_props: List[Proposition]
    ) -> List[Dict[str, str]]:
        """找到所有满足前提的匹配

        Args:
            premises: 前提列表
            state_props: 状态中的命题列表

        Returns:
            绑定列表
        """
        if not premises:
            return [{}]

        first_premise = premises[0]
        rest_premises = premises[1:]

        # 否定关系不能作为前提
        negative_predicates = {"ncoll", "npara", "nperp", "diff"}
        if first_premise.predicate in negative_predicates:
            return []

        result = []

        # 对于状态中的每个命题,尝试匹配第一个前提
        for prop in state_props:
            bindings = self.match_proposition(first_premise, prop, {})
            if bindings is not None:
                # 应用绑定到剩余前提
                bound_rest_premises = []
                for rest_premise in rest_premises:
                    bound_premise = self._apply_bindings(rest_premise, bindings)
                    if bound_premise is not None:
                        bound_rest_premises.append(bound_premise)

                # 递归匹配剩余前提
                if bound_rest_premises:
                    rest_bindings = self._find_all_matches(
                        bound_rest_premises, state_props
                    )
                    for rest_binding in rest_bindings:
                        # 合并绑定
                        merged = {**bindings, **rest_binding}
                        result.append(merged)
                elif not rest_premises:
                    # 没有剩余前提，直接添加绑定
                    result.append(bindings)

        return result

    def _apply_bindings(
        self, prop: Proposition, bindings: Dict[str, str]
    ) -> Optional[Proposition]:
        """应用绑定到命题

        Args:
            prop: 命题
            bindings: 绑定

        Returns:
            应用绑定后的命题
        """
        new_args = []
        for arg in prop.args:
            if arg in bindings:
                new_args.append(bindings[arg])
            else:
                new_args.append(arg)

        return Proposition(predicate=prop.predicate, args=tuple(new_args))

    def deduce(self, state: ProofState, max_steps: int = 100) -> List[Proposition]:
        """执行演绎推理

        Args:
            state: 初始证明状态
            max_steps: 最大推理步数

        Returns:
            推导出的所有新命题
        """
        new_props = []
        step = 0

        while step < max_steps:
            step += 1
            added = False

            # 尝试应用每条规则
            for rule in self.rules:
                derived = self.apply_rule(rule, state)
                for prop in derived:
                    if not state.contains(prop):
                        state.add(prop)
                        new_props.append(prop)
                        added = True

            if not added:
                # 没有新命题被推导出来,停止
                break

        return new_props

    def can_prove(
        self, goal: Proposition, premises: List[Proposition], max_steps: int = 100
    ) -> Tuple[bool, List[Proposition]]:
        """检查是否可以证明目标

        Args:
            goal: 目标命题
            premises: 前提命题列表
            max_steps: 最大推理步数

        Returns:
            (是否可以证明, 推导出的命题列表)
        """
        state = ProofState()
        for prop in premises:
            state.add(prop)

        derived = self.deduce(state, max_steps)

        return state.contains(goal), derived

    def get_rules(self) -> List[DeductionRule]:
        """获取所有规则"""
        return self.rules.copy()

    def clear_rules(self):
        """清空所有规则"""
        self.rules.clear()

    def __str__(self):
        return f"SymbolicEngine({len(self.rules)} rules)"
