# GENERATED BY AI
"""几何题推理AI的符号引擎。

该模块提供类似于AlphaGeometry的DD的符号演绎功能。
"""

from typing import List, Set, Dict, Tuple, Optional
from dataclasses import dataclass, field


@dataclass
class Statement:
    """几何命题。"""
    predicate: str
    args: Tuple[str, ...]

    def __str__(self):
        return f"{self.predicate} {' '.join(self.args)}"

    def __hash__(self):
        return hash((self.predicate, self.args))

    def __eq__(self, other):
        if not isinstance(other, Statement):
            return False
        return self.predicate == other.predicate and self.args == other.args


@dataclass
class ProofState:
    """证明状态。"""
    statements: Set[Statement] = field(default_factory=set)
    derived: Set[Statement] = field(default_factory=set)

    def add(self, stmt: Statement, is_derived: bool = False):
        """添加命题。"""
        self.statements.add(stmt)
        if is_derived:
            self.derived.add(stmt)

    def contains(self, stmt: Statement) -> bool:
        """检查是否包含命题。"""
        return stmt in self.statements

    def get_by_predicate(self, predicate: str) -> List[Statement]:
        """按谓词获取命题。"""
        return [s for s in self.statements if s.predicate == predicate]


class DeductionRule:
    """演绎规则。"""

    def __init__(self, name: str, premises: List[str], conclusions: List[str]):
        """初始化演绎规则。"""
        self.name = name
        self.premises = premises
        self.conclusions = conclusions

    def apply(self, state: ProofState) -> List[Statement]:
        """应用规则。"""
        new_statements = []

        premise_stmts = [self._parse_statement(p) for p in self.premises]
        conclusion_stmts = [self._parse_statement(c) for c in self.conclusions]

        bindings_list = self._find_bindings(state, premise_stmts)

        for bindings in bindings_list:
            for conc in conclusion_stmts:
                bound_args = tuple(bindings.get(arg, arg) for arg in conc.args)
                new_stmt = Statement(conc.predicate, bound_args)
                if not state.contains(new_stmt):
                    new_statements.append(new_stmt)

        return new_statements

    def _parse_statement(self, stmt_str: str) -> Statement:
        """解析语句。"""
        parts = stmt_str.split()
        if not parts:
            return Statement("", ())
        return Statement(parts[0], tuple(parts[1:]))

    def _find_bindings(
        self, state: ProofState, patterns: List[Statement]
    ) -> List[Dict[str, str]]:
        """查找参数绑定。"""
        if not patterns:
            return [{}]

        first_pattern = patterns[0]
        rest_patterns = patterns[1:]

        candidates = state.get_by_predicate(first_pattern.predicate)
        bindings_list = []

        for candidate in candidates:
            bindings = self._match_pattern(first_pattern.args, candidate.args)
            if bindings is not None:
                rest_bindings = self._find_bindings(state, rest_patterns)
                for rest_binding in rest_bindings:
                    combined = {**bindings, **rest_binding}
                    if self._is_consistent(combined):
                        bindings_list.append(combined)

        return bindings_list

    def _match_pattern(
        self, pattern_args: Tuple[str, ...], actual_args: Tuple[str, ...]
    ) -> Optional[Dict[str, str]]:
        """匹配模式。"""
        if len(pattern_args) != len(actual_args):
            return None

        bindings: Dict[str, str] = {}
        for p, a in zip(pattern_args, actual_args):
            if p.isupper():
                if p in bindings and bindings[p] != a:
                    return None
                bindings[p] = a
            elif p != a:
                return None

        return bindings

    def _is_consistent(self, _bindings: Dict[str, str]) -> bool:
        """检查绑定是否一致。"""
        return True


# 内置规则
BUILTIN_RULES = [
    DeductionRule("perp_to_para", ["perp A B C D", "perp E F C D"], ["para A B E F"]),
    DeductionRule("para_to_para", ["para A B C D", "para C D E F"], ["para A B E F"]),
    DeductionRule("midp_to_cong", ["midp M A B"], ["cong A M M B"]),
    DeductionRule("cong_trans", ["cong A B C D", "cong C D E F"], ["cong A B E F"]),
    DeductionRule("cong_refl", [], ["cong A A B B"]),
    DeductionRule("circle_def", ["circle O A", "circle O B"], ["cong O A O B"]),
    DeductionRule("cyclic_perp", ["cyclic A B C D", "perp A B B C"], ["perp C D D A"]),
    DeductionRule("isos_triangle", ["cong A B A C"], ["eqangle B A C A C A B"]),
]


# 扩展规则
EXTENDED_RULES = [
    # 共圆规则
    DeductionRule(
        "cong_to_cyclic",
        ["cong O A O B", "cong O B O C", "cong O C O D"],
        ["cyclic A B C D"]
    ),
    DeductionRule(
        "cyclic_eqangle",
        ["cyclic A B P Q"],
        ["eqangle P A P B Q A Q B"]
    ),
    DeductionRule(
        "eqangle6_to_cyclic",
        ["eqangle6 P A P B Q A Q B", "ncoll P Q A B"],
        ["cyclic A B P Q"]
    ),
    DeductionRule(
        "cyclic_eqangle6_to_cong",
        ["cyclic A B C P Q R", "eqangle C A C B R P R Q"],
        ["cong A B P Q"]
    ),
    # 中点规则
    DeductionRule(
        "midp_to_para",
        ["midp E A B", "midp F A C"],
        ["para E F B C"]
    ),
    DeductionRule(
        "midp_to_para2",
        ["midp M A B", "para A C B D", "para A D B C"],
        ["midp M C D"]
    ),
    DeductionRule(
        "midp_eqratio",
        ["midp M A B", "midp N C D"],
        ["eqratio M A A B N C C D"]
    ),
    # 等角规则
    DeductionRule(
        "eqangle_to_para",
        ["eqangle A B P Q C D P Q"],
        ["para A B C D"]
    ),
    DeductionRule(
        "eqangle_to_perp",
        ["eqangle A B P Q C D U V", "perp P Q U V"],
        ["perp A B C D"]
    ),
    DeductionRule(
        "eqangle_trans",
        ["eqangle a b c d m n p q", "eqangle c d e f p q r u"],
        ["eqangle a b e f m n r u"]
    ),
    # 等比规则
    DeductionRule(
        "eqratio_to_cong",
        ["eqratio A B P Q C D U V", "cong P Q U V"],
        ["cong A B C D"]
    ),
    DeductionRule(
        "eqratio_trans",
        ["eqratio a b c d m n p q", "eqratio c d e f p q r u"],
        ["eqratio a b e f m n r u"]
    ),
    # 等角等比转换规则
    DeductionRule(
        "eqratio6_to_eqangle6",
        ["eqratio6 d b d c a b a c", "coll d b c", "ncoll a b c"],
        ["eqangle6 a b a d a d a c"]
    ),
    DeductionRule(
        "eqangle6_to_eqratio6",
        ["eqangle6 a b a d a d a c", "coll d b c", "ncoll a b c"],
        ["eqratio6 d b d c a b a c"]
    ),
    # 全等和等角转换
    DeductionRule(
        "cong_to_eqangle",
        ["cong O A O B", "ncoll O A B"],
        ["eqangle O A A B A B O B"]
    ),
    DeductionRule(
        "eqangle6_to_cong",
        ["eqangle6 A O A B B A B O", "ncoll O A B"],
        ["cong O A O B"]
    ),
    # 圆中点规则
    DeductionRule(
        "circle_midp_eqangle",
        ["circle O A B C", "midp M B C"],
        ["eqangle A B A C O B O M"]
    ),
    DeductionRule(
        "circle_coll_eqangle_to_midp",
        ["circle O A B C", "coll M B C", "eqangle A B A C O B O M"],
        ["midp M B C"]
    ),
    # 中点垂直规则
    DeductionRule(
        "midp_perp_to_cong",
        ["perp A B B C", "midp M A C"],
        ["cong A M B M"]
    ),
    # 全等三角形规则
    DeductionRule(
        "cong_to_contri",
        ["cong A P B P", "cong A Q B Q", "cong C A R P", "ncoll A B C"],
        ["contri* A B C P Q R"]
    ),
    DeductionRule(
        "cong_eqangle_to_contri",
        ["cong A P B P", "cong A Q B Q", "eqangle6 B A B C Q P Q R", "ncoll A B C"],
        ["contri* A B C P Q R"]
    ),
    # 相似三角形规则
    DeductionRule(
        "eqangle_to_simtri",
        ["eqangle6 B A B C Q P Q R", "eqangle6 C A C B R P R Q", "ncoll A B C"],
        ["simtri A B C P Q R"]
    ),
    DeductionRule(
        "eqangle2_to_simtri",
        ["eqangle6 B A B C Q R Q P", "eqangle6 C A C B R Q R P", "ncoll A B C"],
        ["simtri2 A B C P Q R"]
    ),
    DeductionRule(
        "eqangle_cong_to_contri",
        ["eqangle6 B A B C Q P Q R", "eqangle6 C A C B R P R Q", "ncoll A B C", "cong A B P Q"],
        ["contri A B C P Q R"]
    ),
    DeductionRule(
        "eqangle2_cong_to_contri2",
        ["eqangle6 B A B C Q R Q P", "eqangle6 C A C B R Q R P", "ncoll A B C", "cong A B P Q"],
        ["contri2 A B C P Q R"]
    ),
    # 等比相似规则
    DeductionRule(
        "eqratio6_to_simtri",
        ["eqratio6 B A B C Q P Q R", "eqratio6 C A C B R P R Q", "ncoll A B C"],
        ["simtri* A B C P Q R"]
    ),
    DeductionRule(
        "eqratio6_eqangle6_to_simtri",
        ["eqratio6 B A B C Q P Q R", "eqangle6 B A B C Q P Q R", "ncoll A B C"],
        ["simtri* A B C P Q R"]
    ),
    DeductionRule(
        "eqratio6_cong_to_contri",
        ["eqratio6 B A B C Q P Q R", "eqratio6 C A C B R P R Q", "ncoll A B C", "cong A B P Q"],
        ["contri* A B C P Q R"]
    ),
    # 平行传递规则
    DeductionRule(
        "para_eqratio",
        ["para a b c d", "coll m a d", "coll n b c", "eqratio6 m a m d n b n c", "sameside m a d n b c"],
        ["para m n a b"]
    ),
    DeductionRule(
        "para_to_eqratio",
        ["para a b c d", "coll m a d", "coll n b c", "para m n a b"],
        ["eqratio6 m a m d n b n c"]
    ),
    # 平行共线规则
    DeductionRule(
        "para_to_coll",
        ["para A B A C"],
        ["coll A B C"]
    ),
    # 等比平行规则
    DeductionRule(
        "eqratio_to_para",
        ["eqratio O A A C O B B D", "coll O A C", "coll O B D", "ncoll A B C", "sameside A O C B O D"],
        ["para A B C D"]
    ),
]


class SymbolicEngine:
    """符号引擎。"""

    def __init__(self, rules: Optional[List[DeductionRule]] = None, extended: bool = True):
        """初始化符号引擎。"""
        if rules is None:
            if extended:
                self.rules = BUILTIN_RULES + EXTENDED_RULES
            else:
                self.rules = BUILTIN_RULES.copy()
        else:
            self.rules = rules
        self.state = ProofState()
        self.max_iterations = 100

    def reset(self):
        """重置引擎。"""
        self.state = ProofState()

    def add_statement(self, stmt_str: str, is_derived: bool = False) -> Statement:
        """添加命题。"""
        stmt = self._parse_statement(stmt_str)
        self.state.add(stmt, is_derived)
        return stmt

    def _parse_statement(self, stmt_str: str) -> Statement:
        """解析语句。"""
        stmt_str = stmt_str.strip()
        parts = stmt_str.split()
        if not parts:
            return Statement("", ())
        return Statement(parts[0], tuple(parts[1:]))

    def apply_rules(self) -> List[Statement]:
        """应用所有规则。"""
        new_statements = []
        for rule in self.rules:
            derived = rule.apply(self.state)
            for stmt in derived:
                self.state.add(stmt, is_derived=True)
                new_statements.append(stmt)
        return new_statements

    def deduce(self, max_steps: Optional[int] = None) -> int:
        """演绎推理。"""
        actual_max_steps = max_steps if max_steps is not None else self.max_iterations
        total_new = 0

        for _ in range(actual_max_steps):
            new = self.apply_rules()
            total_new += len(new)
            if not new:
                break

        return total_new

    def verify(self, stmt_str: str) -> bool:
        """验证命题。"""
        stmt = self._parse_statement(stmt_str)
        return self.state.contains(stmt)

    def can_derive(
        self, stmt_str: str, max_steps: Optional[int] = None
    ) -> Tuple[bool, List[Statement]]:
        """检查能否推导。"""
        if self.verify(stmt_str):
            return True, []

        original_state = ProofState(
            statements=self.state.statements.copy(), derived=self.state.derived.copy()
        )

        target = self._parse_statement(stmt_str)
        derivation_path = []

        actual_max_steps = max_steps if max_steps is not None else self.max_iterations

        for _ in range(actual_max_steps):
            new = self.apply_rules()
            derivation_path.extend(new)

            if self.state.contains(target):
                return True, derivation_path

        self.state = original_state
        return False, []

    def get_all_statements(self) -> List[str]:
        """获取所有命题。"""
        return [str(s) for s in self.state.statements]

    def get_derived_statements(self) -> List[str]:
        """获取推导命题。"""
        return [str(s) for s in self.state.derived]

    def get_rule_count(self) -> int:
        """获取规则数量。"""
        return len(self.rules)


if __name__ == "__main__":
    engine = SymbolicEngine()

    print(f"加载了 {engine.get_rule_count()} 条演绎规则\n")

    # 测试垂直到平行规则
    print("=== 测试垂直到平行规则 ===")
    engine.reset()
    engine.add_statement("perp A B C D")
    engine.add_statement("perp E F C D")

    new = engine.deduce()
    print(f"推导出 {new} 条新语句")

    result, path = engine.can_derive("para A B E F")
    print(f"能否推导 'para A B E F': {result}")
    if path:
        print("推导路径:")
        for stmt in path:
            print(f"  {stmt}")

    # 测试共圆规则
    print("\n=== 测试共圆规则 ===")
    engine.reset()
    engine.add_statement("cong O A O B")
    engine.add_statement("cong O B O C")
    engine.add_statement("cong O C O D")

    new = engine.deduce()
    print(f"推导出 {new} 条新语句")

    result = engine.verify("cyclic A B C D")
    print(f"能否验证 'cyclic A B C D': {result}")

    # 测试中点规则
    print("\n=== 测试中点规则 ===")
    engine.reset()
    engine.add_statement("midp M A B")

    new = engine.deduce()
    print(f"推导出 {new} 条新语句")

    result = engine.verify("cong A M M B")
    print(f"能否验证 'cong A M M B': {result}")
