# GENERATED BY AI
"""测试 AlphaGeometry examples.txt 中的问题"""

import sys
import os
import signal

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from geometry_parser import GeometryParser, Proposition, Problem
from render_engine import RenderEngine
from symbolic_engine import SymbolicEngine, ProofState


# 设置超时
def timeout_handler(signum, frame):
    raise TimeoutError("测试超时")


class AlphaGeometryTester:
    """AlphaGeometry 测试器"""

    def __init__(self):
        self.parser = GeometryParser()
        self.render_engine = RenderEngine()
        self.symbolic_engine = SymbolicEngine()

    def test_examples_from_file(self, filepath: str):
        """从文件测试示例

        Args:
            filepath: examples.txt 文件路径
        """
        print(f"\n从文件加载测试用例: {filepath}")

        examples = self._load_examples(filepath)
        print(f"加载了 {len(examples)} 个测试用例\n")

        results = []
        for i, (name, problem_str) in enumerate(examples, 1):
            print(f"\n{'=' * 60}")
            print(f"测试 {i}/{len(examples)}: {name}")
            print(f"{'=' * 60}")

            try:
                # 设置超时
                signal.signal(signal.SIGALRM, timeout_handler)
                signal.alarm(30)  # 30秒超时

                result = self.test_problem(problem_str)
                results.append((name, result))

                signal.alarm(0)  # 取消超时

            except TimeoutError as e:
                print(f"  ✗ 测试超时: {e}")
                results.append((name, False))
                signal.alarm(0)
            except Exception as e:
                print(f"  ✗ 测试失败: {e}")
                results.append((name, False))

        return results

    def _load_examples(self, filepath: str) -> list:
        """加载示例文件

        Args:
            filepath: 文件路径

        Returns:
            (名称, 问题字符串) 列表
        """
        examples = []
        current_name = None
        current_problem = []

        with open(filepath, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue

                # 名称行(以数字开头)
                if line.isdigit() and len(current_problem) == 0:
                    current_name = f"Example_{line}"
                # 问题行(包含 ?)
                elif "?" in line:
                    if current_name:
                        examples.append((current_name, line))
                        current_name = None
                # 其他行(可能是描述)
                else:
                    if current_name and line and not line.isdigit():
                        current_name = line

        return examples

    def test_problem(self, problem_str: str):
        """测试单个问题

        Args:
            problem_str: 问题字符串

        Returns:
            是否成功
        """
        print(f"\n问题: {problem_str}")

        try:
            # 解析问题
            problem = self.parser.parse_problem(problem_str)
            print(f"  ✓ 解析成功")
            print(f"    构造数: {len(problem.constructions)}")
            print(f"    目标: {problem.goal}")

            # 测试符号推理
            print(f"\n  测试符号推理...")
            symbolic_success = self._test_symbolic(problem)

            # 测试渲染验证
            print(f"\n  测试渲染验证...")
            render_success = self._test_render(problem)

            # 综合结果
            success = symbolic_success or render_success
            print(f"\n  结果: {'✓ 成功' if success else '✗ 失败'}")
            print(f"    符号推理: {'✓' if symbolic_success else '✗'}")
            print(f"    渲染验证: {'✓' if render_success else '✗'}")

            return success

        except Exception as e:
            print(f"  ✗ 测试失败: {e}")
            import traceback

            traceback.print_exc()
            return False

    def _test_symbolic(self, problem: Problem) -> bool:
        """测试符号推理

        Args:
            problem: 问题对象

        Returns:
            是否成功
        """
        try:
            # 创建证明状态
            state = ProofState()

            # 添加构造产生的命题(这里简化处理,只添加目标)
            # 在实际应用中,应该根据构造生成相应的命题

            # 尝试证明目标
            premises = []  # 空前提,只测试规则应用
            can_prove, derived = self.symbolic_engine.can_prove(
                problem.goal, premises, max_steps=10
            )

            print(f"    规则数: {len(self.symbolic_engine.get_rules())}")
            print(f"    推导出的命题数: {len(derived)}")
            print(f"    可以证明目标: {can_prove}")

            return can_prove

        except Exception as e:
            print(f"    ✗ 符号推理失败: {e}")
            return False

    def _test_render(self, problem: Problem) -> bool:
        """测试渲染验证

        Args:
            problem: 问题对象

        Returns:
            是否成功
        """
        try:
            # 清空渲染引擎
            self.render_engine.clear()

            # 添加一些测试点(简化处理)
            # 在实际应用中,应该根据构造生成相应的点和坐标
            self.render_engine.add_point("A", 0, 0)
            self.render_engine.add_point("B", 2, 0)
            self.render_engine.add_point("C", 1, 1)

            # 验证目标
            result = self.render_engine.verify_proposition(problem.goal)

            print(f"    验证结果: {result}")

            return result

        except Exception as e:
            print(f"    ✗ 渲染验证失败: {e}")
            return False

    def test_all_predicates(self):
        """测试所有支持的谓词"""
        print("\n" + "=" * 60)
        print("测试所有支持的谓词")
        print("=" * 60)

        # 添加测试点
        self.render_engine.clear()
        self.render_engine.add_point("A", 0, 0)
        self.render_engine.add_point("B", 2, 0)
        self.render_engine.add_point("C", 1, 1)
        self.render_engine.add_point("D", 1, 0)
        self.render_engine.add_point("E", 0, 1)
        self.render_engine.add_point("F", 2, 1)

        # 测试所有谓词
        test_cases = [
            # 基本关系
            ("coll A B D", "共线"),
            ("para A B E F", "平行"),
            ("perp A B D C", "垂直"),
            ("cong A D D B", "全等"),
            ("midp D A B", "中点"),
            ("cyclic A B C D", "共圆"),
            ("circle O A", "圆"),
            # 角度关系
            ("eqangle A B C D E F G H", "等角"),
            ("eqangle6 A B C D E F G H", "六点等角"),
            ("eqangle3 A B C D E F", "三点等角"),
            ("eqangle2 A B C D", "二点等角"),
            # 比例关系
            ("eqratio A B C D E F G H", "等比"),
            ("eqratio6 A B C D E F G H", "六点等比"),
            ("eqratio3 A B C D E F", "三点等比"),
            # 否定关系
            ("ncoll A B C", "非共线"),
            ("npara A B C D", "非平行"),
            ("nperp A B C D", "非垂直"),
            ("diff A B", "不同点"),
            # 特殊关系
            ("sameside A B C D", "同侧"),
            # 三角形关系
            ("contri A B C D E F", "全等三角形"),
            ("simtri A B C D E F", "相似三角形"),
        ]

        passed = 0
        failed = 0

        for prop_str, desc in test_cases:
            try:
                prop = self.parser.parse_proposition(prop_str)
                result = self.render_engine.verify_proposition(prop)
                print(f"  ✓ {desc}: {prop_str} -> {result}")
                passed += 1
            except Exception as e:
                print(f"  ✗ {desc}: {prop_str} -> 错误: {e}")
                failed += 1

        print(f"\n总计: {passed} 通过, {failed} 失败")
        return failed == 0

    def test_all_rules(self):
        """测试所有加载的规则"""
        print("\n" + "=" * 60)
        print("测试所有加载的规则")
        print("=" * 60)

        rules = self.symbolic_engine.get_rules()
        print(f"\n已加载 {len(rules)} 条演绎规则")

        # 显示前10条规则
        print("\n前10条规则:")
        for i, rule in enumerate(rules[:10]):
            print(f"  {i+1}. {rule}")

        return len(rules) > 0


def main():
    print("\n" + "=" * 60)
    print("AlphaGeometry 语法测试")
    print("=" * 60)

    tester = AlphaGeometryTester()

    # 测试所有谓词
    predicates_passed = tester.test_all_predicates()

    # 测试所有规则
    rules_passed = tester.test_all_rules()

    # 测试 examples.txt
    examples_file = (
        "d:\\代码\\入\\入geometry_simple_glm\\alphageometry-main\\examples.txt"
    )
    if os.path.exists(examples_file):
        print("\n" + "=" * 60)
        print("测试 examples.txt")
        print("=" * 60)

        try:
            results = tester.test_examples_from_file(examples_file)

            print("\n" + "=" * 60)
            print("测试总结")
            print("=" * 60)

            passed = sum(1 for _, result in results if result)
            total = len(results)
            print(f"examples.txt: {passed}/{total} 通过")

            for name, result in results:
                status = "✓" if result else "✗"
                print(f"  {status} {name}")

            examples_passed = passed == total
        except Exception as e:
            print(f"  ✗ 测试 examples.txt 失败: {e}")
            examples_passed = False
    else:
        print(f"\n  警告: examples.txt 不存在: {examples_file}")
        examples_passed = True  # 跳过此测试

    # 总体结果
    print("\n" + "=" * 60)
    print("总体结果")
    print("=" * 60)

    all_passed = predicates_passed and rules_passed and examples_passed

    print(f"  谓词测试: {'✓ 通过' if predicates_passed else '✗ 失败'}")
    print(f"  规则测试: {'✓ 通过' if rules_passed else '✗ 失败'}")
    print(f"  示例测试: {'✓ 通过' if examples_passed else '✗ 失败'}")
    print(f"\n  总体: {'✓ 所有测试通过' if all_passed else '✗ 部分测试失败'}")
    print("=" * 60)


if __name__ == "__main__":
    main()
