# GENERATED BY AI
"""
训练数据生成器测试 - 验证数据生成的正确性和完整性
"""

import sys
import os
import json
import unittest

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from data_generator import (
    TrainingDataGenerator,
    ProofData,
    ProofStep,
    SimpleProofState,
    SimpleDeductiveEngine,
    ProblemGenerator,
    GeometryDefinitions,
    DeductionRules,
)


class TestProofState(unittest.TestCase):
    """测试证明状态"""

    def setUp(self):
        self.state = SimpleProofState()

    def test_add_predicate(self):
        """测试添加谓词"""
        result = self.state.add("coll a b c")
        self.assertTrue(result)
        self.assertEqual(len(self.state.predicates), 1)

    def test_add_duplicate(self):
        """测试添加重复谓词"""
        self.state.add("coll a b c")
        result = self.state.add("coll a b c")
        self.assertFalse(result)
        self.assertEqual(len(self.state.predicates), 1)

    def test_normalize_coll(self):
        """测试coll谓词规范化"""
        self.state.add("coll a b c")
        self.assertTrue(self.state.contains("coll b a c"))
        self.assertTrue(self.state.contains("coll c b a"))

    def test_normalize_para(self):
        """测试para谓词规范化"""
        self.state.add("para a b c d")
        self.assertTrue(self.state.contains("para a b c d"))


class TestDeductiveEngine(unittest.TestCase):
    """测试演绎引擎"""

    def setUp(self):
        self.engine = SimpleDeductiveEngine()

    def test_deduce_from_coll(self):
        """测试从共线推导"""
        self.engine.reset()
        self.engine.add_premise("coll a b c")
        self.engine.add_premise("coll a b d")

        steps = self.engine.deduce(max_steps=5)

        conclusions = [s.conclusion for s in steps]
        self.assertIn("coll a c d", conclusions)

    def test_deduce_from_para(self):
        """测试从平行推导"""
        self.engine.reset()
        self.engine.add_premise("para a b c d")
        self.engine.add_premise("para c d e f")

        steps = self.engine.deduce(max_steps=5)

        conclusions = [s.conclusion for s in steps]
        self.assertIn("para a b e f", conclusions)

    def test_deduce_from_cong(self):
        """测试从全等推导"""
        self.engine.reset()
        self.engine.add_premise("cong a b c d")
        self.engine.add_premise("cong c d e f")

        steps = self.engine.deduce(max_steps=5)

        conclusions = [s.conclusion for s in steps]
        self.assertIn("cong a b e f", conclusions)


class TestProblemGenerator(unittest.TestCase):
    """测试问题生成器"""

    def setUp(self):
        self.gen = ProblemGenerator()

    def test_gen_triangle_basic(self):
        """测试三角形问题生成"""
        problem, goal, constructions = self.gen._gen_triangle_basic()
        self.assertIn("triangle", problem)
        self.assertIn("coll", goal)

    def test_gen_midpoint_problem(self):
        """测试中点问题生成"""
        problem, goal, constructions = self.gen._gen_midpoint_problem()
        self.assertIn("midpoint", problem)
        self.assertIn("coll", goal)

    def test_gen_orthocenter_problem(self):
        """测试垂心问题生成"""
        problem, goal, constructions = self.gen._gen_orthocenter_problem()
        self.assertIn("orthocenter", problem)
        self.assertIn("perp", goal)


class TestTrainingDataGenerator(unittest.TestCase):
    """测试训练数据生成器"""

    def setUp(self):
        self.generator = TrainingDataGenerator()

    def test_parse_problem(self):
        """测试问题解析"""
        constructions, goal, predicates = self.generator.parse_problem(
            "a b c = triangle ? ncoll a b c"
        )
        self.assertEqual(len(constructions), 1)
        self.assertEqual(goal, "ncoll a b c")

    def test_generate_proof_data(self):
        """测试证明数据生成"""
        proof_data = self.generator.generate_proof_data(
            "a b c = triangle; m = midpoint m a b ? coll m a b", "test_problem"
        )

        self.assertEqual(proof_data.problem_name, "test_problem")
        self.assertTrue(len(proof_data.setup_predicates) > 0)
        self.assertTrue(len(proof_data.proof_steps) > 0)
        self.assertTrue(proof_data.is_solved)

    def test_generate_batch(self):
        """测试批量生成"""
        batch = self.generator.generate_batch(num_problems=5, include_random=False)
        self.assertGreaterEqual(len(batch), 0)

    def test_export_json(self):
        """测试JSON导出"""
        import tempfile

        proof_data = self.generator.generate_proof_data(
            "a b c = triangle; m = midpoint m a b ? coll m a b", "export_test"
        )

        with tempfile.NamedTemporaryFile(suffix=".json", delete=False, mode="w") as f:
            temp_path = f.name

        try:
            self.generator.export_to_file([proof_data], temp_path, output_format="json")

            with open(temp_path, "r", encoding="utf-8") as f:
                data = json.load(f)

            self.assertEqual(len(data), 1)
            self.assertEqual(data[0]["problem_name"], "export_test")
        finally:
            if os.path.exists(temp_path):
                os.unlink(temp_path)

    def test_get_training_sequences(self):
        """测试获取训练序列"""
        proof_data = self.generator.generate_proof_data(
            "a b c = triangle; m = midpoint m a b ? coll m a b", "seq_test"
        )

        sequences = self.generator.get_training_sequences([proof_data])

        self.assertEqual(len(sequences), 1)
        init, steps, goal = sequences[0]
        self.assertTrue(len(init) > 0)
        self.assertTrue(len(steps) > 0)


class TestProofData(unittest.TestCase):
    """测试证明数据类"""

    def test_to_training_format(self):
        """测试转换为训练格式"""
        steps = [
            ProofStep(
                premises=["coll a b c", "coll a b d"],
                conclusion="coll a c d",
                rule_name="r01",
                level=1,
            )
        ]

        proof_data = ProofData(
            problem_name="test",
            problem_statement="test problem",
            constructions=["a b c = triangle"],
            goal="coll a c d",
            proof_steps=steps,
            is_solved=True,
            setup_predicates=["coll a b c"],
        )

        training_format = proof_data.to_training_format()

        self.assertEqual(training_format["problem_name"], "test")
        self.assertEqual(len(training_format["proof_steps"]), 1)
        self.assertEqual(training_format["proof_steps"][0]["rule_name"], "r01")


class TestIntegration(unittest.TestCase):
    """集成测试"""

    def test_full_pipeline(self):
        """测试完整流程"""
        generator = TrainingDataGenerator()

        problems = [
            "a b c = triangle; m = midpoint m a b ? coll m a b",
            "a b c = triangle; h = orthocenter h a b c ? perp h a b c",
            "a b c = triangle; o = circumcenter o a b c ? cong o a o b",
        ]

        results = []
        for problem in problems:
            proof_data = generator.generate_proof_data(problem)
            results.append(proof_data)

        self.assertEqual(len(results), 3)

        solved_count = sum(1 for r in results if r.is_solved)
        self.assertGreater(solved_count, 0)

        total_steps = sum(len(r.proof_steps) for r in results)
        self.assertGreater(total_steps, 0)


def run_tests():
    """运行所有测试"""
    loader = unittest.TestLoader()
    suite = unittest.TestSuite()

    suite.addTests(loader.loadTestsFromTestCase(TestProofState))
    suite.addTests(loader.loadTestsFromTestCase(TestDeductiveEngine))
    suite.addTests(loader.loadTestsFromTestCase(TestProblemGenerator))
    suite.addTests(loader.loadTestsFromTestCase(TestTrainingDataGenerator))
    suite.addTests(loader.loadTestsFromTestCase(TestProofData))
    suite.addTests(loader.loadTestsFromTestCase(TestIntegration))

    runner = unittest.TextTestRunner(verbosity=2)
    result = runner.run(suite)

    return result.wasSuccessful()


if __name__ == "__main__":
    success = run_tests()
    exit(0 if success else 1)
