# GENERATED BY AI
"""渲染引擎和符号引擎的综合测试。"""

import math

from .render_engine import RenderEngine
from .symbolic_engine import SymbolicEngine, ProofState
from .geometry_parser import GeometryParser


def test_render_engine_basic():
    """测试渲染引擎基础功能。"""
    print("\n" + "=" * 60)
    print("测试1: 渲染引擎 - 基础功能")
    print("=" * 60)

    engine = RenderEngine()

    engine.add_point("A", 0, 0)
    engine.add_point("B", 2, 0)
    engine.add_point("C", 1, math.sqrt(3))
    engine.add_point("D", 1, 0)
    engine.add_point("M", 1, 0)

    test_cases = [
        ("coll A B D", True, "共线点"),
        ("midp M A B", True, "中点"),
        ("coll A B C", False, "非共线点"),
        ("perp A B A D", False, "非垂直"),
    ]

    print("\n测试命题:")
    all_passed = True
    for prop_str, expected, desc in test_cases:
        prop = GeometryParser.parse_proposition(prop_str)
        result = engine.verify_proposition(prop)
        passed = result == expected
        status = "✓" if passed else "✗"
        print(f"  {status} {desc}: '{prop_str}' -> {result} (期望 {expected})")
        if not passed:
            all_passed = False

    return all_passed


def test_render_engine_complex():
    """测试渲染引擎复杂案例。"""
    print("\n" + "=" * 60)
    print("测试2: 渲染引擎 - 复杂案例")
    print("=" * 60)

    engine = RenderEngine()

    engine.add_point("A", 0, 0)
    engine.add_point("B", 4, 0)
    engine.add_point("C", 2, 2)
    engine.add_point("D", 2, 0)
    engine.add_point("E", 0, 2)
    engine.add_point("F", 4, 2)

    test_cases = [
        ("para A B E F", True, "平行线"),
        ("perp A B D C", True, "垂直线"),
        ("cong A D D B", True, "全等线段"),
        ("cong A D A B", False, "非全等线段"),
    ]

    print("\n测试复杂命题:")
    all_passed = True
    for prop_str, expected, desc in test_cases:
        prop = GeometryParser.parse_proposition(prop_str)
        result = engine.verify_proposition(prop)
        passed = result == expected
        status = "✓" if passed else "✗"
        print(f"  {status} {desc}: '{prop_str}' -> {result} (期望 {expected})")
        if not passed:
            all_passed = False

    return all_passed


def test_render_engine_new_predicates():
    """测试渲染引擎新增谓词。"""
    print("\n" + "=" * 60)
    print("测试3: 渲染引擎 - 新增谓词")
    print("=" * 60)

    engine = RenderEngine()

    engine.add_point("A", 0, 0)
    engine.add_point("B", 4, 0)
    engine.add_point("C", 2, 2)
    engine.add_point("D", 2, 0)
    engine.add_point("E", 0, 2)
    engine.add_point("F", 4, 2)

    test_cases = [
        ("eqangle A B C D E F G H", True, "等角"),
        ("eqratio A B C D E F G H", True, "等比"),
        ("ncoll A B C", True, "非共线"),
        ("npara A B C D", True, "非平行"),
        ("nperp A B C D", False, "非垂直"),
        ("diff A B", True, "不同点"),
        ("sameside A B C D", True, "同侧"),
    ]

    print("\n测试新增谓词:")
    all_passed = True
    for prop_str, expected, desc in test_cases:
        try:
            prop = GeometryParser.parse_proposition(prop_str)
            result = engine.verify_proposition(prop)
            passed = result == expected
            status = "✓" if passed else "✗"
            print(f"  {status} {desc}: '{prop_str}' -> {result} (期望 {expected})")
            if not passed:
                all_passed = False
        except Exception as e:
            print(f"  ✗ {desc}: '{prop_str}' -> 错误: {e}")
            all_passed = False

    return all_passed


def test_symbolic_engine_basic():
    """测试符号引擎基础功能。"""
    print("\n" + "=" * 60)
    print("测试4: 符号引擎 - 基础功能")
    print("=" * 60)

    engine = SymbolicEngine()

    print("\n添加前提:")
    state = ProofState()
    prop1 = GeometryParser.parse_proposition("perp A B C D")
    prop2 = GeometryParser.parse_proposition("perp E F C D")
    state.add(prop1)
    state.add(prop2)
    print(f"  - {prop1}")
    print(f"  - {prop2}")

    print("\n运行演绎...")
    new_props = engine.deduce(state, max_steps=10)
    print(f"  推导出 {len(new_props)} 条新命题")

    test_cases = [
        ("para A B E F", True, "从垂直线推导平行"),
        ("perp A B C D", True, "原始前提"),
        ("para A B C D", False, "不可推导"),
    ]

    print("\n测试推导:")
    all_passed = True
    for stmt_str, expected, desc in test_cases:
        stmt = GeometryParser.parse_proposition(stmt_str)
        result = state.contains(stmt)
        passed = result == expected
        status = "✓" if passed else "✗"
        print(f"  {status} {desc}: '{stmt_str}' -> {result} (期望 {expected})")
        if not passed:
            all_passed = False

    return all_passed


def test_symbolic_engine_complex():
    """测试符号引擎复杂案例。"""
    print("\n" + "=" * 60)
    print("测试5: 符号引擎 - 复杂案例")
    print("=" * 60)

    engine = SymbolicEngine()

    print("\n添加前提:")
    state = ProofState()
    prop1 = GeometryParser.parse_proposition("midp M A B")
    state.add(prop1)
    print(f"  - {prop1}")

    print("\n运行演绎...")
    new_props = engine.deduce(state, max_steps=10)
    print(f"  推导出 {len(new_props)} 条新命题")

    test_cases = [
        ("cong A M M B", True, "从中点推导全等"),
        ("cong A A B B", True, "自反性全等"),
        ("para A B M B", False, "不可推导"),
    ]

    print("\n测试推导:")
    all_passed = True
    for stmt_str, expected, desc in test_cases:
        stmt = GeometryParser.parse_proposition(stmt_str)
        result = state.contains(stmt)
        passed = result == expected
        status = "✓" if passed else "✗"
        print(f"  {status} {desc}: '{stmt_str}' -> {result} (期望 {expected})")
        if not passed:
            all_passed = False

    return all_passed


def test_symbolic_engine_prove():
    """测试符号引擎证明功能。"""
    print("\n" + "=" * 60)
    print("测试6: 符号引擎 - 证明功能")
    print("=" * 60)

    engine = SymbolicEngine()

    print("\n添加前提:")
    premises = [
        GeometryParser.parse_proposition("perp A B C D"),
        GeometryParser.parse_proposition("perp E F C D"),
    ]
    for prop in premises:
        print(f"  - {prop}")

    target = GeometryParser.parse_proposition("para A B E F")
    print(f"\n目标: {target}")

    can_prove, derived = engine.can_prove(target, premises, max_steps=10)
    print(f"  可以证明: {can_prove}")
    print(f"  推导出的命题数: {len(derived)}")

    if can_prove:
        print("\n  推导出的命题:")
        for i, prop in enumerate(derived[:10]):  # 只显示前10个
            print(f"    {i+1}. {prop}")

    return can_prove


def test_symbolic_engine_rules():
    """测试符号引擎规则加载。"""
    print("\n" + "=" * 60)
    print("测试7: 符号引擎 - 规则加载")
    print("=" * 60)

    engine = SymbolicEngine()

    rules = engine.get_rules()
    print(f"\n已加载 {len(rules)} 条演绎规则")

    print("\n前5条规则:")
    for i, rule in enumerate(rules[:5]):
        print(f"  {i+1}. {rule}")

    return len(rules) > 0


def test_combined_engines():
    """测试渲染引擎和符号引擎的组合使用。"""
    print("\n" + "=" * 60)
    print("测试8: 组合引擎")
    print("=" * 60)

    render_engine = RenderEngine()
    symbolic_engine = SymbolicEngine()

    render_engine.add_point("A", 0, 0)
    render_engine.add_point("B", 2, 0)
    render_engine.add_point("C", 1, math.sqrt(3))
    render_engine.add_point("D", 1, 0)

    state = ProofState()
    prop = GeometryParser.parse_proposition("perp A B C D")
    state.add(prop)

    test_proposition = "perp A B C D"

    print(f"\n测试命题: '{test_proposition}'")

    prop_obj = GeometryParser.parse_proposition(test_proposition)
    render_result = render_engine.verify_proposition(prop_obj)
    print(f"  渲染引擎: {render_result}")

    symbolic_result = state.contains(prop_obj)
    print(f"  符号引擎: {symbolic_result}")

    print("\n✓ 组合引擎测试通过")
    return True


def test_geometry_parser():
    """测试几何语法解析器。"""
    print("\n" + "=" * 60)
    print("测试9: 几何语法解析器")
    print("=" * 60)

    parser = GeometryParser()

    print("\n测试命题解析:")
    test_cases = [
        "perp A B C D",
        "coll A B C",
        "midp M A B",
        "eqangle A B C D E F G H",
        "eqratio A B C D E F G H",
    ]

    all_passed = True
    for prop_str in test_cases:
        try:
            prop = parser.parse_proposition(prop_str)
            print(f"  ✓ 解析成功: '{prop_str}' -> {prop}")
        except Exception as e:
            print(f"  ✗ 解析失败: '{prop_str}' -> {e}")
            all_passed = False

    print("\n测试问题解析:")
    problem_str = "a b c = triangle; h = on_tline b a c ? perp a h b c"
    try:
        problem = parser.parse_problem(problem_str)
        print(f"  ✓ 解析成功:")
        print(f"    构造数: {len(problem.constructions)}")
        print(f"    目标: {problem.goal}")
    except Exception as e:
        print(f"  ✗ 解析失败: {e}")
        all_passed = False

    return all_passed


def main():
    print("\n" + "=" * 60)
    print("几何题推理AI - 引擎测试")
    print("=" * 60)

    results = []

    results.append(("渲染引擎基础", test_render_engine_basic()))
    results.append(("渲染引擎复杂", test_render_engine_complex()))
    results.append(("渲染引擎新增谓词", test_render_engine_new_predicates()))
    results.append(("符号引擎基础", test_symbolic_engine_basic()))
    results.append(("符号引擎复杂", test_symbolic_engine_complex()))
    results.append(("符号引擎证明", test_symbolic_engine_prove()))
    results.append(("符号引擎规则", test_symbolic_engine_rules()))
    results.append(("组合引擎", test_combined_engines()))
    results.append(("几何解析器", test_geometry_parser()))

    print("\n" + "=" * 60)
    print("测试总结")
    print("=" * 60)

    for name, passed in results:
        status = "✓ 通过" if passed else "✗ 失败"
        print(f"  {status}: {name}")

    all_passed = all(passed for _, passed in results)
    print(f"\n总体: {'✓ 所有测试通过' if all_passed else '✗ 部分测试失败'}")
    print("=" * 60)


if __name__ == "__main__":
    main()
