# GENERATED BY AI
"""几何推理系统完整测试套件。"""

import sys
import os

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from geometry_parser import GeometryParser, Proposition, Problem
from extended_render_engine import ExtendedRenderEngine, Point
from extended_symbolic_engine import ExtendedSymbolicEngine
from integrated_workflow import IntegratedGeometrySystem


def print_section(title: str):
    """打印测试部分标题。"""
    print("\n" + "=" * 70)
    print(f"  {title}")
    print("=" * 70)


def test_parser_basic():
    """测试基本解析功能。"""
    print_section("测试 1: 语法解析器 - 基本功能")

    parser = GeometryParser()

    # 测试命题解析
    print("\n--- 命题解析 ---")
    test_props = [
        "perp A B C D",
        "coll A B C",
        "para A B C D",
        "cong A B C D",
        "midp M A B",
        "cyclic A B C D",
        "eqangle A B C D E F",
        "eqratio A B C D E F G H",
        "contri A B C P Q R",
        "simtri A B C P Q R",
    ]

    passed = 0
    for prop_str in test_props:
        prop = parser.parse_proposition(prop_str)
        if prop:
            print(f"✓ {prop_str}")
            passed += 1
        else:
            print(f"✗ {prop_str} -> 解析失败")

    print(f"\n通过: {passed}/{len(test_props)}")


def test_parser_constructions():
    """测试构造解析。"""
    print_section("测试 2: 语法解析器 - 构造解析")

    parser = GeometryParser()

    # 测试构造解析
    print("\n--- 构造解析 ---")
    test_constructions = [
        "on_line X A B",
        "on_tline H B A C",
        "on_circle X O A",
        "intersection_ll X A B C D",
        "intersection_cc X O W A",
        "midpoint M A B",
        "foot H A B C",
    ]

    passed = 0
    for cons_str in test_constructions:
        cons = parser.parse_construction(cons_str)
        if cons:
            print(f"✓ {cons_str}")
            passed += 1
        else:
            print(f"✗ {cons_str} -> 解析失败")

    print(f"\n通过: {passed}/{len(test_constructions)}")


def test_parser_clauses():
    """测试子句解析。"""
    print_section("测试 3: 语法解析器 - 子句解析")

    parser = GeometryParser()

    # 测试子句解析
    print("\n--- 子句解析 ---")
    test_clauses = [
        "a b c = triangle",
        "h = on_tline h b a c, on_tline h c a b",
        "d1 d2 d3 d = incenter2 a b c",
        "x y z i a b c o = 2l1c a b c o",
    ]

    passed = 0
    for clause_str in test_clauses:
        clause = parser.parse_clause(clause_str)
        if clause:
            print(f"✓ {clause_str}")
            passed += 1
        else:
            print(f"✗ {clause_str} -> 解析失败")

    print(f"\n通过: {passed}/{len(test_clauses)}")


def test_parser_problems():
    """测试问题解析。"""
    print_section("测试 4: 语法解析器 - 问题解析")

    parser = GeometryParser()

    # 测试问题解析
    print("\n--- 问题解析 ---")
    problem_text = """orthocenter
a b c = triangle
h = on_tline h b a c, on_tline h c a b ? perp a h b c"""

    problem = parser.parse_problem(problem_text)
    if problem:
        print(f"✓ 问题名称: {problem.name}")
        print(f"  目标: {problem.goal}")
        print(f"  前提数量: {len(problem.premises)}")
    else:
        print("✗ 问题解析失败")


def test_render_engine_basic():
    """测试渲染引擎基本关系。"""
    print_section("测试 5: 渲染引擎 - 基本关系")

    engine = ExtendedRenderEngine()

    # 测试基本关系
    print("\n--- 基本关系 ---")
    engine.points = {
        "A": Point(0, 0),
        "B": Point(1, 0),
        "C": Point(0, 1),
        "D": Point(1, 1),
        "M": Point(0.5, 0),
    }

    tests = [
        ("coll A B C", lambda: engine.verify_collinear([
            engine.points["A"], engine.points["B"], engine.points["C"]
        ])),
        ("para A B C D", lambda: engine.verify_parallel(
            engine.points["A"], engine.points["B"],
            engine.points["C"], engine.points["D"]
        )),
        ("perp A B C D", lambda: engine.verify_perpendicular(
            engine.points["A"], engine.points["B"],
            engine.points["C"], engine.points["D"]
        )),
        ("cong A M M B", lambda: engine.verify_congruent(
            engine.points["A"], engine.points["M"],
            engine.points["M"], engine.points["B"]
        )),
        ("midp M A B", lambda: engine.verify_midpoint(
            engine.points["M"], engine.points["A"], engine.points["B"]
        )),
    ]

    passed = 0
    for prop_str, test_func in tests:
        try:
            result = test_func()
            status = "✓" if result else "✗"
            print(f"{status} {prop_str}")
            if result:
                passed += 1
        except Exception as e:
            print(f"✗ {prop_str} -> 错误: {e}")

    print(f"\n通过: {passed}/{len(tests)}")


def test_render_engine_advanced():
    """测试渲染引擎高级关系。"""
    print_section("测试 6: 渲染引擎 - 高级关系")

    engine = ExtendedRenderEngine()

    # 测试角度关系
    print("\n--- 角度关系 ---")
    engine.points = {
        "A": Point(0, 0),
        "B": Point(1, 0),
        "C": Point(0, 1),
        "D": Point(1, 1),
        "E": Point(0, 0),
        "F": Point(1, 0),
    }

    tests = [
        ("eqangle A B C D E F", lambda: engine.verify_eqangle(
            engine.points["A"], engine.points["B"], engine.points["C"],
            engine.points["D"], engine.points["E"], engine.points["F"]
        )),
    ]

    passed = 0
    for prop_str, test_func in tests:
        try:
            result = test_func()
            status = "✓" if result else "✗"
            print(f"{status} {prop_str}")
            if result:
                passed += 1
        except Exception as e:
            print(f"✗ {prop_str} -> 错误: {e}")

    # 测试比例关系
    print("\n--- 比例关系 ---")
    engine.points = {
        "A": Point(0, 0),
        "B": Point(1, 0),
        "C": Point(0, 0),
        "D": Point(2, 0),
        "E": Point(0, 0),
        "F": Point(1, 0),
        "G": Point(0, 0),
        "H": Point(2, 0),
    }

    tests = [
        ("eqratio A B C D E F G H", lambda: engine.verify_eqratio(
            engine.points["A"], engine.points["B"], engine.points["C"], engine.points["D"],
            engine.points["E"], engine.points["F"], engine.points["G"], engine.points["H"]
        )),
    ]

    for prop_str, test_func in tests:
        try:
            result = test_func()
            status = "✓" if result else "✗"
            print(f"{status} {prop_str}")
            if result:
                passed += 1
        except Exception as e:
            print(f"✗ {prop_str} -> 错误: {e}")

    print(f"\n通过: {passed}/{len(tests)}")


def test_symbolic_engine_basic():
    """测试符号引擎基本规则。"""
    print_section("测试 7: 符号引擎 - 基本规则")

    engine = ExtendedSymbolicEngine()

    print(f"\n加载了 {engine.get_rule_count()} 条演绎规则")

    # 测试垂直到平行规则
    print("\n--- 垂直到平行规则 ---")
    engine.reset()
    engine.add_statement("perp A B C D")
    engine.add_statement("perp E F C D")

    new = engine.deduce()
    print(f"推导出 {new} 条新语句")

    result = engine.verify("para A B E F")
    status = "✓" if result else "✗"
    print(f"{status} 验证 'para A B E F': {result}")


def test_symbolic_engine_advanced():
    """测试符号引擎高级规则。"""
    print_section("测试 8: 符号引擎 - 高级规则")

    engine = ExtendedSymbolicEngine()

    # 测试共圆规则
    print("\n--- 共圆规则 ---")
    engine.reset()
    engine.add_statement("cong O A O B")
    engine.add_statement("cong O B O C")
    engine.add_statement("cong O C O D")

    new = engine.deduce()
    print(f"推导出 {new} 条新语句")

    result = engine.verify("cyclic A B C D")
    status = "✓" if result else "✗"
    print(f"{status} 验证 'cyclic A B C D': {result}")

    # 测试等角规则
    print("\n--- 等角规则 ---")
    engine.reset()
    engine.add_statement("cyclic A B P Q")

    new = engine.deduce()
    print(f"推导出 {new} 条新语句")

    result = engine.verify("eqangle P A P B Q A Q B")
    status = "✓" if result else "✗"
    print(f"{status} 验证 'eqangle P A P B Q A Q B': {result}")


def test_new_predicates():
    """测试新增谓词。"""
    print_section("测试 9: 新增谓词")

    parser = GeometryParser()

    print("\n--- 新增谓词 ---")
    new_predicates = [
        "eqangle6 A B C D E F",
        "eqratio6 A B C D E F G H",
        "contri2 A B C P Q R",
        "simtri2 A B C P Q R",
        "contri* A B C P Q R",
        "simtri* A B C P Q R",
        "sameside A B C D",
        "ncoll A B C",
        "npara A B C D",
        "nperp A B C D",
        "diff A B",
    ]

    passed = 0
    for prop_str in new_predicates:
        prop = parser.parse_proposition(prop_str)
        if prop:
            print(f"✓ {prop_str}")
            passed += 1
        else:
            print(f"✗ {prop_str} -> 解析失败")

    print(f"\n通过: {passed}/{len(new_predicates)}")


def test_new_constructions():
    """测试新增构造。"""
    print_section("测试 10: 新增构造")

    parser = GeometryParser()

    print("\n--- 新增构造 ---")
    new_constructions = [
        "intersection_ll X A B C D",
        "intersection_lc X A O B",
        "intersection_cc X O W A",
        "intersection_lp X A B C M N",
        "intersection_lt X A B C D E",
        "intersection_pp X A B C D E F",
        "intersection_tt X A B C D E F",
        "on_pline X A B C",
        "on_bline X A B",
        "on_aline X A B C D E",
        "on_aline2 X A B C D E",
        "on_dia X A B",
        "on_opline X A B",
        "angle_bisector X A B C",
        "angle_mirror X A B C",
        "eqdistance X A B C",
        "lc_tangent X A O",
        "eqangle2 X A B C",
        "eqangle3 X A B D E F",
        "tangent X Y A O B",
        "on_circum X A B C",
        "circle O A B C",
        "circumcenter X A B C",
        "incenter X A B C",
        "excenter X A B C",
        "incenter2 X Y Z I A B C",
        "excenter2 X Y Z I A B C",
        "centroid X Y Z I A B C",
        "ninepoints X Y Z I A B C",
        "triangle A B C",
        "iso_triangle A B C",
        "r_triangle A B C",
        "triangle12 A B C",
        "ieq_triangle A B C",
        "rectangle A B C D",
        "parallelogram A B C X",
        "trapezoid A B C D",
        "r_trapezoid A B C D",
        "square A B X Y",
        "isquare A B C D",
        "pentagon A B C D E",
        "quadrangle A B C D",
        "eq_quadrangle A B C D",
        "eq_trapezoid A B C D",
        "eqdia_quadrangle A B C D",
        "mirror X A B",
        "reflect X A B C",
        "nsquare X A B",
        "psquare X A B",
        "shift X B C D",
        "eq_triangle X B C",
        "trisect X Y A B C",
        "trisegment X Y A B",
        "cc_tangent0 X Y O A W B",
        "cc_tangent X Y Z I O A W B",
        "2l1c X Y Z I A B C O",
        "e5128 X Y A B C D",
        "3peq X Y Z A B C",
        "segment A B",
    ]

    passed = 0
    for cons_str in new_constructions:
        cons = parser.parse_construction(cons_str)
        if cons:
            print(f"✓ {cons_str}")
            passed += 1
        else:
            print(f"✗ {cons_str} -> 解析失败")

    print(f"\n通过: {passed}/{len(new_constructions)}")


def test_new_rules():
    """测试新增演绎规则。"""
    print_section("测试 11: 新增演绎规则")

    engine = ExtendedSymbolicEngine()

    print(f"\n符号引擎共有 {engine.get_rule_count()} 条规则")

    # 测试一些新规则
    test_cases = [
        ("eqangle6_to_cyclic", ["eqangle6 P A P B Q A Q B", "ncoll P Q A B"], "cyclic A B P Q"),
        ("eqratio_to_cong", ["eqratio A B P Q C D U V", "cong P Q U V"], "cong A B C D"),
        ("eqratio_trans", ["eqratio a b c d m n p q", "eqratio c d e f p q r u"], "eqratio a b e f m n r u"),
        ("cong_to_eqangle", ["cong O A O B", "ncoll O A B"], "eqangle O A A B A B O B"),
        ("eqangle6_to_cong", ["eqangle6 A O A B B A B O", "ncoll O A B"], "cong O A O B"),
    ]

    passed = 0
    for rule_name, premises, expected_conc in test_cases:
        engine.reset()
        for premise in premises:
            engine.add_statement(premise)

        engine.deduce(max_steps=5)

        result = engine.verify(expected_conc)
        status = "✓" if result else "✗"
        print(f"{status} 规则 '{rule_name}': {expected_conc}")
        if result:
            passed += 1

    print(f"\n通过: {passed}/{len(test_cases)}")


def test_examples_txt():
    """测试 examples.txt 中的案例。"""
    print_section("测试 12: examples.txt 中的案例")

    parser = GeometryParser()

    # 读取 examples.txt
    examples_path = os.path.join(
        os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
        "alphageometry-main",
        "examples.txt"
    )

    if not os.path.exists(examples_path):
        print(f"⚠ 未找到 examples.txt: {examples_path}")
        print("使用内置示例...")

        examples = [
            """orthocenter
a b c = triangle
h = on_tline h b a c, on_tline h c a b ? perp a h b c""",
            """orthocenter_aux
a b c = triangle
d = on_tline d b a c, on_tline d c a b
e = on_line e a c, on_line e b d ? perp a d b c""",
            """incenter_excenter
a b c = triangle a b c
d1 d2 d3 d = incenter2 a b c
e1 e2 e3 e = excenter2 a b c ? perp d c c e""",
            """euler
a b c = triangle a b c
h = orthocenter a b c
h1 = foot a b c
h2 = foot b c a
h3 = foot c a b
g1 g2 g3 g = centroid g1 g2 g3 g a b c
o = circle a b c ? coll h g o""",
        ]
    else:
        with open(examples_path, 'r', encoding='utf-8') as f:
            content = f.read()
        problems = parser.parse_problem_file(content)
        examples = [f"{p.name}\n" + '\n'.join(str(clause) for clause in p.premises) +
                  (f"\n? {p.goal}" if p.goal else "") for p in problems]

    passed = 0
    for i, example_text in enumerate(examples, 1):
        print(f"\n--- 示例 {i} ---")
        problem = parser.parse_problem(example_text)

        if problem:
            print(f"✓ 问题名称: {problem.name}")
            print(f"  目标: {problem.goal}")
            print(f"  前提数量: {len(problem.premises)}")
            passed += 1
        else:
            print(f"✗ 示例 {i} 解析失败")

    print(f"\n通过: {passed}/{len(examples)}")


def test_integrated_system():
    """测试集成系统。"""
    print_section("测试 13: 集成系统")

    system = IntegratedGeometrySystem()

    # 打印参数信息
    params = system.count_parameters()
    print("\n模型参数:")
    print(f"  编码器: {params['encoder']:,}")
    print(f"  解码器: {params['decoder']:,}")
    print(f"  推理AI: {params['reasoning_ai']:,}")
    print(f"  总计: {params['total']:,}")
    print(f"  小于0.05M: {params['total'] < 50000}\n")

    # 测试编码
    print("--- 编码测试 ---")
    proposition = "perp A B C D"
    print(f"原始命题: {proposition}")

    try:
        event_vector = system.encode_proposition(proposition)
        print(f"事件向量形状: {event_vector.shape}")
        print("✓ 编码成功")
    except Exception as e:
        print(f"✗ 编码失败: {e}")


def run_all_tests():
    """运行所有测试。"""
    print("\n" + "=" * 70)
    print("几何推理系统完整测试套件")
    print("=" * 70)

    test_results = []

    try:
        test_parser_basic()
        test_parser_constructions()
        test_parser_clauses()
        test_parser_problems()
        test_render_engine_basic()
        test_render_engine_advanced()
        test_symbolic_engine_basic()
        test_symbolic_engine_advanced()
        test_new_predicates()
        test_new_constructions()
        test_new_rules()
        test_examples_txt()
        test_integrated_system()

        print("\n" + "=" * 70)
        print("所有测试完成!")
        print("=" * 70)

    except Exception as e:
        print(f"\n✗ 测试过程中发生错误: {e}")
        import traceback
        traceback.print_exc()


if __name__ == "__main__":
    run_all_tests()
