# GENERATED BY AI
"""几何题推理AI的分词器。

按照空格和符号分词，支持AlphaGeometry格式的几何命题。
"""

import re
from dataclasses import dataclass
from typing import List


@dataclass
class Token:
    """词元数据结构"""

    text: str
    id: int


class GeometryTokenizer:
    """几何命题分词器，支持AlphaGeometry格式"""

    SPECIAL_TOKENS = ["<PAD>", "<UNK>", "<BOS>", "<EOS>", "<SEP>"]
    SYMBOLS = ["=", ";", ",", "(", ")", "?", ":", "{", "}"]

    def __init__(self, vocab_size: int = 400):
        self.vocab_size = vocab_size
        self.token_to_id: dict[str, int] = {}
        self.id_to_token: dict[int, str] = {}
        self._build_vocab()

    def _build_vocab(self):
        idx = 0
        for token in self.SPECIAL_TOKENS:
            self.token_to_id[token] = idx
            self.id_to_token[idx] = token
            idx += 1

        for symbol in self.SYMBOLS:
            self.token_to_id[symbol] = idx
            self.id_to_token[idx] = symbol
            idx += 1

        geometry_keywords = [
            "point",
            "line",
            "circle",
            "triangle",
            "angle",
            "segment",
            "midpoint",
            "perpendicular",
            "parallel",
            "congruent",
            "similar",
            "collinear",
            "cyclic",
            "tangent",
            "radius",
            "center",
            "a",
            "b",
            "c",
            "d",
            "e",
            "f",
            "g",
            "h",
            "i",
            "j",
            "k",
            "l",
            "m",
            "n",
            "o",
            "p",
            "q",
            "r",
            "s",
            "t",
            "u",
            "v",
            "w",
            "x",
            "y",
            "z",
            "A",
            "B",
            "C",
            "D",
            "E",
            "F",
            "G",
            "H",
            "I",
            "J",
            "K",
            "L",
            "M",
            "N",
            "O",
            "P",
            "Q",
            "R",
            "S",
            "T",
            "U",
            "V",
            "W",
            "X",
            "Y",
            "Z",
            "0",
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
            "9",
            "pi",
            "perp",
            "para",
            "cong",
            "coll",
            "cyclic",
            "midp",
            "eqangle",
            "eqratio",
            "simtri",
            "contri",
            "on_line",
            "on_circle",
            "on_pline",
            "on_tline",
            "foot",
            "reflect",
            "bisect",
            "circumcenter",
            "incenter",
            "orthocenter",
            "centroid",
            "ninepoints",
            "free",
            "triangle",
            "quadrangle",
            "trapezoid",
            "rectangle",
            "square",
            "isos",
            "risos",
            "r_triangle",
            "T",
            "P",
            "D",
            "C",
            "O",
            "M",
            "S",
            "R",
            "F1",
            "F2",
            "x00",
            "x01",
            "x02",
            "x03",
            "x04",
            "x05",
        ]

        for keyword in geometry_keywords:
            if keyword not in self.token_to_id and idx < self.vocab_size:
                self.token_to_id[keyword] = idx
                self.id_to_token[idx] = keyword
                idx += 1

        while idx < self.vocab_size:
            token = f"<UNUSED_{idx}>"
            self.token_to_id[token] = idx
            self.id_to_token[idx] = token
            idx += 1

    def tokenize(self, text: str) -> List[str]:
        text = str(text)
        pattern = r"(\s+|" + "|".join(re.escape(s) for s in self.SYMBOLS) + r")"
        tokens = []
        for part in re.split(pattern, text):
            if part.strip():
                tokens.append(part)
            elif part in self.SYMBOLS:
                tokens.append(part)
        return [t for t in tokens if t]

    def encode(self, text: str) -> List[int]:
        tokens = self.tokenize(text)
        return [
            self.token_to_id.get(token, self.token_to_id["<UNK>"]) for token in tokens
        ]

    def decode(self, ids: List[int]) -> str:
        tokens = []
        for id_ in ids:
            if id_ in self.id_to_token:
                token = self.id_to_token[id_]
                if token not in self.SPECIAL_TOKENS and not token.startswith(
                    "<UNUSED_"
                ):
                    tokens.append(token)
            else:
                tokens.append("<UNK>")
        return " ".join(tokens)

    def encode_with_special(
        self, text: str, add_bos: bool = True, add_eos: bool = True
    ) -> List[int]:
        ids = []
        if add_bos:
            ids.append(self.token_to_id["<BOS>"])
        ids.extend(self.encode(text))
        if add_eos:
            ids.append(self.token_to_id["<EOS>"])
        return ids

    @property
    def pad_id(self) -> int:
        return self.token_to_id["<PAD>"]

    @property
    def unk_id(self) -> int:
        return self.token_to_id["<UNK>"]

    @property
    def bos_id(self) -> int:
        return self.token_to_id["<BOS>"]

    @property
    def eos_id(self) -> int:
        return self.token_to_id["<EOS>"]

    def __len__(self) -> int:
        return self.vocab_size
