# GENERATED BY AI
"""几何题推理AI的训练策略。

包含编码器-解码器联合训练、监督训练和强化学习训练三种训练方式。
"""

import random
from collections import deque
from dataclasses import dataclass
from typing import TYPE_CHECKING, Any, Dict, List, Optional, Tuple

import torch
from torch import nn
from torch.optim import Adam

try:
    from .config import SystemConfig, TrainingConfig, get_default_config
    from .event_system import Event
    from .models import Decoder, Encoder
    from .tokenizer import GeometryTokenizer
    from .workflow import ReasoningStep
except ImportError:
    from config import SystemConfig, TrainingConfig, get_default_config
    from event_system import Event
    from models import Decoder, Encoder
    from tokenizer import GeometryTokenizer
    from workflow import ReasoningStep

if TYPE_CHECKING:
    from .workflow import GeometryReasoningSystem


@dataclass
class RewardConfig:
    """奖励配置

    注意：step_penalty 仅用于推理阶段，不参与RL训练。
    推理阶段的步数惩罚在 workflow.py 中实现。
    """

    render_success: float = 0.5
    render_failure: float = -0.1
    symbolic_success: float = 1.0
    symbolic_failure: float = -0.2
    proof_success: float = 5.0
    proof_failure: float = -2.0
    repeat_penalty: float = -0.05
    # 连续不调用符号引擎的惩罚配置
    consecutive_no_symbolic_base: float = -0.0  # 连续不调用符号引擎的基础惩罚
    consecutive_no_symbolic_increment: float = -0.1  # 每多一步增加的惩罚


class EncoderDecoderTrainer:
    """编码器-解码器联合训练器"""

    def __init__(
        self,
        encoder: Encoder,
        decoder: Decoder,
        tokenizer: GeometryTokenizer,
        config: TrainingConfig,
    ):
        self.encoder = encoder
        self.decoder = decoder
        self.tokenizer = tokenizer
        self.config = config

        self.encoder_optimizer = Adam(encoder.parameters(), lr=config.learning_rate)
        self.decoder_optimizer = Adam(decoder.parameters(), lr=config.learning_rate)

        self.loss_fn = nn.CrossEntropyLoss(ignore_index=tokenizer.pad_id)

    def generate_random_statement(self) -> str:
        """生成随机几何命题"""
        templates = [
            ("perp {p1} {p2} {p3} {p4}", 4),
            ("para {p1} {p2} {p3} {p4}", 4),
            ("cong {p1} {p2} {p3} {p4}", 4),
            ("coll {p1} {p2} {p3}", 3),
            ("midp {p1} {p2} {p3}", 3),
            ("cyclic {p1} {p2} {p3} {p4}", 4),
        ]

        points = list("ABCDEFGH")
        template, num_points = random.choice(templates)
        selected = random.sample(points, num_points)

        return template.format(**{f"p{i+1}": p for i, p in enumerate(selected)})

    def train_step(self, statements: Optional[List[str]] = None) -> float:
        """执行单步训练"""
        if statements is None:
            statements = [
                self.generate_random_statement() for _ in range(self.config.batch_size)
            ]

        self.encoder_optimizer.zero_grad()
        self.decoder_optimizer.zero_grad()

        total_loss = 0.0

        for stmt in statements:
            token_ids = self.tokenizer.encode_with_special(stmt)
            input_tensor = torch.tensor([token_ids], dtype=torch.long)

            target_ids = token_ids[1:]
            target_tensor = torch.tensor([target_ids], dtype=torch.long)

            decoder_input = input_tensor[:, :-1]
            event_vector = self.encoder(input_tensor)
            memory = event_vector.unsqueeze(1)
            logits = self.decoder(decoder_input, memory)

            min_len = min(logits.size(1), target_tensor.size(1))
            logits = logits[:, :min_len, :]
            target_tensor = target_tensor[:, :min_len]

            loss = self.loss_fn(
                logits.view(-1, logits.size(-1)), target_tensor.view(-1)
            )

            total_loss += loss.item()
            loss.backward()

        self.decoder_optimizer.step()

        return total_loss / len(statements)

    def train_joint(
        self, num_epochs: int = 10, statements_per_epoch: int = 100
    ) -> List[float]:
        """联合训练编码器和解码器"""
        losses = []

        for epoch in range(num_epochs):
            epoch_loss = 0.0

            for _ in range(statements_per_epoch // self.config.batch_size):
                statements = [
                    self.generate_random_statement()
                    for _ in range(self.config.batch_size)
                ]
                loss = self.train_step(statements)
                epoch_loss += loss

            avg_loss = epoch_loss / (statements_per_epoch // self.config.batch_size)
            losses.append(avg_loss)

            if (epoch + 1) % 5 == 0:
                print(f"联合训练轮次 {epoch + 1}/{num_epochs}, 损失: {avg_loss:.4f}")

        return losses


class SupervisedTrainer:
    """监督训练器"""

    def __init__(self, system: "GeometryReasoningSystem", config: TrainingConfig):
        self.system = system
        self.config = config

        self.encoder_optimizer = Adam(
            system.encoder.parameters(), lr=config.learning_rate
        )
        self.decoder_optimizer = Adam(
            system.decoder.parameters(), lr=config.learning_rate
        )
        self.reasoning_optimizer = Adam(
            system.reasoning_ai.parameters(), lr=config.learning_rate
        )

        self.tokenizer = system.tokenizer
        self.loss_fn = nn.CrossEntropyLoss(ignore_index=system.tokenizer.pad_id)

    def train_step(self, problem: str, solution_steps: List[str]) -> Dict[str, float]:
        """执行单步监督训练"""
        losses: Dict[str, float] = {}

        self.encoder_optimizer.zero_grad()
        self.decoder_optimizer.zero_grad()
        self.reasoning_optimizer.zero_grad()

        initial_event = self.system.create_initial_event(problem)
        event_vector = initial_event.event_vector

        decoder_loss: torch.Tensor = torch.tensor(0.0)
        for step in solution_steps:
            token_ids = self.tokenizer.encode_with_special(step)
            input_tensor = torch.tensor([token_ids], dtype=torch.long)

            memory = event_vector.unsqueeze(1)
            decoder_input = input_tensor[:, :-1]

            logits = self.system.decoder(decoder_input, memory)

            target_ids = token_ids[1:]
            target_tensor = torch.tensor([target_ids], dtype=torch.long)

            min_len = min(logits.size(1), target_tensor.size(1))
            logits = logits[:, :min_len, :]
            target_tensor = target_tensor[:, :min_len]

            loss = self.loss_fn(
                logits.view(-1, logits.size(-1)), target_tensor.view(-1)
            )
            decoder_loss = decoder_loss + loss

        decoder_loss = decoder_loss / len(solution_steps)
        losses["decoder_loss"] = decoder_loss.item()

        decoder_loss.backward()
        self.decoder_optimizer.step()

        return losses

    def train_epoch(self, problems: List[Tuple[str, List[str]]]) -> Dict[str, float]:
        """训练一个epoch"""
        total_decoder_loss = 0.0

        for problem, solution in problems:
            losses = self.train_step(problem, solution)
            total_decoder_loss += losses["decoder_loss"]

        return {"decoder_loss": total_decoder_loss / len(problems)}


class RLTrainer:
    """强化学习训练器"""

    def __init__(
        self,
        system: "GeometryReasoningSystem",
        config: TrainingConfig,
        reward_config: Optional[RewardConfig] = None,
    ):
        self.system = system
        self.config = config
        self.reward_config = (
            reward_config if reward_config is not None else RewardConfig()
        )

        self.optimizer = Adam(system.reasoning_ai.parameters(), lr=config.learning_rate)

        self.recent_statements: deque = deque(maxlen=10)
        self.gamma = 0.99

    def compute_reward(
        self,
        step_result: ReasoningStep,
        is_proof_complete: bool,
        is_repeat: bool,
        consecutive_no_symbolic: int = 0,
    ) -> float:
        """计算奖励值（RL训练用，不包含步数惩罚）

        注意：步数惩罚仅在推理阶段应用，不参与RL训练。

        Args:
            step_result: 推理步骤结果
            is_proof_complete: 是否完成证明
            is_repeat: 是否重复命题
            consecutive_no_symbolic: 连续不调用符号引擎的步数

        Returns:
            奖励值
        """
        reward = 0.0

        if is_repeat:
            reward += self.reward_config.repeat_penalty

        if step_result.render_valid is not None:
            if step_result.render_valid:
                reward += self.reward_config.render_success
            else:
                reward += self.reward_config.render_failure

        if step_result.symbolic_valid is not None:
            if step_result.symbolic_valid:
                reward += self.reward_config.symbolic_success
            else:
                reward += self.reward_config.symbolic_failure

        if is_proof_complete:
            reward += self.reward_config.proof_success

        # 连续不调用符号引擎的惩罚（绝对值逐渐变大）
        if consecutive_no_symbolic > 0:
            penalty = (
                self.reward_config.consecutive_no_symbolic_base
                + self.reward_config.consecutive_no_symbolic_increment
                * (consecutive_no_symbolic - 1)
            )
            reward += penalty

        return reward

    def train_episode(
        self,
        initial_proposition: str,
        target: Optional[str] = None,
        max_steps: int = 20,
    ) -> Tuple[float, int]:
        """执行一个训练回合"""
        self.system.reset()

        initial_event = self.system.create_initial_event(initial_proposition)
        self.system.event_sequence.add_event(initial_event)

        rewards: List[float] = []
        log_probs: List[torch.Tensor] = []
        control_signals: List[torch.Tensor] = []  # 保存控制信号用于梯度引导
        needs_guidance: List[bool] = []  # 记录哪些步骤需要引导梯度
        consecutive_no_symbolic = 0  # 连续不调用符号引擎的步数

        for _ in range(max_steps):
            encoded_sequence = self.system.event_sequence.get_sequence_tensor()

            event_vector, control_signal = self.system.reasoning_ai(encoded_sequence)

            control_log_prob = torch.log(control_signal + 1e-10).sum()
            log_probs.append(control_log_prob)
            control_signals.append(control_signal.clone())  # 保存控制信号

            use_render = control_signal[0, 0].item() > 0.5
            use_decoder = control_signal[0, 1].item() > 0.5
            decoded_statement: Optional[str] = None
            symbolic_valid: Optional[bool] = None
            render_valid: Optional[bool] = None

            if use_decoder:
                decoded_statement = self.system.decode_event(event_vector)
                try:
                    from .geometry_parser import GeometryParser

                    prop = GeometryParser.parse_proposition(decoded_statement)
                    if use_render:
                        # 使用渲染引擎验证
                        is_valid = self.system.render_engine.verify_proposition(prop)
                        render_valid = is_valid
                    else:
                        # 使用符号引擎验证
                        is_valid = self.system.symbolic_engine.verify_proposition(prop)
                        symbolic_valid = is_valid
                except Exception:
                    is_valid = False
                    if use_render:
                        render_valid = False
                    else:
                        symbolic_valid = False

            # 跟踪连续不调用符号引擎的步数
            # 判断条件：生成了命题但没有调用符号引擎检查（即没有解码，或者解码后使用了渲染引擎）
            generated_proposition = decoded_statement is not None
            used_symbolic_check = (
                use_decoder and not use_render and symbolic_valid is not None
            )

            if generated_proposition and not used_symbolic_check:
                consecutive_no_symbolic += 1
            else:
                consecutive_no_symbolic = 0

            # 记录是否需要引导梯度（连续不调用符号引擎检查时需要）
            needs_guidance.append(generated_proposition and not used_symbolic_check)

            is_repeat = (
                decoded_statement in self.recent_statements
                if decoded_statement
                else False
            )
            if decoded_statement:
                self.recent_statements.append(decoded_statement)

            is_complete = False
            if target and decoded_statement:
                target_tokens = set(self.system.tokenizer.tokenize(target))
                stmt_tokens = set(self.system.tokenizer.tokenize(decoded_statement))
                is_complete = target_tokens.issubset(stmt_tokens)

            step_result = ReasoningStep(
                event_vector=event_vector,
                control_signal=control_signal,
                decoded_statement=decoded_statement,
                symbolic_valid=symbolic_valid,
                render_valid=render_valid,
                used_symbolic_check=used_symbolic_check,
            )

            reward = self.compute_reward(
                step_result, is_complete, is_repeat, consecutive_no_symbolic
            )
            rewards.append(reward)

            new_event = Event(
                event_vector=event_vector, is_success=symbolic_valid or render_valid
            )
            self.system.event_sequence.add_event(new_event)

            if is_complete:
                break

        returns: List[float] = []
        R = 0.0
        for r in reversed(rewards):
            R = r + self.gamma * R
            returns.insert(0, R)

        returns_tensor = torch.tensor(returns)
        if len(returns) > 1:
            returns_tensor = (returns_tensor - returns_tensor.mean()) / (
                returns_tensor.std() + 1e-10
            )

        policy_loss: torch.Tensor = torch.tensor(0.0)
        for log_prob, R in zip(log_probs, returns_tensor):
            policy_loss = policy_loss - log_prob * R

        # 连续不调用符号引擎时，添加引导梯度使"调用符号引擎位"趋向1
        # control_signal[1] 是解码器控制位，应趋向1
        symbolic_guidance_loss: torch.Tensor = torch.tensor(0.0)
        guidance_count = 0
        for control_signal, need_guidance in zip(control_signals, needs_guidance):
            if need_guidance:
                # 对于需要引导的步骤，添加梯度引导
                # 目标：解码器控制位趋向1（调用解码器）
                target_decoder = torch.ones_like(
                    control_signal[0, 1:2]
                )  # 解码器位目标为1

                # 使用 BCE loss 引导控制信号
                decoder_loss = torch.nn.functional.binary_cross_entropy(
                    control_signal[0, 1:2],  # 解码器控制位
                    target_decoder,
                    reduction="sum",
                )
                symbolic_guidance_loss = symbolic_guidance_loss + decoder_loss
                guidance_count += 1

        # 将引导损失添加到策略损失中，使用较小的权重
        # 只有在需要引导时才添加
        if guidance_count > 0:
            guidance_weight = 0.1
            total_loss = policy_loss + guidance_weight * symbolic_guidance_loss
        else:
            total_loss = policy_loss

        self.optimizer.zero_grad()
        total_loss.backward()
        torch.nn.utils.clip_grad_norm_(
            self.system.reasoning_ai.parameters(), self.config.max_grad_norm
        )
        self.optimizer.step()

        return sum(rewards), len(rewards)

    def train(
        self, problems: List[Tuple[str, str]], num_epochs: int = 10
    ) -> List[float]:
        """执行强化学习训练"""
        episode_rewards = []

        for epoch in range(num_epochs):
            epoch_reward = 0.0

            for initial_prop, target in problems:
                reward, _ = self.train_episode(initial_prop, target)
                epoch_reward += reward

            avg_reward = epoch_reward / len(problems)
            episode_rewards.append(avg_reward)

            if (epoch + 1) % 5 == 0:
                print(
                    f"强化学习训练轮次 {epoch + 1}/{num_epochs}, 平均奖励: {avg_reward:.4f}"
                )

        return episode_rewards


class TrainingPipeline:
    """训练流水线，整合所有训练方式"""

    def __init__(
        self, system: "GeometryReasoningSystem", config: Optional[SystemConfig] = None
    ):
        self.system = system
        self.config = config if config is not None else get_default_config()

        self.encoder_decoder_trainer = EncoderDecoderTrainer(
            system.encoder, system.decoder, system.tokenizer, self.config.training
        )

        self.supervised_trainer = SupervisedTrainer(system, self.config.training)

        self.rl_trainer = RLTrainer(system, self.config.training)

    def pretrain_encoder_decoder(self, num_epochs: int = 20) -> List[float]:
        """预训练编码器-解码器"""
        print("预训练编码器-解码器...")
        losses = self.encoder_decoder_trainer.train_joint(num_epochs=num_epochs)
        return losses

    def supervised_training(
        self, problems: List[Tuple[str, List[str]]], num_epochs: int = 10
    ) -> List[Dict[str, float]]:
        """监督训练"""
        print("运行监督训练...")

        all_losses: List[Dict[str, float]] = []
        for epoch in range(num_epochs):
            losses = self.supervised_trainer.train_epoch(problems)
            all_losses.append(losses)

            if (epoch + 1) % 5 == 0:
                print(
                    f"监督训练轮次 {epoch + 1}/{num_epochs}, 损失: {losses['decoder_loss']:.4f}"
                )

        return all_losses

    def rl_training(
        self, problems: List[Tuple[str, str]], num_epochs: int = 10
    ) -> List[float]:
        """强化学习训练"""
        print("运行强化学习训练...")
        rewards = self.rl_trainer.train(problems, num_epochs=num_epochs)
        return rewards

    def full_training(
        self,
        pretrain_epochs: int = 10,
        supervised_epochs: int = 10,
        rl_epochs: int = 10,
        supervised_problems: Optional[List[Tuple[str, List[str]]]] = None,
        rl_problems: Optional[List[Tuple[str, str]]] = None,
    ) -> Dict[str, Any]:
        """完整训练流程"""
        results: Dict[str, Any] = {}

        results["pretrain"] = self.pretrain_encoder_decoder(num_epochs=pretrain_epochs)

        if supervised_problems:
            results["supervised"] = self.supervised_training(
                supervised_problems, num_epochs=supervised_epochs
            )

        if rl_problems:
            results["rl"] = self.rl_training(rl_problems, num_epochs=rl_epochs)

        return results


if __name__ == "__main__":
    try:
        from . import workflow as _workflow_module
    except ImportError:
        import workflow as _workflow_module

    system = _workflow_module.GeometryReasoningSystem()
    pipeline = TrainingPipeline(system)

    print("预训练编码器-解码器...")
    pretrain_losses = pipeline.pretrain_encoder_decoder(num_epochs=5)
    print(f"预训练损失: {pretrain_losses}")

    print("\n模型参数:")
    params = system.count_parameters()
    print(f"总计: {params['total']:,}")
