# GENERATED BY GLM
"""几何题推理AI的训练策略。"""

import torch
from torch import nn
from torch.optim import Adam
from typing import List, Tuple, Optional, Dict, Any
from dataclasses import dataclass
from collections import deque
import random

try:
    from .config import SystemConfig, TrainingConfig, get_default_config
    from .models import Encoder, Decoder
    from .tokenizer import GeometryTokenizer
    from .event_system import Event
    from .integrated_workflow import ReasoningStep
except ImportError:
    from config import SystemConfig, TrainingConfig, get_default_config
    from models import Encoder, Decoder
    from tokenizer import GeometryTokenizer
    from event_system import Event
    from integrated_workflow import ReasoningStep


@dataclass
class RewardConfig:
    step_penalty: float = -0.01
    render_success: float = 0.5
    render_failure: float = -0.1
    symbolic_success: float = 1.0
    symbolic_failure: float = -0.2
    proof_success: float = 5.0
    proof_failure: float = -2.0
    repeat_penalty: float = -0.05


class EncoderDecoderTrainer:
    def __init__(
        self,
        encoder: Encoder,
        decoder: Decoder,
        tokenizer: GeometryTokenizer,
        config: TrainingConfig,
    ):
        self.encoder = encoder
        self.decoder = decoder
        self.tokenizer = tokenizer
        self.config = config

        self.encoder_optimizer = Adam(encoder.parameters(), lr=config.learning_rate)
        self.decoder_optimizer = Adam(decoder.parameters(), lr=config.learning_rate)

        self.loss_fn = nn.CrossEntropyLoss(ignore_index=tokenizer.pad_id)

    def generate_random_statement(self) -> str:
        templates = [
            ("perp {p1} {p2} {p3} {p4}", 4),
            ("para {p1} {p2} {p3} {p4}", 4),
            ("cong {p1} {p2} {p3} {p4}", 4),
            ("coll {p1} {p2} {p3}", 3),
            ("midp {p1} {p2} {p3}", 3),
            ("cyclic {p1} {p2} {p3} {p4}", 4),
        ]

        points = list("ABCDEFGH")

        template, num_points = random.choice(templates)
        selected = random.sample(points, num_points)

        return template.format(**{f"p{i+1}": p for i, p in enumerate(selected)})

    def train_step(self, statements: Optional[List[str]] = None) -> float:
        if statements is None:
            statements = [
                self.generate_random_statement() for _ in range(self.config.batch_size)
            ]

        self.encoder_optimizer.zero_grad()
        self.decoder_optimizer.zero_grad()

        total_loss = 0.0

        for stmt in statements:
            token_ids = self.tokenizer.encode_with_special(stmt)
            input_tensor = torch.tensor([token_ids], dtype=torch.long)

            target_ids = token_ids[1:]
            target_tensor = torch.tensor([target_ids], dtype=torch.long)

            decoder_input = input_tensor[:, :-1]

            event_vector = self.encoder(input_tensor)

            memory = event_vector.unsqueeze(1)

            logits = self.decoder(decoder_input, memory)

            min_len = min(logits.size(1), target_tensor.size(1))
            logits = logits[:, :min_len, :]
            target_tensor = target_tensor[:, :min_len]

            loss = self.loss_fn(
                logits.view(-1, logits.size(-1)), target_tensor.view(-1)
            )

            total_loss += loss.item()

            loss.backward()

        self.decoder_optimizer.step()

        return total_loss / len(statements)

    def train_joint(
        self, num_epochs: int = 10, statements_per_epoch: int = 100
    ) -> List[float]:
        losses = []

        for epoch in range(num_epochs):
            epoch_loss = 0.0

            for _ in range(statements_per_epoch // self.config.batch_size):
                statements = [
                    self.generate_random_statement()
                    for _ in range(self.config.batch_size)
                ]
                loss = self.train_step(statements)
                epoch_loss += loss

            avg_loss = epoch_loss / (statements_per_epoch // self.config.batch_size)
            losses.append(avg_loss)

            if (epoch + 1) % 5 == 0:
                print(f"联合训练轮次 {epoch + 1}/{num_epochs}, 损失: {avg_loss:.4f}")

        return losses


class SupervisedTrainer:
    def __init__(self, system: Any, config: TrainingConfig):
        self.system = system
        self.config = config

        self.encoder_optimizer = Adam(
            system.encoder.parameters(), lr=config.learning_rate
        )
        self.decoder_optimizer = Adam(
            system.decoder.parameters(), lr=config.learning_rate
        )
        self.reasoning_optimizer = Adam(
            system.reasoning_ai.parameters(), lr=config.learning_rate
        )

        self.tokenizer = system.tokenizer
        self.loss_fn = nn.CrossEntropyLoss(ignore_index=system.tokenizer.pad_id)

    def train_step(  # pylint: disable=too-many-locals
        self, problem: str, solution_steps: List[str]
    ) -> Dict[str, float]:
        losses: Dict[str, float] = {}

        self.encoder_optimizer.zero_grad()
        self.decoder_optimizer.zero_grad()
        self.reasoning_optimizer.zero_grad()

        initial_event = self.system.create_initial_event(problem)
        event_vector = initial_event.event_vector

        decoder_loss: torch.Tensor = torch.tensor(0.0)
        for step in solution_steps:
            token_ids = self.tokenizer.encode_with_special(step)
            input_tensor = torch.tensor([token_ids], dtype=torch.long)

            memory = event_vector.unsqueeze(1)
            decoder_input = input_tensor[:, :-1]

            logits = self.system.decoder(decoder_input, memory)

            target_ids = token_ids[1:]
            target_tensor = torch.tensor([target_ids], dtype=torch.long)

            min_len = min(logits.size(1), target_tensor.size(1))
            logits = logits[:, :min_len, :]
            target_tensor = target_tensor[:, :min_len]

            loss = self.loss_fn(
                logits.view(-1, logits.size(-1)), target_tensor.view(-1)
            )
            decoder_loss = decoder_loss + loss

        decoder_loss = decoder_loss / len(solution_steps)
        losses["decoder_loss"] = decoder_loss.item()

        decoder_loss.backward()
        self.decoder_optimizer.step()

        return losses

    def train_epoch(self, problems: List[Tuple[str, List[str]]]) -> Dict[str, float]:
        total_decoder_loss = 0.0

        for problem, solution in problems:
            losses = self.train_step(problem, solution)
            total_decoder_loss += losses["decoder_loss"]

        return {"decoder_loss": total_decoder_loss / len(problems)}


class RLTrainer:
    def __init__(
        self,
        system: Any,
        config: TrainingConfig,
        reward_config: Optional[RewardConfig] = None,
    ):
        self.system = system
        self.config = config
        self.reward_config = (
            reward_config if reward_config is not None else RewardConfig()
        )

        self.optimizer = Adam(system.reasoning_ai.parameters(), lr=config.learning_rate)

        self.recent_statements: deque = deque(maxlen=10)
        self.gamma = 0.99

    def compute_reward(
        self, step_result: Any, is_proof_complete: bool, is_repeat: bool
    ) -> float:
        reward = self.reward_config.step_penalty

        if is_repeat:
            reward += self.reward_config.repeat_penalty

        if step_result.render_valid is not None:
            if step_result.render_valid:
                reward += self.reward_config.render_success
            else:
                reward += self.reward_config.render_failure

        if step_result.symbolic_valid is not None:
            if step_result.symbolic_valid:
                reward += self.reward_config.symbolic_success
            else:
                reward += self.reward_config.symbolic_failure

        if is_proof_complete:
            reward += self.reward_config.proof_success
        elif step_result.decoded_statement is None:
            pass

        return reward

    def train_episode(  # pylint: disable=too-many-locals
        self,
        initial_proposition: str,
        target: Optional[str] = None,
        max_steps: int = 20,
    ) -> Tuple[float, int]:
        self.system.reset()

        initial_event = self.system.create_initial_event(initial_proposition)
        self.system.event_sequence.add_event(initial_event)

        rewards: List[float] = []
        log_probs: List[torch.Tensor] = []

        for _ in range(max_steps):
            encoded_sequence = self.system.event_sequence.get_position_encoded()

            event_vector, control_signal = self.system.reasoning_ai(encoded_sequence)

            control_log_prob = torch.log(control_signal + 1e-10).sum()
            log_probs.append(control_log_prob)

            use_decoder = control_signal[0, 1].item() > 0.5
            decoded_statement: Optional[str] = None
            symbolic_valid: Optional[bool] = None
            render_valid: Optional[bool] = None

            if use_decoder:
                decoded_statement = self.system.decode_event(event_vector)

                is_valid, _ = self.system.symbolic_engine.can_derive(decoded_statement)
                symbolic_valid = is_valid

            is_repeat = (
                decoded_statement in self.recent_statements
                if decoded_statement
                else False
            )
            if decoded_statement:
                self.recent_statements.append(decoded_statement)

            is_complete = False
            if target and decoded_statement:
                target_tokens = set(self.system.tokenizer.tokenize(target))
                stmt_tokens = set(self.system.tokenizer.tokenize(decoded_statement))
                is_complete = target_tokens.issubset(stmt_tokens)

            step_result = ReasoningStep(
                event_vector=event_vector,
                control_signal=control_signal,
                decoded_statement=decoded_statement,
                symbolic_valid=symbolic_valid,
                render_valid=render_valid,
            )

            reward = self.compute_reward(step_result, is_complete, is_repeat)
            rewards.append(reward)

            new_event = Event(
                event_vector=event_vector, is_success=symbolic_valid or render_valid
            )
            self.system.event_sequence.add_event(new_event)

            if is_complete:
                break

        returns: List[float] = []
        R = 0.0
        for r in reversed(rewards):
            R = r + self.gamma * R
            returns.insert(0, R)

        returns_tensor = torch.tensor(returns)
        if len(returns) > 1:
            returns_tensor = (returns_tensor - returns_tensor.mean()) / (
                returns_tensor.std() + 1e-10
            )

        policy_loss: torch.Tensor = torch.tensor(0.0)
        for log_prob, R in zip(log_probs, returns_tensor):
            policy_loss = policy_loss - log_prob * R

        self.optimizer.zero_grad()
        policy_loss.backward()
        torch.nn.utils.clip_grad_norm_(
            self.system.reasoning_ai.parameters(), self.config.max_grad_norm
        )
        self.optimizer.step()

        return sum(rewards), len(rewards)

    def train(
        self, problems: List[Tuple[str, str]], num_epochs: int = 10
    ) -> List[float]:
        episode_rewards = []

        for epoch in range(num_epochs):
            epoch_reward = 0.0

            for initial_prop, target in problems:
                reward, _ = self.train_episode(initial_prop, target)
                epoch_reward += reward

            avg_reward = epoch_reward / len(problems)
            episode_rewards.append(avg_reward)

            if (epoch + 1) % 5 == 0:
                print(
                    f"强化学习训练轮次 {epoch + 1}/{num_epochs}, 平均奖励: {avg_reward:.4f}"
                )

        return episode_rewards


class TrainingPipeline:
    def __init__(self, system: Any, config: Optional[SystemConfig] = None):
        self.system = system
        self.config = config if config is not None else get_default_config()

        self.encoder_decoder_trainer = EncoderDecoderTrainer(
            system.encoder, system.decoder, system.tokenizer, self.config.training
        )

        self.supervised_trainer = SupervisedTrainer(system, self.config.training)

        self.rl_trainer = RLTrainer(system, self.config.training)

    def pretrain_encoder_decoder(self, num_epochs: int = 20) -> List[float]:
        print("预训练编码器-解码器...")
        losses = self.encoder_decoder_trainer.train_joint(num_epochs=num_epochs)
        return losses

    def supervised_training(
        self, problems: List[Tuple[str, List[str]]], num_epochs: int = 10
    ) -> List[Dict[str, float]]:
        print("运行监督训练...")

        all_losses: List[Dict[str, float]] = []
        for epoch in range(num_epochs):
            losses = self.supervised_trainer.train_epoch(problems)
            all_losses.append(losses)

            if (epoch + 1) % 5 == 0:
                print(
                    f"监督训练轮次 {epoch + 1}/{num_epochs}, 损失: {losses['decoder_loss']:.4f}"
                )

        return all_losses

    def rl_training(
        self, problems: List[Tuple[str, str]], num_epochs: int = 10
    ) -> List[float]:
        print("运行强化学习训练...")
        rewards = self.rl_trainer.train(problems, num_epochs=num_epochs)
        return rewards

    def full_training(  # pylint: disable=too-many-arguments,too-many-positional-arguments
        self,
        pretrain_epochs: int = 10,
        supervised_epochs: int = 10,
        rl_epochs: int = 10,
        supervised_problems: Optional[List[Tuple[str, List[str]]]] = None,
        rl_problems: Optional[List[Tuple[str, str]]] = None,
    ) -> Dict[str, Any]:

        results: Dict[str, Any] = {}

        results["pretrain"] = self.pretrain_encoder_decoder(num_epochs=pretrain_epochs)

        if supervised_problems:
            results["supervised"] = self.supervised_training(
                supervised_problems, num_epochs=supervised_epochs
            )

        if rl_problems:
            results["rl"] = self.rl_training(rl_problems, num_epochs=rl_epochs)

        return results


if __name__ == "__main__":
    from .integrated_workflow import IntegratedGeometrySystem

    system = GeometryReasoningSystem()
    pipeline = TrainingPipeline(system)

    print("预训练编码器-解码器...")
    pretrain_losses = pipeline.pretrain_encoder_decoder(num_epochs=5)
    print(f"预训练损失: {pretrain_losses}")

    print("\n模型参数:")
    params = system.count_parameters()
    print(f"总计: {params['total']:,}")
