# GENERATED BY GLM
"""几何题推理AI的主要工作流程。"""

import torch
from torch import nn
from typing import Optional, List, Tuple, Dict
from dataclasses import dataclass

from .config import SystemConfig, get_default_config
from .event_system import Event, EventSequence
from .tokenizer import GeometryTokenizer
from .models import Encoder, Decoder, ReasoningAI
from .render_engine import RenderEngine
from .symbolic_engine import SymbolicEngine
from .proposition_manager import PropositionManager
from .geometry_parser import GeometryParser, Proposition


@dataclass
class ReasoningStep:
    event_vector: torch.Tensor
    control_signal: torch.Tensor
    decoded_statement: Optional[str] = None
    symbolic_valid: Optional[bool] = None
    render_valid: Optional[bool] = None


class GeometryReasoningSystem:
    def __init__(self, config: Optional[SystemConfig] = None):
        self.config = config if config is not None else get_default_config()

        self.tokenizer = GeometryTokenizer(vocab_size=self.config.encoder.vocab_size)

        self.encoder = Encoder(
            vocab_size=self.config.encoder.vocab_size,
            embed_dim=self.config.encoder.embed_dim,
            num_heads=self.config.encoder.num_heads,
            num_layers=self.config.encoder.num_layers,
            ffn_dim=self.config.encoder.ffn_dim,
            max_seq_len=self.config.encoder.max_seq_len,
            dropout=self.config.encoder.dropout,
        )

        self.decoder = Decoder(
            vocab_size=self.config.decoder.vocab_size,
            embed_dim=self.config.decoder.embed_dim,
            num_heads=self.config.decoder.num_heads,
            num_layers=self.config.decoder.num_layers,
            ffn_dim=self.config.decoder.ffn_dim,
            max_seq_len=self.config.decoder.max_seq_len,
            dropout=self.config.decoder.dropout,
        )

        self.reasoning_ai = ReasoningAI(
            embed_dim=self.config.reasoning_ai.embed_dim,
            num_heads=self.config.reasoning_ai.num_heads,
            num_layers=self.config.reasoning_ai.num_layers,
            ffn_dim=self.config.reasoning_ai.ffn_dim,
            control_dim=self.config.reasoning_ai.control_dim,
            max_seq_len=self.config.reasoning_ai.max_seq_len,
            dropout=self.config.reasoning_ai.dropout,
        )

        self.render_engine = RenderEngine()
        self.symbolic_engine = SymbolicEngine()
        self.proposition_manager = PropositionManager()

        self.event_sequence = EventSequence(
            event_dim=self.config.event.event_dim,
            max_events=self.config.event.max_events,
        )

        self.max_steps = 50
        self.control_threshold = 0.5

    def encode_proposition(self, proposition):
        """编码几何命题

        Args:
            proposition: 命题字符串或Proposition对象

        Returns:
            事件向量
        """
        # 如果是 Proposition 对象，转换为字符串
        if isinstance(proposition, Proposition):
            proposition_str = str(proposition)
        else:
            proposition_str = proposition

        token_ids = self.tokenizer.encode_with_special(proposition_str)
        input_tensor = torch.tensor([token_ids], dtype=torch.long)

        with torch.no_grad():
            event_vector = self.encoder(input_tensor)

        return event_vector.squeeze(0)

    def decode_event(self, event_vector: torch.Tensor) -> str:
        if event_vector.dim() == 1:
            event_vector = event_vector.unsqueeze(0)

        with torch.no_grad():
            generated = self.decoder.generate(
                event_vector,
                bos_id=self.tokenizer.bos_id,
                eos_id=self.tokenizer.eos_id,
                max_len=64,
            )

        token_ids = generated[0].tolist()
        statement = self.tokenizer.decode(token_ids)
        return statement

    def create_initial_event(self, proposition: str) -> Event:
        event_vector = self.encode_proposition(proposition)
        return Event(event_vector=event_vector)

    def reasoning_step(self) -> ReasoningStep:
        encoded_sequence = self.event_sequence.get_position_encoded()

        with torch.no_grad():
            event_vector, control_signal = self.reasoning_ai(encoded_sequence)

        step = ReasoningStep(event_vector=event_vector, control_signal=control_signal)

        use_render = control_signal[0, 0].item() > self.control_threshold
        use_decoder = control_signal[0, 1].item() > self.control_threshold

        if use_decoder or use_render:
            statement = self.decode_event(event_vector)
            step.decoded_statement = statement

            if use_render:
                try:
                    prop = GeometryParser.parse_proposition(statement)
                    is_valid = self.render_engine.verify_proposition(prop)
                    step.render_valid = is_valid
                    self.proposition_manager.add_rendered(statement, is_valid)
                except Exception as e:
                    print(f"渲染验证失败: {e}")
                    step.render_valid = False
            else:
                try:
                    prop = GeometryParser.parse_proposition(statement)
                    state = self.proposition_manager.get_proof_state()
                    is_valid = state.contains(prop)
                    step.symbolic_valid = is_valid
                    self.proposition_manager.add_symbolic(statement, is_valid)
                except Exception as e:
                    print(f"符号验证失败: {e}")
                    step.symbolic_valid = False

        return step

    def run_reasoning(
        self,
        initial_proposition: str,
        target: Optional[str] = None,
        max_steps: Optional[int] = None,
    ) -> Tuple[bool, List[ReasoningStep]]:
        self.reset()
        actual_max_steps = max_steps if max_steps is not None else self.max_steps

        initial_event = self.create_initial_event(initial_proposition)
        self.event_sequence.add_event(initial_event)

        steps: List[ReasoningStep] = []

        for _ in range(actual_max_steps):
            step = self.reasoning_step()
            steps.append(step)

            new_event = Event(
                event_vector=step.event_vector,
                is_success=step.symbolic_valid or step.render_valid,
            )
            self.event_sequence.add_event(new_event)

            if target and step.decoded_statement:
                if self._check_target_reached(step.decoded_statement, target):
                    return True, steps

            if self._should_stop(steps):
                break

        return False, steps

    def _check_target_reached(self, statement: str, target: str) -> bool:
        statement_tokens = set(self.tokenizer.tokenize(statement))
        target_tokens = set(self.tokenizer.tokenize(target))
        return target_tokens.issubset(statement_tokens)

    def _should_stop(self, steps: List[ReasoningStep]) -> bool:
        if len(steps) < 3:
            return False

        recent = steps[-3:]
        statements = [s.decoded_statement for s in recent if s.decoded_statement]

        if len(statements) == 3 and len(set(statements)) == 1:
            return True

        return False

    def reset(self):
        self.event_sequence = EventSequence(
            event_dim=self.config.event.event_dim,
            max_events=self.config.event.max_events,
        )
        self.render_engine.reset()
        self.symbolic_engine.reset()
        self.proposition_manager.clear()

    def load_models(self, path: str):
        checkpoint = torch.load(path)
        self.encoder.load_state_dict(checkpoint["encoder"])
        self.decoder.load_state_dict(checkpoint["decoder"])
        self.reasoning_ai.load_state_dict(checkpoint["reasoning_ai"])

    def save_models(self, path: str):
        checkpoint = {
            "encoder": self.encoder.state_dict(),
            "decoder": self.decoder.state_dict(),
            "reasoning_ai": self.reasoning_ai.state_dict(),
            "config": self.config,
        }
        torch.save(checkpoint, path)

    def count_parameters(self) -> Dict[str, int]:
        def count(model: nn.Module) -> int:
            return sum(p.numel() for p in model.parameters() if p.requires_grad)

        return {
            "encoder": count(self.encoder),
            "decoder": count(self.decoder),
            "reasoning_ai": count(self.reasoning_ai),
            "total": count(self.encoder)
            + count(self.decoder)
            + count(self.reasoning_ai),
        }


if __name__ == "__main__":
    system = GeometryReasoningSystem()

    params = system.count_parameters()
    print("模型参数:")
    for name, count in params.items():
        print(f"  {name}: {count:,}")

    print(f"\n总参数量: {params['total']:,}")
    print(f"小于0.05M (50,000): {params['total'] < 50000}")
