# GENERATED BY AI
"""几何题推理AI的主要工作流程。

定义推理系统的核心类和推理步骤的数据结构。
"""

from dataclasses import dataclass
from typing import Dict, List, Optional, Tuple, Union

import torch
from torch import nn

try:
    from .config import SystemConfig, get_default_config
    from .event_system import Event, EventSequence
    from .geometry_parser import GeometryParser, Proposition
    from .models import Decoder, Encoder, ReasoningAI
    from .proposition_manager import PropositionManager
    from .render_engine import RenderEngine
    from .symbolic_engine import SymbolicEngine
    from .tokenizer import GeometryTokenizer
except ImportError:
    from config import SystemConfig, get_default_config
    from event_system import Event, EventSequence
    from geometry_parser import GeometryParser, Proposition
    from models import Decoder, Encoder, ReasoningAI
    from proposition_manager import PropositionManager
    from render_engine import RenderEngine
    from symbolic_engine import SymbolicEngine
    from tokenizer import GeometryTokenizer


@dataclass
class ReasoningStep:
    """推理步骤数据结构，记录每一步推理的结果"""

    event_vector: torch.Tensor
    control_signal: torch.Tensor
    decoded_statement: Optional[str] = None
    symbolic_valid: Optional[bool] = None
    render_valid: Optional[bool] = None


class GeometryReasoningSystem:
    """几何推理系统主类

    整合编码器、解码器、推理AI和验证引擎，实现完整的几何证明流程。
    """

    def __init__(self, config: Optional[SystemConfig] = None):
        self.config = config if config is not None else get_default_config()
        self._init_models()
        self._init_engines()
        self._init_state()

    def _init_models(self) -> None:
        """初始化神经网络模型"""
        self.tokenizer = GeometryTokenizer(vocab_size=self.config.encoder.vocab_size)

        self.encoder = Encoder(
            vocab_size=self.config.encoder.vocab_size,
            embed_dim=self.config.encoder.embed_dim,
            num_heads=self.config.encoder.num_heads,
            num_layers=self.config.encoder.num_layers,
            ffn_dim=self.config.encoder.ffn_dim,
            max_seq_len=self.config.encoder.max_seq_len,
            dropout=self.config.encoder.dropout,
        )

        self.decoder = Decoder(
            vocab_size=self.config.decoder.vocab_size,
            embed_dim=self.config.decoder.embed_dim,
            num_heads=self.config.decoder.num_heads,
            num_layers=self.config.decoder.num_layers,
            ffn_dim=self.config.decoder.ffn_dim,
            max_seq_len=self.config.decoder.max_seq_len,
            dropout=self.config.decoder.dropout,
        )

        self.reasoning_ai = ReasoningAI(
            embed_dim=self.config.reasoning_ai.embed_dim,
            num_heads=self.config.reasoning_ai.num_heads,
            num_layers=self.config.reasoning_ai.num_layers,
            ffn_dim=self.config.reasoning_ai.ffn_dim,
            control_dim=self.config.reasoning_ai.control_dim,
            max_seq_len=self.config.reasoning_ai.max_seq_len,
            dropout=self.config.reasoning_ai.dropout,
        )

    def _init_engines(self) -> None:
        """初始化验证引擎"""
        self.render_engine = RenderEngine()
        self.symbolic_engine = SymbolicEngine()
        self.proposition_manager = PropositionManager()

    def _init_state(self) -> None:
        """初始化推理状态"""
        self.event_sequence = EventSequence(
            event_dim=self.config.event.event_dim,
            max_events=self.config.event.max_events,
        )
        self.max_steps = 50
        self.control_threshold = 0.5

    def encode_proposition(self, proposition: Union[str, Proposition]) -> torch.Tensor:
        """编码几何命题

        Args:
            proposition: 命题字符串或Proposition对象

        Returns:
            事件向量
        """
        proposition_str = (
            str(proposition) if isinstance(proposition, Proposition) else proposition
        )

        token_ids = self.tokenizer.encode_with_special(proposition_str)
        input_tensor = torch.tensor([token_ids], dtype=torch.long)

        with torch.no_grad():
            event_vector = self.encoder(input_tensor)

        return event_vector.squeeze(0)

    def decode_event(self, event_vector: torch.Tensor) -> str:
        """解码事件向量为命题字符串

        Args:
            event_vector: 事件向量

        Returns:
            解码后的命题字符串
        """
        if event_vector.dim() == 1:
            event_vector = event_vector.unsqueeze(0)

        with torch.no_grad():
            generated = self.decoder.generate(
                event_vector,
                bos_id=self.tokenizer.bos_id,
                eos_id=self.tokenizer.eos_id,
                max_len=64,
            )

        token_ids = generated[0].tolist()
        return self.tokenizer.decode(token_ids)

    def create_initial_event(self, proposition: str) -> Event:
        """创建初始事件

        Args:
            proposition: 命题字符串

        Returns:
            初始事件对象
        """
        event_vector = self.encode_proposition(proposition)
        return Event(event_vector=event_vector)

    def reasoning_step(self) -> ReasoningStep:
        """执行单步推理

        Returns:
            推理步骤结果
        """
        encoded_sequence = self.event_sequence.get_sequence_tensor()

        with torch.no_grad():
            event_vector, control_signal = self.reasoning_ai(encoded_sequence)

        step = ReasoningStep(event_vector=event_vector, control_signal=control_signal)

        use_render = control_signal[0, 0].item() > self.control_threshold
        use_decoder = control_signal[0, 1].item() > self.control_threshold

        if use_decoder or use_render:
            self._process_decoded_statement(step, use_render)

        return step

    def _process_decoded_statement(self, step: ReasoningStep, use_render: bool) -> None:
        """处理解码后的命题"""
        statement = self.decode_event(step.event_vector)
        step.decoded_statement = statement

        try:
            prop = GeometryParser.parse_proposition(statement)

            if use_render:
                is_valid = self.render_engine.verify_proposition(prop)
                step.render_valid = is_valid
                self.proposition_manager.add_rendered(statement, is_valid)
            else:
                state = self.proposition_manager.get_proof_state()
                is_valid = state.contains(prop)
                step.symbolic_valid = is_valid
                self.proposition_manager.add_symbolic(statement, is_valid)
        except Exception as e:
            print(f"验证失败: {e}")
            if use_render:
                step.render_valid = False
            else:
                step.symbolic_valid = False

    def run_reasoning(
        self,
        initial_proposition: str,
        target: Optional[str] = None,
        max_steps: Optional[int] = None,
    ) -> Tuple[bool, List[ReasoningStep]]:
        """运行完整推理流程

        Args:
            initial_proposition: 初始命题
            target: 目标命题（可选）
            max_steps: 最大推理步数

        Returns:
            (是否成功, 推理步骤列表)
        """
        self.reset()
        actual_max_steps = max_steps if max_steps is not None else self.max_steps

        initial_event = self.create_initial_event(initial_proposition)
        self.event_sequence.add_event(initial_event)

        steps: List[ReasoningStep] = []

        for _ in range(actual_max_steps):
            step = self.reasoning_step()
            steps.append(step)

            new_event = Event(
                event_vector=step.event_vector,
                is_success=step.symbolic_valid or step.render_valid,
            )
            self.event_sequence.add_event(new_event)

            if target and step.decoded_statement:
                if self._check_target_reached(step.decoded_statement, target):
                    return True, steps

            if self._should_stop(steps):
                break

        return False, steps

    def _check_target_reached(self, statement: str, target: str) -> bool:
        """检查是否达到目标"""
        statement_tokens = set(self.tokenizer.tokenize(statement))
        target_tokens = set(self.tokenizer.tokenize(target))
        return target_tokens.issubset(statement_tokens)

    def _should_stop(self, steps: List[ReasoningStep]) -> bool:
        """检查是否应该停止推理"""
        if len(steps) < 3:
            return False

        recent = steps[-3:]
        statements = [s.decoded_statement for s in recent if s.decoded_statement]

        return len(statements) == 3 and len(set(statements)) == 1

    def reset(self) -> None:
        """重置推理状态"""
        self.event_sequence = EventSequence(
            event_dim=self.config.event.event_dim,
            max_events=self.config.event.max_events,
        )
        self.render_engine.reset()
        self.symbolic_engine.reset()
        self.proposition_manager.clear()

    def load_models(self, path: str) -> None:
        """加载模型参数

        Args:
            path: 模型文件路径
        """
        checkpoint = torch.load(path, weights_only=False)
        self.encoder.load_state_dict(checkpoint["encoder"])
        self.decoder.load_state_dict(checkpoint["decoder"])
        self.reasoning_ai.load_state_dict(checkpoint["reasoning_ai"])

    def save_models(self, path: str) -> None:
        """保存模型参数

        Args:
            path: 保存路径
        """
        checkpoint = {
            "encoder": self.encoder.state_dict(),
            "decoder": self.decoder.state_dict(),
            "reasoning_ai": self.reasoning_ai.state_dict(),
            "config": self.config,
        }
        torch.save(checkpoint, path)

    def count_parameters(self) -> Dict[str, int]:
        """统计模型参数数量

        Returns:
            各模块参数数量字典
        """

        def count(model: nn.Module) -> int:
            return sum(p.numel() for p in model.parameters() if p.requires_grad)

        return {
            "encoder": count(self.encoder),
            "decoder": count(self.decoder),
            "reasoning_ai": count(self.reasoning_ai),
            "total": count(self.encoder)
            + count(self.decoder)
            + count(self.reasoning_ai),
        }
