# GENERATED BY AI
"""几何题推理AI的工作流。

该模块提供几何推理系统的主要工作流程。
"""

import torch
from torch import nn
from typing import Optional, List, Tuple, Dict
from dataclasses import dataclass

try:
    from .config import SystemConfig, get_default_config
    from .event_system import Event, EventSequence
    from .tokenizer import GeometryTokenizer
    from .models import Encoder, Decoder, ReasoningAI
    from .render_engine import RenderEngine
    from .symbolic_engine import SymbolicEngine
    from .proposition_manager import PropositionManager
except ImportError:
    from config import SystemConfig, get_default_config
    from event_system import Event, EventSequence
    from tokenizer import GeometryTokenizer
    from models import Encoder, Decoder, ReasoningAI
    from render_engine import RenderEngine
    from symbolic_engine import SymbolicEngine
    from proposition_manager import PropositionManager


@dataclass
class ReasoningStep:
    """推理步骤。"""
    event_vector: torch.Tensor
    control_signal: torch.Tensor
    decoded_statement: Optional[str] = None
    symbolic_valid: Optional[bool] = None
    render_valid: Optional[bool] = None


class GeometryReasoningSystem:
    """几何推理系统。"""

    def __init__(self, config: Optional[SystemConfig] = None):
        """初始化几何推理系统。"""
        self.config = config if config is not None else get_default_config()

        # 初始化组件
        self.tokenizer = GeometryTokenizer(vocab_size=self.config.encoder.vocab_size)
        self.render_engine = RenderEngine()
        self.symbolic_engine = SymbolicEngine()
        self.prop_manager = PropositionManager()

        # 初始化模型
        self.encoder = Encoder(
            vocab_size=self.config.encoder.vocab_size,
            embed_dim=self.config.encoder.embed_dim,
            num_heads=self.config.encoder.num_heads,
            num_layers=self.config.encoder.num_layers,
            ffn_dim=self.config.encoder.ffn_dim,
            max_seq_len=self.config.encoder.max_seq_len,
            dropout=self.config.encoder.dropout,
        )

        self.decoder = Decoder(
            vocab_size=self.config.decoder.vocab_size,
            embed_dim=self.config.decoder.embed_dim,
            num_heads=self.config.decoder.num_heads,
            num_layers=self.config.decoder.num_layers,
            ffn_dim=self.config.decoder.ffn_dim,
            max_seq_len=self.config.decoder.max_seq_len,
            dropout=self.config.decoder.dropout,
        )

        self.reasoning_ai = ReasoningAI(
            embed_dim=self.config.reasoning_ai.embed_dim,
            num_heads=self.config.reasoning_ai.num_heads,
            num_layers=self.config.reasoning_ai.num_layers,
            ffn_dim=self.config.reasoning_ai.ffn_dim,
            max_seq_len=self.config.reasoning_ai.max_seq_len,
            control_dim=self.config.reasoning_ai.control_dim,
            dropout=self.config.reasoning_ai.dropout,
        )

    def count_parameters(self) -> Dict[str, int]:
        """计算模型参数量。"""
        encoder_params = sum(p.numel() for p in self.encoder.parameters())
        decoder_params = sum(p.numel() for p in self.decoder.parameters())
        reasoning_ai_params = sum(p.numel() for p in self.reasoning_ai.parameters())

        return {
            "encoder": encoder_params,
            "decoder": decoder_params,
            "reasoning_ai": reasoning_ai_params,
            "total": encoder_params + decoder_params + reasoning_ai_params,
        }

    def encode_proposition(self, proposition: str) -> torch.Tensor:
        """编码几何命题为事件向量。"""
        # 使用分词器
        tokens = self.tokenizer.encode(proposition)

        # 转换为张量
        token_tensor = torch.tensor([tokens], dtype=torch.long)

        # 编码
        with torch.no_grad():
            event_vector = self.encoder(token_tensor)

        return event_vector.squeeze(0)

    def decode_event(self, event_vector: torch.Tensor) -> str:
        """解码事件向量为命题。"""
        # 添加批次维度
        event_vector = event_vector.unsqueeze(0)

        # 解码
        with torch.no_grad():
            output = self.decoder(event_vector)

        # 转换为 token
        tokens = output.argmax(dim=-1).squeeze(0).tolist()

        # 解码为文本
        return self.tokenizer.decode(tokens)

    def verify_symbolic(self, proposition: str) -> bool:
        """使用符号引擎验证命题。"""
        # 添加命题到符号引擎
        self.symbolic_engine.add_statement(proposition)

        # 尝试推导
        self.symbolic_engine.deduce(max_steps=10)

        # 检查是否可验证
        return self.symbolic_engine.verify(proposition)

    def verify_render(self, proposition: str) -> bool:
        """使用渲染引擎验证命题。"""
        result, msg = self.render_engine.render_and_verify(proposition)
        return result

    def solve_problem(
        self,
        problem: str,
        max_steps: int = 100
    ) -> Tuple[bool, List[ReasoningStep]]:
        """解决几何问题。"""
        # 重置引擎
        self.symbolic_engine.reset()
        self.render_engine.reset()
        self.prop_manager.clear()

        # 解析问题
        premises = problem.split(';')

        # 添加前提
        for premise in premises:
            premise = premise.strip()
            if premise:
                self.symbolic_engine.add_statement(premise)
                self.prop_manager.add_symbolic(premise, True)

        # 推理步骤
        reasoning_steps: List[ReasoningStep] = []

        for step in range(max_steps):
            # 生成新事件（这里简化处理）
            # 对于演示，我们使用符号引擎的推导
            new = self.symbolic_engine.apply_rules()

            if not new:
                break

            # 处理新命题
            for stmt in new:
                stmt_str = str(stmt)

                # 编码
                event_vector = self.encode_proposition(stmt_str)

                # 验证
                symbolic_valid = self.symbolic_engine.verify(stmt_str)
                render_valid = self.verify_render(stmt_str)

                # 添加到命题管理器
                if symbolic_valid:
                    self.prop_manager.add_symbolic(stmt_str, True)
                if render_valid:
                    self.prop_manager.add_rendered(stmt_str, True)

                # 创建推理步骤
                step_obj = ReasoningStep(
                    event_vector=event_vector,
                    control_signal=torch.tensor([0.0, 0.0]),
                    decoded_statement=stmt_str,
                    symbolic_valid=symbolic_valid,
                    render_valid=render_valid,
                )
                reasoning_steps.append(step_obj)

        return len(reasoning_steps) > 0, reasoning_steps


if __name__ == "__main__":
    system = GeometryReasoningSystem()

    params = system.count_parameters()
    print("模型参数:")
    print(f"  编码器: {params['encoder']:,}")
    print(f"  解码器: {params['decoder']:,}")
    print(f"  推理AI: {params['reasoning_ai']:,}")
    print(f"  总计: {params['total']:,}")
    print(f"  小于0.05M: {params['total'] < 50000}")

    # 测试编码和解码
    proposition = "perp A B C D"
    print(f"\n编码命题: '{proposition}'")

    event_vector = system.encode_proposition(proposition)
    print(f"事件向量形状: {event_vector.shape}")

    decoded = system.decode_event(event_vector)
    print(f"解码命题: '{decoded}'")
